### ISSUE TITLE
priority of snpEff effects

### ISSUE THREAD

**Issue by dgaston** [arq5x/gemini#100]
What are the rules by which gemini decides between snpEff effect predictions? I know it is attempting to take one effect with the strongest predicted effect, but how does it prioritize? Browsing in the code I see the various effects are assigned an impact priority number, but obviously many of them are tied.

Just curious as in some of my work "downstream" seems to be trumping (or tied) with intronic for the reported effect.

**Comment by arq5x** [comment]
Documented in geneimpacts module.
