### ISSUE TITLE
Multiple alternative alleles

### ISSUE THREAD

**Issue by erscott** [arq5x/gemini#161]
Thanks for the great tool, it's very helpful to have an off-the-shelf genomics RDB.

I have noticed that GEMINI does not handle multiple alternative alleles.  GEMINI also seems to assume any alternative allele with a length > 1 is an indel.  

Here are a few examples where the type/sub_type is mistaken.  I know that the formatting of some of the following variants is wrong (e.g. CCG CCA), but I think they are useful to show potential edge cases.

These misannotations will affect the SNP, MNP, indel counts and also cause imprecise reporting of num_het, num_hom_alt etc.  

I am happy to help work through the source code to split alternative alleles into separate records, but I don't want to duplicate efforts if this is already under revision.

Thanks.

> gemini query -q "select chrom,start,end,ref,alt,aaf,type,sub_type,num_hom_ref,num_het,num_hom_alt from variants where end>790750 and end<790770" my.db

chr1	790755	790760	GTGTA	GTG,G,GTGTG	None	indel	unknown	10	97	268

> gemini query -q "select chrom,start,end,ref,alt,aaf,type,sub_type,num_hom_ref,num_het,num_hom_alt from variants where end>808625 and end<808640" my.db

chr1	808628	808631	CCG	CCA	0.763661202186	indel	ins	23	127	216

> gemini query -q "select chrom,start,end,ref,alt,aaf,type,sub_type,num_hom_ref,num_het,num_hom_alt from variants where end>812825 and end<812832" my.db

chr1	812826	812829	CTC	TCT	0.00134408602151	indel	ins	371	1	0

> gemini query -q "select chrom,start,end,ref,alt,aaf,type,sub_type,num_hom_ref,num_het,num_hom_alt from variants where end>801300 and end<801310" my.db

chr1	801305	801308	ACC	GTT	0.00134770889488	indel	ins	370	1	0

> gemini query -q "select chrom,start,end,ref,alt,aaf,type,sub_type,num_hom_ref,num_het,num_hom_alt from variants where end>805100 and end<805109" my.db

chr1	805101	805103	CG	AA,CT	None	indel	unknown	374	2	0

**Comment by brentp** [comment]
this can be closed.

**Comment by arq5x** [comment]
Thanks to @brentp, full support for multiple alternate alleles is available in master and will be in the forthcoming release.

**Comment by jxchong** [comment]
I think this hasn't been included yet:
It would be very useful to support multiple alt alleles when using a bed/vcf(-like) file with the annotate tool.

We (and others) use an internal database of NGS data for frequency exclusion (because you have a large control set of exomes/genomes from a population not represented in 1KG/ExAC/ESP and/or because you want to filter out pipeline-specific artifacts. If you have multiple alt alleles and one is an artifact/common while the other is your causal mutation, you obviously don't want to exclude the entire position, just the common/artifact allele.

**Comment by arq5x** [comment]
Brent is working on that right now.  Will be in the forthcoming release.

**Comment by jxchong** [comment]
Awesome thanks!

**Comment by arq5x** [comment]
In the context of multiple alts, proper annotation with a VCF will require that the annotation VCF is also decomposed and normalized in the same way as the VCF that was loaded into GEMINI.

Decomposition and normalization will be required pre-processing steps for all input VCFs in the next release.

**Comment by brentp** [comment]
@jxchong we think that forcing decomposition + normalization before is the best way and should improve the annotation. But, there could be use-cases or ways of doing this we haven't thought of so let us know.

The vt software (https://github.com/atks/vt) is quite good at doing this now and the developer is fixing bugs as we report them.
