### ISSUE TITLE
Add Exome Sequencing Project annotations

### ISSUE THREAD

**Issue by arq5x** [arq5x/gemini#2]
New columns should be added to the `variants` table describing the EA, AA, and ALL allele frequencies observed in the NHLBI Exome Sequencing Project data.  In addition, we need a column indicating whether or not a variant is on the "Exome chip".

**Comment by Vaidhy-M** [comment]
Hi, what does an allele frequency of -1 mean?

**Comment by arq5x** [comment]
This means that the variant was not observed and hence the AF is unknown in that cohort.

**Comment by Vaidhy-M** [comment]
If there is a rs_id associated with the variant is it still possible for a variant to have AF -1?
