### ISSUE TITLE
Installation issues (numpy, scipy, Cython...)

### ISSUE THREAD

**Issue by amanjeev** [arq5x/gemini#313]
This is really not a bug but just an FYI. I searched the issue logs and did not find anything reported about it. My apologies if this is already known or reported.

Once it was installed, the installation was smooth. Please note that I had `numpy` install via `yum` but still needed to install `numpy-f2py`.

`sudo yum install numpy-f2py`

My OS is CentOS 6.

**Comment by RatnamRaju** [comment]
[root@localhost home]# gemini -v
Traceback (most recent call last):
  File "/usr/bin/gemini", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2659, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: numexpr>=2.4.3

**Comment by chapmanb** [comment]
Thanks for the problem report. You reported this in multiple locations (also https://github.com/arq5x/gemini/issues/215#issuecomment-104985271 and https://github.com/chapmanb/bcbio-nextgen/issues/143#issuecomment-104985293) and I'll try to tackle in one place.

Can you provide more context about how you installed gemini? Specifically it looks like you're using python2.6 which won't work cleanly with GEMINI. Following the automated installation approach is the best approach to install GEMINI:

http://gemini.readthedocs.org/en/latest/content/installation.html#automated-installation

Happy to provide more specific advice with additional information.

**Comment by RatnamRaju** [comment]
@chapmanb Thanks for your reply, I fixed the issue by running following command

yum install python-argparse

Thanks
