### ISSUE TITLE
hg38 + multiallelic calls?

### ISSUE THREAD

**Issue by parlar** [arq5x/gemini#367]
I feel that it is important to move to hg38 as soon as possible, due to mapping issues caused by paralogs not present in hg19. Will there be support for hg38? A request for future versions is also handling handling of multiallelic calls.
Thanks for making this great tool!

**Comment by arq5x** [comment]
I completely agree and these are a part of our plan.  We will likely address multiple allele support first, as we need to come up with a detailed plan for supporting build 38 given that many annotations are only available for build 37.

**Comment by arq5x** [comment]
Multi-allelic support is now in master and will be part of the forthcoming release.

hg38 support is in the works but will take several months.
