### ISSUE TITLE
Restrict de novo variants to _affected_ individuals in de_novo built-in tool

### ISSUE THREAD

**Issue by oleraj** [arq5x/gemini#371]
I think this should probably be the default or else it could be done optionally, with a flag such as --only-affected like comp_hets has.  For example, this variant should not show up in the results: 

DS-101725(father; unaffected),DS-101850(mother; unaffected),DS-101749(child; unaffected),DS-101762(child; affected),DS-101780(child; unaffected)	T|T,T|T,T/T,T|T,T/A

The variant is only present in the unaffected child so it is not interesting.

Thanks,

Andrew

**Comment by arq5x** [comment]
Thanks for bringing this up.  I have added the --only-affected option with commit 0d89f70.

**Comment by oleraj** [comment]
Thanks, I'll give it a try!

Andrew
