### ISSUE TITLE
ram recommendations

### ISSUE THREAD

**Issue by deanasnyder** [arq5x/gemini#376]
We would like to run Gemini in our own Galaxy instance here at CIDR, but are having a hard time trying to figure out how much RAM we should plan for in setting up our VM. We will be analyzing VCF files with 100's of samples in them, and typically 5-6 gB in size.

Any recommendation you could give would be greatly appreciated.

**Comment by arq5x** [comment]
The RAM requirements should be very low. @bgruening do you have any recommendations here?

**Comment by bgruening** [comment]
We have limited `gemini load`to 10GB in our scheduler. But it should be way less. The querying tools will need < 4GB.
@deanasnyder please let me know what are your experiences with gemini and Galaxy.

**Comment by deanasnyder** [comment]
"please let me know what are your experiences with gemini and Galaxy."

Will do. We are planning to do a simple, default, single box Galaxy install at first. Then, if we like the results (ignoring performance, of course), we plan to do a production install of Galaxy and Gemini.

Which reminds me - I had another, very different question. Have you considered doing vcf conversion to a graph database?

**Comment by bgruening** [comment]
@deanasnyder Sounds good. Even if you don't like the results, please tell me! ;)

Regarding graph database: no clue, but @arq5x is working on postgresql integration.
