### ISSUE TITLE
recommended gemini revision in galaxy toolshed

### ISSUE THREAD

**Issue by deanasnyder** [arq5x/gemini#377]
I'm now ready to install gemini in our local galaxy instance but don't know which revision I should install. When I do a toolshed search on "gemini" it returns these four: 

d3c4d0208bb2
93bb0cfacefb
720cbfb4190d
ba3abde6775b.

Which should I install? (And maybe, what's the differences between them?)

Do I need to install a data_manager_gemini_database_downloader? If so which one?

**Comment by bgruening** [comment]
`ba3abde6775b` is the latest one. How do you install gemini with the Tool Shed? You should not see the revision number and the latest version should be installed by default. Latest means with bugfixes. The difference you can inspect in the Tool Shed if you click `view history`.

You need the data_manager to install geminis annotation databases. But this repository is automatically installed (as repository dependency) if you install the gemini repository. You can see all dependencies in the repository description in the Tool Shed and can browse those.

**Comment by deanasnyder** [comment]
"How do you install gemini with the Tool Shed? You should not see the revision number and the latest version should be installed by default."

I just did a toolshed search on "gemini" from the admin interface and it listed all the revisions.

**Comment by bgruening** [comment]
How old is your Galaxy instance?

![gemini_from_toolshed](https://cloud.githubusercontent.com/assets/469983/6190480/8c44f502-b3a2-11e4-8276-8bc323bd48f0.png)

This is how it should look like :)

**Comment by deanasnyder** [comment]
downloaded latest yesterday

**Comment by deanasnyder** [comment]
I just attempted an install and everything installed except:
 data_manager_gemini_database_downloader
gemini
package_gemini_0_10_0

In the "Manage installed tool shed repositories" section of admin they are listed as "Installed, missing tool dependencies".
