### ISSUE TITLE
Test transposed ped (TPED) query format - Fails for query.t22,t26,t27

### ISSUE THREAD

**Issue by nfarzaneh** [arq5x/gemini#385]
Hello,

> query.t22...\c
> 1,9c1,9
> < 10 1 0 1142207 C C C C C C C C
> < 10 2 0 48003991 T T C T C T C C
> < 10 3 0 52004314 0 0 0 0 C C C C
> < 10 4 0 52497528 0 0 C C C C 0 0
> < 10 5 0 126678091 G G G G G G G A
> < 10 6 0 135210790 T T C C C C T T
> < 10 7 0 135336655 0 0 A A 0 0 A A
> < 10 8 0 135369531 T T T C T C T T
> < 16 9 0 72057434 C T C C C C C C
> 
> \> 10 10:1142207-1142208:T|C:1 0 1142207 C C C C C C C C
> \> 10 10:48003991-48003992:C|T:2 0 48003991 T T C T C T C C
> \> 10 10:52004314-52004315:T|C:3 0 52004314 0 0 0 0 C C C C
> \> 10 10:52497528-52497529:G|C:4 0 52497528 0 0 C C C C 0 0
> \> 10 10:126678091-126678092:G|A:5 0 126678091 G G G G G G G A
> \> 10 10:135210790-135210791:T|C:6 0 135210790 T T C C C C T T
> \> 10 10:135336655-135336656:G|A:7 0 135336655 0 0 A A 0 0 A A
> \> 10 10:135369531-135369532:T|C:8 0 135369531 T T T C T C T T
> \> 16 16:72057434-72057435:C|T:9 0 72057434 C T C C C C C C
> fail

======================================================

> query.t26...\c
> 0a1,5
> \> T/T,T/T,T/C,T/T,T/T,T/T,T/T,T/T,C/C	0,0,1,0,0,0,0,0,3
> \> C/T,C/T,T/T,C/C,C/C,C/T,C/T,C/T,C/T	1,1,3,0,0,1,1,1,1
> \> C/T,C/T,C/T,C/T,C/T,T/T,C/C,C/C,C/T	1,1,1,1,1,3,0,0,1
> \> G/G,G/G,G/A,G/G,G/G,G/A,G/A,G/A,G/A	0,0,1,0,0,1,1,1,1
> \> T/T,T/T,T/C,T/T,T/T,T/C,T/T,T/T,T/C	0,0,1,0,0,1,0,0,1
> fail

============================================

> query.t27...\c
> 2,4d1
> < C/T,C/T,T/T,C/C,C/C,C/T,C/T,C/T,C/T	1,1,3,0,0,1,1,1,1
> < C/T,C/T,C/T,C/T,C/T,T/T,C/C,C/C,C/T	1,1,1,1,1,3,0,0,1
> < G/G,G/G,G/A,G/G,G/G,G/A,G/A,G/A,G/A	0,0,1,0,0,1,1,1,1
> 7d3
> < T/T,T/T,T/T,T/T,T/T,T/T,T/T,T/C,T/C	0,0,0,0,0,0,0,1,1
> fail

=============================================

What can I do to fix these errors?  And are these problematic?

I am running gemini 0.11.1a on Ubuntu 14.04.2.  The master-test wasn't giving me any errors before.

Thanks a lot!
Nima

**Comment by arq5x** [comment]
Hi Nima,

It looks as though these failures are the result of a formatting change in the way the TPED output is handled.  They should not affect GEMINI's broader functionality.

@brentp - these are the same tests that were failing for you, correct?

**Comment by brentp** [comment]
yes, test22 was failing. It does just look like a representation change.

**Comment by roryk** [comment]
Sorry about the failing test22, I swapped to using the variant_id as the id since it was easier to join metadata to the values from the rest of the database, but forgot to update the test.  @nfarzaneh  feel free to reopen if this didn't actually fix it, and thank you for reporting it.
