### ISSUE TITLE
Empty comp_hets and autosomal_recessive outputs for family trio

### ISSUE THREAD

**Issue by dkoboldt** [arq5x/gemini#387]
Hello,

We're trying to run GEMINI 0.11.1a on a family trio of exome data. We loaded the database and PED file, and were able to run the de novo command with expected results (suggesting the PED structure is correctly interpreted). However, when we try to run comp_hets or autosomal_recessive or even autosomal_dominant, we get only a header (no output).

We ran the stats commands and variant/genotype counts look good. Any advice?

**Comment by arq5x** [comment]
My first suspicion would be that the phenotypes for mom, dad, and proband are not labelled correctly (should be 1,1,2) respectively (IIRC).

- Aaron

**Comment by dkoboldt** [comment]
Aaron: we checked that, and I don't think it's the issue. Here's the PED:

FamilyA	FamilyA-Child	FamilyA-Dad	FamilyA-Mom	2	2
FamilyA	FamilyA-Dad	0	0	1	1
FamilyA	FamilyA-Mom	0	0	2	1

**Comment by arq5x** [comment]
Not sure then. Any chance you can share the first 10000 lines of the VCF so
I can investigate?

**Comment by arq5x** [comment]
You could also check the contents of the samples table to ensure there
wasn't any odd parsing of your PED file: gemini query -q "select * from
samples" --header

**Comment by dkoboldt** [comment]
I will see about a partial VCF. I'd try the query thing, but any attempts to run "gemini query -q" give us a "gemini: error: unrecognized arguments" error.

**Comment by arq5x** [comment]
Ouch, sorry for the trouble. It sounds as though your GEMINI installation
may be borked.

**Comment by dkoboldt** [comment]
They just installed it last week! Any advice for troubleshooting the installation?

**Comment by arq5x** [comment]
Not sure.  It is confusing because you can actually run the auto_rec and
comp_hets tools, but you are getting that odd "unrecognized argument" error
with the query tool.

What happens for each of the following commands:

1. gemini --version
2. gemini query --help
3. gemini query -q "select * from samples" DAN.DB

**Comment by dkoboldt** [comment]
I think we figured out the issue with the query, and are putting in the request to have that fixed. It might resolve the other pieces as well; will keep you posted

**Comment by arq5x** [comment]
Closing, but if still an issue, please reopen.
