### ISSUE TITLE
Issue with Gemini load and ESP6500 annotation

### ISSUE THREAD

**Issue by jdh237** [arq5x/gemini#411]
Here is the error from a standard 'gemini load':

Traceback (most recent call last):
  File "/software/gemini/tools/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 225, in loadchunk_fn
    gemini_load_chunk.load(parser, args)
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 697, in load
    gemini_loader.populate_from_vcf()
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 117, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var)
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 311, in _prepare_variation
    esp = annotations.get_esp_info(var)
  File "/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/annotations.py", line 592, in get_esp_info
    aaf_EA = float(lines[0]) / (float(lines[0]) + float(lines[1]))

Digging into it a bit, it seems that the 'tidied' ESP data file has a couple of issues. First, there are entries in the file like this -- 

1       6638842 .       CGCTGCTGCT      C       .       PASS    DBSNP=.;EA_AC=0,0,8254;AA_AC=1,2,4265;TAC=1,2,12519;MAF=0.0,0.0703,0.024;GTS=A1A1,A1A2,A1R,A2A2,A2R,RR;EA_GTC=0,0,0,0,0,4127;AA_GTC=0,0,1,0,2,2131;GTC=0,0,1,0,2,6258;DP=40;GL=TAS1R1;CP=0;CG=4.1;AA=.;CA=.;EXOME_CHIP=no;GWAS_PUBMED=.;GM=NM_138697.3,NM_177540.2;FG=codingComplex,codingComplex;AAC=.,.;PP=.,.;CDP=.,.;GS=.,.;PH=.,.;OLD_MULTIALLELIC=1:6638842:CGCTGCTGCT/C/CGCTGCTGCTGCTGCTGCT

The EA_AC, AA_AC, and TAC INFO fields are not normalized correctly by the tidying process. The reason seems to be a combination of factors. The header information in this file includes this --

##INFO=\<ID=EA_AC,Number=.,Type=String,Description="European American Allele Count in the order of AltAlleles,RefAllele. For INDELs, A1, A2, or An refers to the N-th alternate allele while R refers to the reference allele."\>

In order for 'vt' to normalize this properly, the Number=. needs to be changed to Number=R, and the Type=String needs to be Type=Integer (or maybe vt should be modified to allow for String's?). Doing that almost fixes the problem, except that the ESP6500 vcf file seems to have the allelic information in the wrong order. Or maybe this is an ambiguity in the VCF 4.2 spec? In any case, they have the reference listed last instead of first. Rearranging those fields still leaves a very small number of 'division by zero' errors. The annotations.py script may need a small change to allow for EA_AC=0,0 entries.

-Jason

**Comment by arq5x** [comment]
Hi Jason,

Thanks for reporting this, as our tests never revealed this problem. It looks as though the ESP file, like Clinvar, we need some TLC to work with vt. We will have a look asap a thanks for the informative head start.

- Aaron

**Comment by brentp** [comment]
Hi Jason, thanks for reporting. I am sure this is fixed in the dev branch, but I'd like to add a test-case to make sure. I can't get our whole-genome VCFs to error on master. Can you send a row or 2 with this problem?

**Comment by jdh237** [comment]
Hi Brent,

I fixed my local install a couple of days ago, so I can't easily verify again, but here are a few of the variants that I think triggered the problem:

1	213068542	rs41301015	C	CTGAT	810733.6	PASS
1	237663969	rs141873907	TA	T	60238.7	PASS
4	110884488	rs11568954	G	GA	7951.9	PASS

Thanks!

-Jason

**Comment by brentp** [comment]
Hi Jason, I am able to recreate a ZeroDivision error on master now with those entries. Thanks for the test-case. We will be coming out with this fix and lots of speed improvements this week.
