### ISSUE TITLE
Issue with new snpEff annotations in classic mode

### ISSUE THREAD

**Issue by dgaston** [arq5x/gemini#415]
Even in -classic and -formatEff the new snpEff (4.1) has changed SPLICE_SITE_REGION to SPLICE_SITE_REGION+INTRON which prevents parsing of the snpeff effects for these sites by GEMINI

**Comment by arq5x** [comment]
Thanks for this. Can you tell if it also still produces SPLICE_SITE_REGION or is it a complete replacement?

We should look at their docs to see what else may have changed as this is an important source of false negatives

**Comment by brentp** [comment]
I'll look into the changelog. If it just allows multiples now, it looks like an easy fix in func_impact to loop over impact_string.split("+")

**Comment by dgaston** [comment]
Looks like both are present

**Comment by dgaston** [comment]
Good catch @brentp, I hadn't gone into the documentation enough to see that in the changelogs. Just ran a quick test and it seems that is the case.

**Comment by brentp** [comment]
I don't see this in the changes: http://snpeff.sourceforge.net/features.html
But I think that's because the concentration is on ANN. 

@dgaston, any chance that you could share a header and a few lines with this problem?

**Comment by brentp** [comment]
@arq5x does that seem reasonably to loop over impact_string.split('+') here:

https://github.com/arq5x/gemini/blob/5398efd2de9b57934d2afe63d47c8533ebd1fc30/gemini/func_impact.py#L35-55

?

**Comment by arq5x** [comment]
This challenge is then which annotation to store. Let me give it some thought...

**Comment by brentp** [comment]
variant_impacts are already many to one, or is there another issue?

**Comment by dgaston** [comment]
Yup, I am not in the office at the moment but will post as soon as I can.

**Comment by dgaston** [comment]
Sample '+' lines (SPLICE_SITE_REGION): http://pastebin.com/raw.php?i=CiTqKpe8
VCF header: http://pastebin.com/raw.php?i=0invvc3W

You'll notice in the VCF header there are a couple of snPEff entries from different rounds of SnpSift RmInfo and reannotating.

**Comment by arq5x** [comment]
Thanks much, Daniel. Given that these new types come from -classic and we already have a goal (https://github.com/arq5x/gemini/issues/383) of supporting version 4.0 and abaove, I think perhaps the best solution here would be to update GEMINI to expect snpEff >=4.0.  Otherwise, I fear that we be left in a state of applying consecutive patches for these new terms.  

In the interim, you could run snpEff <= 3.6 to reproduce prior results.
Thoughts?

**Comment by dgaston** [comment]
I agree absolutely that just updating to a newer version of snpEff is the best solution long term. Putting some notice in the current documentation about the issue would probably be a good bet so people know. You can easily pull all of these variants by querying for "impact_sevierity is NULL" as a SQL where clause.

**Comment by arq5x** [comment]
Yep, we should add a warning in the interim. Thanks Daniel.
