### ISSUE TITLE
vcftidy error

### ISSUE THREAD

**Issue by nfarzaneh** [arq5x/gemini#422]
Hello,

I get the following error while running vcftidy on my VCF file:

Traceback (most recent call last):
  File "/home/ubuntu/software/vcftidy-master/vcftidy.py", line 527, in <module>
    sys.exit(main(fh, ref))
  File "/home/ubuntu/software/vcftidy-master/vcftidy.py", line 495, in main
    for v in gen_variants(fh):
  File "/home/ubuntu/software/vcftidy-master/vcftidy.py", line 472, in gen_variants
    fields[1], fields[3], fields[4] = leftnorm(fields[0], pos, ref, alts[0], fa)
  File "/home/ubuntu/software/vcftidy-master/vcftidy.py", line 440, in leftnorm
    return normalize(*leftalign(chrom, pos, ref, alt, fa), left_only=True)
  File "/home/ubuntu/software/vcftidy-master/vcftidy.py", line 322, in leftalign
    assert seq.endswith(ref), (chrom, pos, ref, alt, seq[-10:])
AssertionError: ('chr1', 893981, 'C', 'T', u'ctcttcagcc')

I do not get any errors using vt, but the docs mentioned that vcftidy is better to use.

Is there a conflict between the call and the reference genome?  I used the same reference genome for both.

Happy to provide more information.  I can send you the vcf file with that specific entry if you like.  Thanks in advance.  Great new update!

GEMINI: 0.12.2
OS: Ubuntu 14.04.2 LTS

Kind regards,
Nima Farzaneh

**Comment by brentp** [comment]
Hi Nima, since the last release, vt has fixed the problems that made us recommend vcftidy. So, please use that instead (make sure you get the latest version from github). We will update the docs and I'll look into this for vcftidy.py. That would be great if you could provide the entry.

**Comment by nfarzaneh** [comment]
OK I just sent you an email with the VCF file that is causing this issue.  I will be using vt from now on.
