### ISSUE TITLE
Automated installation fails due to interactions with existing .local/lib/python2.7/site-packages/

### ISSUE THREAD

**Issue by bw2** [arq5x/gemini#426]
I originally installed gemini from source, but then decided to try the anaconda-based auto-install to see if that would solve an issue I was having.

I assumed the anaconda environment would be isolated from other python installs, but this wasn't the case. The auto-install ran into trouble due to interactions with ~/.local/bin and ~/.local/lib/python2.7/site-packages.

In my first attempt, the auto-install completed successfully, but when I went to run gemini, the executable `anaconda/bin/gemini` was missing. This was resolved after I deleted ~/.local/bin/gemini and re-ran the automated install from scratch.

Next, the install again completed, but when I launched the gemini tests, they all failed with weird errors: 

```
Are you trying to `import zmq` from the pyzmq source dir?
Traceback (most recent call last):
  File "/humgen/atgu1/fs03/weisburd/gemini_install/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1141, in main
    args.func(parser, args)
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 134, in load_fn
    import gemini_load
  File "/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 11, in <module>
    from cluster_helper.cluster import cluster_view
  File "/home/unix/weisburd/.local/lib/python2.7/site-packages/ipython_cluster_helper-0.4.3-py2.7.egg/cluster_helper/cluster.py", line 21, in <module>
    from IPython.parallel import Client
  File "/home/unix/weisburd/.local/lib/python2.7/site-packages/ipython-3.0.0-py2.7.egg/IPython/parallel/__init__.py", line 21, in <module>
    import zmq
  File "/home/unix/weisburd/.local/lib/python2.7/site-packages/zmq/__init__.py", line 62, in <module>
    raise ImportError("%s\nAre you trying to `import zmq` from the pyzmq source dir?" % e)
ImportError: /home/unix/weisburd/.local/lib/python2.7/site-packages/zmq/utils/initthreads.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8
```

The auto-install only worked after I moved aside ~/.local and reinstalled from scratch one more time. Now all tests pass. 

A possible work around (other than deleting ~/.local/) might be to use `export PYTHONNOUSERSITE=1` as described in  https://github.com/conda/conda/issues/394 although I haven't tested this.

**Comment by brentp** [comment]
hi @bw2 is PYTHONHOME or PYTHONPATH set? @chapmanb recently commited a fix for this.

**Comment by bw2** [comment]
@brentp I did add some unrelated directories to my PYTHONPATH, but AFAIK those didn't change anything.  I just double-checked, and python is automatically adding '~/.local/lib/python2.7/site-packages' to sys.path regardless of what PYTHONPATH is set to, so I'm not sure that   https://github.com/arq5x/gemini/commit/cf5340acbac5583cf0e0ddf9a2fe4aa602e296ea will help.

**Comment by chapmanb** [comment]
Thanks much for the tip on `PYTHONNOUSERSITE`, that is a really useful option I didn't know about. I added documentation about that and added it to the variables we scrub during installation, as well as ignoring it explicitly when calling the GEMINI script with the `-s` flag. If you run an `update --devel` or add the `-s` flag manually to the `anaconda/bin/gemini` command, I hope that will resolve your issue and skip using the `.local` directory at all. Thanks again for the tips and feedback.

**Comment by bw2** [comment]
Thanks for the quick response @chapmanb. I didn't know about the -s option - that's going to be really useful. 

I updated, but am now getting 
```
$ gemini
Unknown option: - 
usage: /humgen/atgu1/fs03/weisburd/gemini_install/anaconda/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```
where the gemini script starts with:
```
#!/humgen/atgu1/fs03/weisburd/gemini_install/anaconda/bin/python -E -s
```
This seems to be an issue with how my shell handles shebangs, and the only work around I can find is described here:
http://stackoverflow.com/questions/17458528/why-does-this-snippet-work

**Comment by chapmanb** [comment]
Ben;
Apologies, that is my fault. I pushed a fix which uses the shortened syntax (`-Es`) which seems to avoid the problem. Hope that fixes everything for you.

**Comment by bw2** [comment]
Oh nice! That does fix it.

Thanks
-Ben

**Comment by brentp** [comment]
@arq5x or @chapmanb can close this.
