### ISSUE TITLE
Loading of new annotation standard 'ANN' field

### ISSUE THREAD

**Issue by nuada** [arq5x/gemini#442]
Hi,

is anyone currently working on implementation of parser for new ANN annotation standard used by snpEff?
I would like to try to implement this, but I don't want to get in way of someone's work. It is mentioned in release notes. And this would probably require some refactoring of how VEP and snpEff annotation is handled right now.

Would you mind if I tried?

This would affect issues: #383, #415.

**Comment by arq5x** [comment]
Hi @nuada - that would be fantastic if you have the time. It is on our list, but we haven't gotten to it yet.

**Comment by brentp** [comment]
Yes, that would be excellent. Please start from the dev branch as we're accumulating changes there.

**Comment by nuada** [comment]
OK, thank you.

**Comment by nuada** [comment]
Quick question.
Before implementing anything I need to be sure that I have unit tests for part of code I want to fix. But I can't find tests that check how GEMINI handles different versions of snpEff or VEP.
Where can I find them?

**Comment by brentp** [comment]
@nuada currently, all of the tests are functional tests in the test/ directory. It would be better to have unit tests...

**Comment by arq5x** [comment]
Also, the bulk of the relevant functional tests are in:
https://github.com/arq5x/gemini/blob/master/test/test-effstring.sh

As @brentp mentioned, the testing here is a bit weak. ;)
