### ISSUE TITLE
Better backwards compatibility

### ISSUE THREAD

**Issue by arq5x** [arq5x/gemini#446]
When new `gt_*` columns are added to the database in a new version, the GeminiQuery logic will break for databases created from earlier versions of GEMINI, since GeminiQuery explicitly queries for all `gt_*` columns when a user does a `select * from variants` query.  This yields a "column not found" error.  We should have checks in the code to make sure that an appropriate database version is present and if not, cull the column list to solely those columns that should be present for the given version.

Similarly, we need tools and options in the tools to be more backwards compatible.  For example, the new mendelian_errors tool will break for older Dbs since the PL columns are not present.  Thanks to @drmjc for bringing this up.

**Comment by drmjc** [comment]
excellent, thanks @arq5x

**Comment by VelNZ** [comment]
+1
