### ISSUE TITLE
fail in master_test.sh

### ISSUE THREAD

**Issue by mjsduncan** [arq5x/gemini#456]
hi, master-test.sh had 2 fails on my fresh install of gemini 0.14.0 on ubuntu 14.04:

    cadd.t01...\c
2,4c2,4
< chr1	30859	30860	G	C	-0.92	0.39
< chr1	69269	69270	A	G	-1.34	0.03
< chr1	69510	69511	A	G	-1.72	0.01
..
> chr1	30859	30860	G	C	None	None
> chr1	69269	69270	A	G	None	None
> chr1	69510	69511	A	G	None	None
6,7c6,7
< chr1	879675	879676	G	A	0.56	7.02
< chr1	935491	935492	G	T	0.79	8.17
..
> chr1	879675	879676	G	A	None	None
> chr1	935491	935492	G	T	None	None
9,10c9,10
< chr3	60830533	60830534	A	T	0.18	4.98
< chr3	60830762	60830763	G	T	-1.65	0.01
..
> chr3	60830533	60830534	A	T	None	None
> chr3	60830762	60830763	G	T	None	None
fail
    cadd.t02...\c
ok
........
........
........
    gerp.t1...\c
ok
    gerp.t2...\c
1,7c1,7
< chr1	30859	30860	G	C	0.0	None
< chr1	69269	69270	A	G	-0.726000010967	5.41355e-97
< chr1	69510	69511	A	G	1.14999997616	5.41355e-97
< chr1	874815	874816	C	CT	0.0267999991775	None
< chr1	879675	879676	G	A	-3.1099998951	None
< chr1	935491	935492	G	T	0.533999979496	None
< chr1	1334051	1334057	CTAGAG	C	4.82000017166	1.51184e-59
..
> chr1	30859	30860	G	C	None	None
> chr1	69269	69270	A	G	None	5.41355e-97
> chr1	69510	69511	A	G	None	5.41355e-97
> chr1	874815	874816	C	CT	None	None
> chr1	879675	879676	G	A	None	None
> chr1	935491	935492	G	T	None	None
> chr1	1334051	1334057	CTAGAG	C	None	1.51184e-59
fail

it seems like it can access the cadd & gerp extra files, is this a problem with databases?

thanks for your great work!

mike d

**Comment by mjsduncan** [comment]
sorry for the inadvertent markdown formatting.

**Comment by arq5x** [comment]
Hmm. @brentp any ideas?

**Comment by brentp** [comment]
these are both passing for me. @mjsduncan how did you install? was it gemini update or gemini_install.py ? I'll try to recreate in an empty docker image.

**Comment by brentp** [comment]
I don't have the cadd dataset downloaded. I'll do so and look into this.

**Comment by mjsduncan** [comment]
installed with gemini update --dataonly --extra

**Comment by brentp** [comment]
hi @mjsduncan , these tests are passing for me. can you run:

```
ls -lh $(gemini_python ../gemini/anno_info.py)/whole_genome_SNVs.tsv.compressed.gz
ls -lh $(gemini_python ../gemini/anno_info.py)/hg19.gerp.bw

```
you should see a 35GB file for cadd (the first) and the gerp should be 7.1GB.

**Comment by mjsduncan** [comment]
thanks for looking in to this so quickly!  the files are both there.  is there a way to see what's wrong in the output associated with the failed tests?  or an md5 sum to check the files against?

**Comment by mjsduncan** [comment]
ie are there supposed to be numbers in the last to columns where it says "None"?

**Comment by brentp** [comment]
@mjsduncan it would be a good idea to have an md5 to check against. we don't have that currently.

yes, there should be numbers in the last columns. I suspect that somehow the gemini that is being run by your test command is not the same one that has the gerp and cadd data installed.

**Comment by mjsduncan** [comment]
i'm getting the same error with the update.  can you run md5sum on your versions of hg19.gerp.bw and whole_genome_SNVs.tsv.compressed.gz and post the results?

**Comment by mjsduncan** [comment]
thanks to brent for pushing a fix that takes into account an idiosyncrasy in the vcf file format output by complete genomics cgstools!
