### ISSUE TITLE
Standardize on either wget or curl as dependency

### ISSUE THREAD

**Issue by cbrueffer** [arq5x/gemini#458]
Currently, both wget and curl are necessary to install GEMINI; the install script requires both to be present. The annotation-creation scripts certainly use a mix of both tools.

I think standardizing on either wget or curl would be good; I don't think it matters much which one.

I could prepare a patch to make the switch, if we can decide on one or the other.

What do you think?

**Comment by arq5x** [comment]
This seems reasonable to me, but I recall that there were some issues with wget versus curl for certains types of downloads. @chapmanb - do you recall anything of the sort? I vaguely recall something about certificates, etc.

**Comment by chapmanb** [comment]
This would be great. This is a historical issue and probably my fault: I'm more familiar with wget so added those in. I know we've had issues with certificates in the past but think we should be able to solve these with either, so I don't have a strong preference on which we pick. Christian, thanks much for taking this on.

**Comment by cbrueffer** [comment]
Thanks for the feedback, see pull request #461.
