### ISSUE TITLE
Temp directory handling may have broken chunked import

### ISSUE THREAD

**Issue by schelhorn** [arq5x/gemini#459]
Using the latest development version of GEMINI and the temp directory parameter (to circumvent the NFS issue) I get an `sqlite3.OperationalError: unable to open database file` error. The reason for this error is a malformed path that GEMINI generates to import the vcf into database chunks (the original call to GEMINI originates from bcbio, but the bug is on GEMINI's side I believe):

This is what is called by gemini_load.py:

```shell
grabix grab /home/USERNAME/mbio_wes_2013-11/dataset1_comp1/gemini/SAMPLENAME-freebayes-decompose-vepeffects.vcf.gz 18871 20757 \
| gemini load_chunk -v - -t VEP  --skip-gerp-bp \
--passonly \
--tempdir /tmp/bcbiotx/0f20f1de-d49b-4349-ad69-e57cc6ad2b73/tmpPtNOOR \
-o 18871 \ 
/tmp/bcbiotx/0f20f1de-d49b-4349-ad69-e57cc6ad2b73/tmpPtNOOR//home/USERNAME/mbio_wes_2013-11/dataset1_comp1/gemini/SAMPLENAME-freebayes-decompose-vepeffects.vcf.chunk9.db
```

Note the last parameter of the command, which consists of two concatenated paths: the first one to the temporary directory and the second one to the chunk db file, _both including full paths_.

The error may originate from somewhere here:

[`chunk_dir`](https://github.com/arq5x/gemini/blob/master/gemini/gemini_load.py#L190) definition,
[`vcf`](https://github.com/arq5x/gemini/blob/master/gemini/gemini_load.py#L225) definition,
[command line formating](https://github.com/arq5x/gemini/blob/master/gemini/gemini_load.py#L348) that concatenates these strings into the actually called command.

If I have interpreted the code correctly, since `chunk_dir` is directly derived from the temporary directory and includes a full directory full path, the code would require a removal of the parent directories from the path of the `vcf` variable so that the concatenation of `chunk_dir` and `vcf` is a well formed path again.

**Comment by arq5x** [comment]
Thanks for reporting this, @schelhorn. At first glance, I think you are right that the `vcf` variable appears to retain the full path and should be stripped down to solely the filename. We will have a look into this very soon.

**Comment by chapmanb** [comment]
Sven-Eric -- thanks for catching this and apologies for the oversight. I pushed a fix now which does exactly what you describe, strips `vcf` down to just the filename before concatenating the temporary path. Thanks again for testing this and please let us know if you have any other issues.
