### ISSUE TITLE
GEMINI roh - database or disk is full - Error

### ISSUE THREAD

**Issue by nfarzaneh** [arq5x/gemini#473]
Hello,

I am trying to run gemini roh on a large database file (91 GB).  I have more than enough disk space available on my machine but I think that the error may have to do with the settings in sqllite (temp folders or space allocation).  However, you guys are the experts and was wondering if you have seen such an error before?  And of course, what I have to do to fix this.

========================
OS: LINUX OpenSUSE
GEMINI: 0.15.1 (but tried with 0.14.0 as well)

MY COMMAND:
gemini roh --min-snps 50 --min-gt-depth 20 --min-size 100000 --max-hets 1 --max-unknowns 2  *.db

OUTPUT:
LOG: Querying and ordering variants by chromosomal position.
SQLite error: database or disk is full
The query issued (select chrom, start, end,gts,gt_types,gt_phases,gt_depths,gt_ref_depths,gt_alt_depths,gt_quals,gt_copy_numbers,gt_phred_ll_homref,gt_phred_ll_het,gt_phred_ll_homalt FROM variants               WHERE type = 'snp'               AND   filter is NULL               AND   depth >= 20 ORDER BY chrom,  end) has a syntax error

========================

Thanks a lot,
Nima Farzaneh

**Comment by brentp** [comment]
Hi Nima, 
maybe you can try setting SQLITE_TMPDIR to somewhere with a lot of space
e.g. 
export SQLITE_TMPDIR=/path/to/huge/drive

**Comment by nfarzaneh** [comment]
Excellent!  Thanks a lot.  Working again.

Nima
