### ISSUE TITLE
galaxy integration

### ISSUE THREAD

**Issue by matthdsm** [arq5x/gemini#478]
Hi

Are there any plans to integrate a current version of Gemini into the Galaxy toolshed? I know version 0.10 is currently supported through a tool maintained by iuc, but seeing as the current version is 0.15 there are some compatibility issues. I'd like to import the results from bcbio (developed by @chapmanb ).

thanks
Matthias

**Comment by arq5x** [comment]
Hi Matthias,

@bgruening has been managing the Galaxy integration - Bjorn, can you provide guidance here?

**Comment by bgruening** [comment]
@matthdsm I would love to update these wrappers! Unfortunately, I have no time before GCC and BOSC (in 3 weeks). I will try to get to this one as soon as possible. Help is appreciated :)

**Comment by matthdsm** [comment]
Hi there

I forked the tools-uic repo to my personal github and edited the version numbers in the gemini tool/data manager. I don't expect any problems in running the tools with the new version, but do you guys have a way I can test everything before I submit a pool request? My knowledge about Galaxy is still pretty basic, so I don't really know where to start..

Matthias

**Comment by bgruening** [comment]
@matthdsm unfortunately, this is not enough. We need to update the tools as well. I guess there are a lot of new options.
If you just need a quick hack I can try to get the new version as package into the TS as a start. So you can install the binary and redirect your tools to use this new version. But this is really a hack and will destroy any reproducibility.

**Comment by matthdsm** [comment]
@bgruening Is there a way I can do any of that? As I already stated, my experience with Galaxy is still pretty basic, but I'd love to (try to) help to get this up-to date

**Comment by brentp** [comment]
I would also recommend to wait for the 0.16 release as there will be a lot of new changes. This should be out in under a week.

**Comment by bgruening** [comment]
@brentp thanks for the information!
@matthdsm what would help much is producing test data. I need one very small gemini test database for example. I think we can reuse one of @brentp test, but I haven't looked at this yet.

So my plan is to add test to the wrappers that are already there. If we have test we can upgrade tools and add new features.

**Comment by brentp** [comment]
@bgruening I'd be happy to help get test data. Do the datasets in [gemini/test](https://github.com/arq5x/gemini/tree/master/test) work for your purposes?

**Comment by bgruening** [comment]
@brentp probably. I just need to find a small subset out of this that are suitable for most of the tools. We would like to keep the test data as small as possible. For testing the wrappers we usually don't need to test every detail.

@matthdsm if you like to work on adding tests this would be awesome. To get started try [planemo](https://planemo.readthedocs.org/en/latest/). This will help you test tools easily.

**Comment by matthdsm** [comment]
@bgruening I'll start with looking into Planemo, but I think I'll wait to do anything up untill the release of Gemini 0.16, so I can start with an up to date version.
@brentp Thanks for the heads up!

**Comment by matthdsm** [comment]
Hi,

I updated the wrappers and started adding some tests. However, the test data found in this repository totals to about 900 mb when all the databases needed are created. Any ideas on how I can integrate this test data, without getting an angry mail from the github admins?

Matthias

**Comment by bgruening** [comment]
@matthdsm 900MB? This is too much ;) You can share it somehow with me (google drive?) but we really need to trim it down. I had hoped that one sqlite file and one vcf is enough for most of the things.

**Comment by matthdsm** [comment]
I had a slight feeling 900mb of tests would be a bit overkill. I suppose the data files kan be trimmed, but I don't think we'll be able to cut much, since there are several vcf's with different annotations and a lot of functions that need testing.
perhaps @arq5x  can sift through the data and select the bare essentials?
All required databases can be created using the "data-setup.sh" script in the test-data folder.

**Comment by bgruening** [comment]
@matthdsm yes maybe @arq5x or  @brentp can point us to one/two databases with most of the informations. We can also use other comparison techniques like `compare="contains"` in the Galaxy tests. Happy to review your changes without the data to catch these stuff.

**Comment by matthdsm** [comment]
@bgruening I pushed the changes I made to the tool wrappers to my fork of the iuc-tools in matthdsm/tools-iuc. Perhaps you can do a quick review of these changes. I am a bit a loss on how I can write tests for these tools. Are there any functions that are able to compare databases?

**Comment by bgruening** [comment]
@matthdsm This is definitely a good start but we really need to add tests like this here: https://github.com/bgruening/galaxytools/blob/master/tools/diamond/diamond.xml#L135

Could you create a simple branch with only changes to your XML files, these are looking good. I can work on this branch after GCC ... or simply send me your XML files and I will work on this ...

**Comment by matthdsm** [comment]
I branched my changes as "gemini_xml_updates". Good luck @ GCC. I am not able to attend, but I'll try to follow as much as I can. Any idea if I'll be able to stream your talk about galaxy in docker? I'm very interested, as we're trying to do the same here, based on your dockerfile.

**Comment by bgruening** [comment]
@matthdsm I will have a look, thanks! Streaming is not planned, afaik, but all talks are recoded and will be available after GCC. Let me know if you need any information or help.
See also: https://github.com/bgruening/docker-galaxy-stable/issues/67

**Comment by bgruening** [comment]
@matthdsm We have started our work to update the wrappers to the latest 0.18. version. I'm currently trying to fix the tool dependencies and a few new tools are missing. But we are in a pretty good shape. If you want to help ... please feel welcome to join!

@brentp any new release planned in the near future on which we should block?
Thanks and nice holidays!

**Comment by chapmanb** [comment]
Björn;
Apologies in advance as I probably broke some of the gemini galaxy installation with the new release. 0.18 and above are conda-only installs for the dependencies which should make it a lot cleaner going forward but will probably have some rough edges in the transition. Please let me know if I can help at all with any problems.

**Comment by brentp** [comment]
We will release 0.18.1 with some small fixes, but this shouldn't change much. We can try to get this out early next week.

**Comment by bgruening** [comment]
@chapmanb indeed I have some reproducible problems in our Galaxy Docker container.

Running `export HOME=$INSTALL_DIR && python gemini_install.py $INSTALL_DIR $INSTALL_DIR --nodata --gemini-version 0.18.0` will produce this error:

```
....
Python 2.7.11 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
Installing base gemini package...
Error: could not parse '�����m����m�t^�r/
                                           ����X����Sq�C!�l�K��[=r�E!���2$��'Vd_�ɺh�ē\.���3�6��zA�̗�o��Ml2���#������3�e�lNH�
                                                                                                                                        �S������T(�JY>	��#�z�"y� ��Ў�yҭ`��<�V���86�Mu���ǘ"��F�Ow���l�T���	z,e/k=�w]��R��Ѹ�Q/:ww� ��~�g'��&
                                                     
```
Downloading the requirements_conda.txt manually and rerunning it with:
```
/galaxy-central/foo/anaconda/bin/conda install --yes -c bcbio -c bioconda --file requirements_conda.txt
```
generates this error (even with unset PYTHONPATH):
```
Hint: the following packages conflict with each other:
  - bx-python 0.7.2 np18py27_1
  - cyvcf2 >=0.2.3
```

-----
Removing the strict version:
```
export HOME=$INSTALL_DIR && python gemini_install.py $INSTALL_DIR $INSTALL_DIR --nodata
```
seems to install the entire anaconda suite with pandas, zeromq, pyqt and so on and results in this error:
```
subprocess.CalledProcessError: Command '['/galaxy-central/foo/anaconda/bin/gemini', 'update', '--dataonly', '--annotationdir', '/galaxy-central/foo/gemini_data', '--nodata', '--tooldir', '/galaxy-central/foo']' returned non-zero exit status 2
```
You fixed this in master afaik, but it would be nice to use the `--gemini-version` parameter for Galaxy.

**Comment by chapmanb** [comment]
Björn;
Thanks so much for looking at this and sorry about all the issues. The conda requirements file for 0.18.0 has gotten into a bit of a mess with the transition from bcbio packages to bioconda. Everything is now cleanly in bioconda and I updated the requirements for 0.18.0 to match that. Going forward, we should have compatible archived versions so it'll work more cleanly without this hacking needed. If you grab the latest installer and run your first command it should now work. Hope this gets things going for you.

**Comment by bgruening** [comment]
Brad;
This works! Thanks.
Now I get this strange backtrace, only for `gemini load`:
```
Fatal error: Exit code 1 ()
Traceback (most recent call last):
  File "/home/bag/temp/gemini/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/home/bag/temp/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1177, in main
    args.func(parser, args)
  File "/home/bag/temp/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 197, in load_fn
    import gemini_load
  File "/home/bag/temp/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 11, in <module>
    from cluster_helper.cluster import cluster_view
  File "/home/bag/temp/gemini/anaconda/lib/python2.7/site-packages/cluster_helper/cluster.py", line 22, in <module>
    from ipyparallel import Client
  File "/home/bag/temp/gemini/anaconda/lib/python2.7/site-packages/ipyparallel/__init__.py", line 14, in <module>
    from ipykernel.pickleutil import Reference, can_map
  File "/home/bag/temp/gemini/anaconda/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/bag/temp/gemini/anaconda/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named paths
````

One other question do I need to have the annotation databases for running the tests? I would like to test the wrappers but usually we don't have the big databases around.

**Comment by chapmanb** [comment]
Björn;
Sorry about the issue, I missed that one. It looks like the requirements locked us to an old version of IPython for some reason. I bumped that up to a recent one so if you re-run (or do `/home/bag/temp/gemini/anaconda/bin/conda install ipython` on your broken version) it should now work cleanly.

I do think you need the databases for tests since it does loading, but @brentp would know if there's a subset you can run with a more minimal install. Thanks again for testing this and getting it up to date.

**Comment by bgruening** [comment]
@chapmanb thanks a lot! Everything is working as far as I can see. I have for most of the tools (those without --annotation-dir) unit-tests working and everything is on the Test Tool Shed.
I will let you know when we move it to the main Tool Shed.

Thanks and a happy new year!

**Comment by matthdsm** [comment]
Hi all, 

we deployed the gemini tool in our local galaxy and everything works smoothly! We hope the tool will be going to the main toolshed soon.

However, would it be possible to add some more functionality? We'd like a wrapper for the "amend" option, to add a PED file to an existing database.
Also, we would like to customize the GALAXY_SLOTS variable, so the load process can run on more than one core.

Thanks for the help and all the work you're putting into it!

Matthias

**Comment by bgruening** [comment]
@matthdsm updated everything a minute ago. Let me know if you find any problems, especially with installing the datasets via the datamanager and the gemini installation.

Thanks for testing!

**Comment by matthdsm** [comment]
@bgruening 
Thanks! I'll install it right away!

**Comment by bgruening** [comment]
Small update, everything is now in the ToolShed and part of the Freiburger Galaxy Server. It will soon be available at usegalaxy.org as well.
