### ISSUE TITLE
aa_change in not exonic and not coding variants?

### ISSUE THREAD

**Issue by mpschr** [arq5x/gemini#491]
Hi

First off, congrats to this accomplished tool!

I have found a couple of variants in a GEMINI sample database which are annotated with a AA_change, but are not exonic neither coding. I suspect there is a bug somewhere. Are aa_change, is_exonic and is_coding computed from different information?

```
|----------------+---------+---------+-------+-----+-----+-----------+-----------+------------|
|  chrom         | start   | end     | gene  | ref | alt | aa_change | is_coding | is_exonic  |
|----------------+---------+---------+-------+-----+-----+-----------+-----------+------------|
|  chrGL000237.1 | 898     | 899     | BAGE5 | T   | G   | *40C      | 0         | 0          |
|  chr12         | 6094728 | 6094730 | VWF   | CT  | C   | K2300     | 0         | 0          |
|----------------+---------+---------+-------+-----+-----+-----------+-----------+------------|
```

**Comment by arq5x** [comment]
Hmm.  Would you be able to share the lines from the original VCF file that correspond to these rows?

**Comment by mpschr** [comment]
Hm, I've since deleted this file, but it occurs in almost any sample for a couple of entries. Here is another example.

gemini call: 
```gemini query --header -q "select chrom,start,end,gene,ref,alt,aa_change,is_coding,is_exonic from variants where not is_coding and aa_change is not NULL" batch02-ensemble.db | tsvlook```

output: 
```
|--------+-----------+-----------+----------+-----+-----+-----------+-----------+------------|
|  chrom | start     | end       | gene     | ref | alt | aa_change | is_coding | is_exonic  |
|--------+-----------+-----------+----------+-----+-----+-----------+-----------+------------|
|  chr6  | 34950530  | 34950531  | ANKS1A   | G   | A   | T245      | 0         | 0          |
|  chr6  | 138794443 | 138794444 | NHSL1    | T   | G   | K161T     | 0         | 0          |

```

The VCF entries look as follows:
```
6	34950531	.	G	A	.	PASS	EFF=SPLICE_SITE_REGION+SYNONYMOUS_CODING(LOW|SILENT|acG/acA|T245|1134|ANKS1A|protein_coding|CODING|ENST00000360359|5|A),SPLICE_SITE_REGION+SYNONYMOUS_CODING(LOW|SILENT|acG/acA|T245|320|ANKS1A|protein_coding|CODING|ENST00000535627|5|A);EPR=pass;SOMATIC;VT=SNP	GT:AD:BQ:DP:FREQ:SS	0/1:38,34:36:72:0.472:2
6	138794444	.	T	G	.	PASS	EFF=NON_SYNONYMOUS_CODING+SPLICE_SITE_REGION(MODERATE|MISSENSE|aAg/aCg|K161T|1610|NHSL1|protein_coding|CODING|ENST00000427025|3|G),NON_SYNONYMOUS_CODING+SPLICE_SITE_REGION(MODERATE|MISSENSE|aAg/aCg|K113T|1606|NHSL1|protein_coding|CODING|ENST00000343505|3|G),NON_SYNONYMOUS_CODING+SPLICE_SITE_REGION(MODERATE|MISSENSE|aAg/aCg|K99T|220|NHSL1|protein_coding|CODING|ENST00000342260|3|G|WARNING_TRANSCRIPT_NO_STOP_CODON),NON_SYNONYMOUS_CODING+SPLICE_SITE_REGION(MODERATE|MISSENSE|aAg/aCg|K125T|167|NHSL1|protein_coding|CODING|ENST00000491526|3|G|WARNING_TRANSCRIPT_NO_START_CODON),NON_SYNONYMOUS_CODING+SPLICE_SITE_REGION(MODERATE|MISSENSE|aAg/aCg|K114T|136|NHSL1|protein_coding|CODING|ENST00000533765|3|G|WARNING_TRANSCRIPT_INCOMPLETE),SPLICE_SITE_REGION+EXON(LOW|||||NHSL1|retained_intron|CODING|ENST00000426841|3|G),SPLICE_SITE_REGION+EXON(LOW|||||NHSL1|processed_transcript|CODING|ENST00000479393|3|G);EPR=pass;SOMATIC;VT=SNP	GT:AD:BQ:DP:FREQ:SS	0/1:8,3:37:11:0.273:2
```

If it helps, the gemini database has been produces with the `bcbio-nexgen` pipeline, found in @chapmanb repository. But I have the feeling that this is more of a GEMINI problem, as even the metadata in the VCF states for both variants that they are protein_coding, of which the `is_coding` column in the Gemini db is the equivalent, I reckon.

It could be as simple as a gene feature versioning problem, depending on who puts the AA change info into the DB...

**Comment by mpschr** [comment]
@arq5x did you have a chance to have a look at it? Tell me if you need more detail.

**Comment by arq5x** [comment]
We haven't had a chance yet but it is high on our list. Sorry for the delay.

**Comment by brentp** [comment]
Hi, this is because gemini currently doesn't handle snpeff effects like: "SPLICE_SITE_REGION+SYNONYMOUS_CODING"
where 2 effects are joined by "+".

This is a simple fix. I'll open a PR shortly.

**Comment by mpschr** [comment]
Great! This should be in the next release then?

**Comment by arq5x** [comment]
Yep, it will be in the next release.
