### ISSUE TITLE
check pragmas to improve indexing speed

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#495]
e.g.
http://stackoverflow.com/questions/28647616/parallel-index-creation-in-sqlite3

since indexing large databases is taking much of the user-time after parallelization.

**Comment by arq5x** [comment]
Interesting - any evidence that this improves performance? These are areas where a more scalable DB backend would help a ton, but moving to PostgreSQL and the like limits usability for many. 

In many ways, I would almost rather avoid a database entirely, but column indexing is what makes filtering, prioritization, and general querying so fast.

Perhaps something like http://cassandra.apache.org/ would be a better long term alternative?

**Comment by arq5x** [comment]
Another thought is that with vcfanno, @ryanlayer's GQT, @lh3's BGT, and bcftools, one could conceive of a GEMINI-like framework that does not require a formal database.  The front end would just be sugar to convert simple queries into the appropriate filters using the indices from the tools above. Worth thinking about, as this is going to become an ever larger problem.

**Comment by brentp** [comment]
wasn't able to improve indexing speed with the linked pragma. will close for now and we can reopen if we decide to use an alternate backend.
