### ISSUE TITLE
Improving GEMINI on multi-user cluster

### ISSUE THREAD

**Issue by GabrielHoffman** [arq5x/gemini#496]
I have two suggestions that could improve usability on multi-user compute clusters

1) GEMINI creates a local installation of samtools, bedtools, bcftools, etc.  But these programs have changed a lot in the last few years, and GEMINI seems to use older versions.  This becomes an issue when my PATH points to GEMINI's version of these programs instead of a more recent version. 

It would be useful if GEMINI could use its own version of these programs, while not making them visible to the users PATH by putting them in a different directory than the gemini program.

2) When GEMINI loads a VCF, it writes a lot of temporary files to the /tmp directory.  GEMINI deletes these files at the end, but if the user terminates the program early the files are not removed.  This has been an issues on our multi-user machines, where one user starts a large GEMINI job, kills it, and writes a huge amount of data to /tmp with out knowing it.  This has caused /tmp to reach capacity, so that all users of that machine get unexplained errors for every program that needs space in /tmp.  It has taken a few hours to diagnose why every user has been having issues with one machine.

Instead, GEMINI should write these files to a local temporary directory specified by the user.  That way a single user won't be able to disrupt all the other users on our machine.

Thanks!
- Gabriel

**Comment by arq5x** [comment]
Hi Gabriel,

These are great suggestions. The first suggestion should easily be doable. The second suggestion, is, as far as I know, already implemented via the ``--tempdir`` option for the ``load`` tool.  Have you tried that option yet?

**Comment by GabrielHoffman** [comment]
Thanks for the response!  I like the --tempdir option, but the user has 
to know about this option to use it.  We were having an issue where an 
inexperienced user caused some issues on the head node of our cluster 
because they were filling up the global /tmp directory without knowing.

This is clearly a user error, rather than an issue with GEMINI, but I 
figured I would bring it up in case it was a common problem for other people

But the issue with multiple versions of samtools, etc is causing us some 
real problems.

Cheers,
- Gabriel

**Comment by arq5x** [comment]
Absolutely, thanks.  We will discuss options for quarantining the GEMINI versions of the tools. In fact, we need to revisit whether or not this is indeed necessary.

**Comment by chapmanb** [comment]
Aaron and Gabriel;
What do you think about only trying to install grabix and leaving the user to install samtools, tabix and bedtools? Those dependencies in GEMINI are a bit out of date as we're trying to install them with a custom set of scripts that don't get used outside of this installer. In other tools, I use Homebrew/Linuxbrew but introducing a Ruby dependency for GEMINI installation seemed like overkill. Thanks for the suggestions.

**Comment by arq5x** [comment]
I think that makes a lot of sense. I would like to first revisit for what GEMINI tools samtools, bedtools and tabix are required. As far as I recall, bedtools is only needed for the `windower` tool. I can't actually recall any place where samtools or tabix are required, but my memory is nil.

**Comment by arq5x** [comment]
So I looked into it.

1. bedtools is required solely by the ``windower`` tool.
2. samtools is not used at all as far as I can tell by grepping the code.
3. tabix is used solely by the ``annotate`` tool.

Perhaps we should assume these dependencies are installed, and for windower and tabix, check to make sure they are on PATH and if not, alert the user to install them first and place them on the PATH.

Thoughts?

**Comment by chapmanb** [comment]
Sounds great to me. I can work on this but it might not be until early next week since I'm at BOSC the next couple of days. Thanks again for all the ideas and discussion.

**Comment by arq5x** [comment]
No sweat - I am jealous.

**Comment by chapmanb** [comment]
Gabriel and Aaron;
I checked in changes so that GEMINI will only try to install grabix and require users to separately install tabix and bedtools if they're using the annotate or windowers tools. I also added error messages there to make it clear if those tools are missing. Hopefully this avoids any issues with gemini tool installation versions. Thanks again for the helpful feedback.

**Comment by arq5x** [comment]
Fantastic, thanks Brad!
