### ISSUE TITLE
Broken Cython dependency in release 0.16.1 automatic installation

### ISSUE THREAD

**Issue by ddkinnamon** [arq5x/gemini#501]
Hi,

The automatic installation script using flag `--gemini-version 0.16.1` aborts with the following error message:

    Downloading/unpacking bcolz>=0.8.1 (from -r https://raw.githubusercontent.com/arq5x/gemini/master/versioning/0.16.1/requirements_pip.txt (line 18))
    Running setup.py (path:/tmp/pbstmp.4246947/pip_build_user/bcolz/setup.py) egg_info for package bcolz
    .. ERROR:: At least Cython 0.22 is needed so as to generate extensions!
    Complete output from command python setup.py egg_info:
    .. ERROR:: At least Cython 0.22 is needed so as to generate extensions!

Upon further investigation, it appears that the problem arises because Cython 0.20.1-py27_0 is installed based on the `requirements_conda.txt` file for release 0.16.1.

Thanks,
Dan

**Comment by arq5x** [comment]
Thanks for reporting this, Dan. We will look into this once we get a reprieve from the current load.

**Comment by arq5x** [comment]
Thanks much, I just bumped the requirement to 0.22.

**Comment by ddkinnamon** [comment]
You might need to reopen...

```
Error: No packages found in current linux-64 channels matching: cython 0.22.0 py27_0

You can search for this package on Binstar with

    binstar search -t conda cython 0.22.0 py27_0
```
