### ISSUE TITLE
shortcut for filtering by AF in 1kg, ExAC, for all populations for mendelian diseases

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#520]
@jxchong showed an extensive filter for filtering of variants for (rare) mendelian diseases:

```
(aaf_esp_ea <= 0.005 or aaf_esp_ea is NULL) AND \
(aaf_esp_aa <= 0.005 or aaf_esp_aa is NULL) AND \
(aaf_1kg_amr <= 0.005 or aaf_1kg_amr is NULL) AND \
(aaf_1kg_eas <= 0.005 or aaf_1kg_eas is NULL) AND \
(aaf_1kg_sas <= 0.005 or aaf_1kg_sas is NULL) AND \
(aaf_1kg_afr <= 0.005 or aaf_1kg_afr is NULL) AND \
(aaf_1kg_eur <= 0.005 or aaf_1kg_eur is NULL) AND \
(aaf_adj_exac_afr <= 0.005 or aaf_adj_exac_afr is NULL) AND \
(aaf_adj_exac_amr <= 0.005 or aaf_adj_exac_amr is NULL) AND \
(aaf_adj_exac_eas <= 0.005 or aaf_adj_exac_eas is NULL) AND \
(aaf_adj_exac_fin <= 0.005 or aaf_adj_exac_fin is NULL) AND \
(aaf_adj_exac_nfe <= 0.005 or aaf_adj_exac_nfe is NULL) AND \
(aaf_adj_exac_sas <= 0.005 or aaf_adj_exac_sas is NULL)
```
we could add this as a BOOL column to the db `mendelian_af_filter` or we could have a flag to the tools to automatically inject this into the query.

**Comment by arq5x** [comment]
I think it should be a flag that accepts a max AF

**Comment by brentp** [comment]
would be easier to implement as a column somehow. It could store the max af from all of those columns.

**Comment by arq5x** [comment]
A column seems fine with me - only corner case is the FIN example that @jxchong mentioned.

**Comment by brentp** [comment]
currently, missing values are saved as NULL so if we use aaf < 0.001, it doesnt get the NULLs.

We need to document this since those are very important.

For this aggregate field, if all of the fields that we are checking are NULL, we could set to 0.

**Comment by brentp** [comment]
correction: for NULL, we set to -1.
