### ISSUE TITLE
new tool: gemini gene_wise

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#529]
the built in tools are convenient because they automatically group by gene, but they don't allow specifying a `--gt-filter`.
A new tool, `gemini gene_wise` will have `--min-kindreds` arguments that applies to the gene and still allows specifying a custom `--gt-filter`.

It will have similar arguments to the built in tools.

cc @arq5x @jxchong

**Comment by brentp** [comment]
we can mostly use the existing machinery for inheritance models for this. The problem is that for inheritance models, we create 1 filter per family. That's what allows us to determine the number of kindreds. 

With this single --gt-filter, we'll have to apply it across all samples (not 1 family at a time as above) and then make sure the number of families meets the requested kindreds.

**Comment by brentp** [comment]
so --min-kindreds doesn't actually make sense for this tool is I originally proposed it.

We could have it be something like:

```
gemini genewise --min-filters 2 --gt-filter $filter1 --gt-filter $filter2 --gt-filter $filter3 some.db
```

to require that (any) 2 out of the 3 filters are met at a per-gene level. The user could split by family and then --min-filters would equate to --min-kindreds.

For the simple-case, --min-filters will default to 1 so that they can specify a multi-family query in a single --gt-filter and it will explicitly impose a min-kindreds. 

@arq5x does that sound reasonable?

**Comment by brentp** [comment]
I have this working. An example invocation and output looks like:

```
gemini genewise --gt-filter "gt_types.1094PC0005 == HET" --gt-filter "gt_types.1094PC0009 == HET" test/test.query.db --min-filters 2 | cols
chrom  start   end     gene     impact          passed_filters
chr1   898602  898603  KLHL17   non_syn_coding  1,2
chr1   900559  900560  KLHL17   non_syn_coding  1,2
chr1   901918  901919  PLEKHN1  non_syn_coding  1,2
chr1   909237  909238  PLEKHN1  non_syn_coding  1,2
```

if I change that to --min-filters 1, then it gets more:
```
chrom	start	end	gene	impact	passed_filters
chr1	949654	949655	ISG15	non_syn_coding	1
chr1	898602	898603	KLHL17	non_syn_coding	1,2
chr1	900559	900560	KLHL17	non_syn_coding	1,2
chr1	69760	69761	OR4F5	non_syn_coding	2
chr1	901918	901919	PLEKHN1	non_syn_coding	1,2
chr1	909237	909238	PLEKHN1	non_syn_coding	1,2
chr1	1226756	1226757	SCNN1D	non_syn_coding	1
chr1	1226888	1226889	SCNN1D	non_syn_coding	1
```

There is also a --min-variants, option, so without it:
```
$ gemini genewise --gt-filter "gt_types.1094PC0005 == HET" test/test.query.db                                                     
chrom	start	end	gene	impact	passed_filters
chr1	949654	949655	ISG15	non_syn_coding	1
chr1	900559	900560	KLHL17	non_syn_coding	1
chr1	909237	909238	PLEKHN1	non_syn_coding	1
chr1	1226756	1226757	SCNN1D	non_syn_coding	1
chr1	1226888	1226889	SCNN1D	non_syn_coding	1
```
and with it:
```
$ gemini genewise --gt-filter "gt_types.1094PC0005 == HET" test/test.query.db --min-variants 2
chrom	start	end	gene	impact	passed_filters
chr1	1226756	1226757	SCNN1D	non_syn_coding	1
chr1	1226888	1226889	SCNN1D	non_syn_coding	1
```

combining multipe gt-filters with --min-filters and --min-variants could provide a lot of flexiblity.
currently --min-variants is per gene, but it could be per-gene, per-filter.

**Comment by brentp** [comment]
As an example, given this cohort from @jxcong: 
![genewise](https://cloud.githubusercontent.com/assets/1739/9393781/5b157b9a-4741-11e5-9350-52235e845af2.png)

We can do the entire analysis (note the use of the new max_aaf_filter) with this command:

```
gemini genewise disease_x.VT.db \
    --min-filters 3 \
    --gt-filter "gt_types.37721 == HET and gt_types.42224 == HOM_REF and gt_types.37722 == HOM_REF" \
    --gt-filter "gt_types.37724 == HET" \
    --gt-filter "gt_types.44872 == HET" \
    --columns "chrom,start,end,gene,impact,impact_severity" \
    --filter "max_aaf_all < 0.005"
```
which gives 4 candidates:
```
chrom	start	end	gene	impact	impact_severity	passed_filters
chr5	60839982	60839983	ZSWIM6	non_syn_coding	MED	1,2,3
chr6	32548031	32548032	HLA-DRB1	non_syn_coding	MED	1,2,3
chr6	32552059	32552060	HLA-DRB1	frame_shift	HIGH	1,2,3
chr6	32552131	32552132	HLA-DRB1	inframe_codon_gain	MED	1,2,3
chr6	32552136	32552137	HLA-DRB1	non_syn_coding	MED	1,2,3
```
In this example, all samples have the exact same variant in the known gene (ZSWIM6), but it could find them in different locations in the same gene as it did for the HLA gene.

**Comment by brentp** [comment]
I updated so that it outputs which variants passed which filters both variant-wise and gene-wise:
```
chrom  start     end       gene      impact              impact_severity  variant_passed_filters  passed_filters
chr5   60839982  60839983  ZSWIM6    non_syn_coding      MED              1,2,3                   1,2,3
chr6   32548031  32548032  HLA-DRB1  non_syn_coding      MED              1                       1,2,3
chr6   32552059  32552060  HLA-DRB1  frame_shift         HIGH             2                       1,2,3
chr6   32552131  32552132  HLA-DRB1  inframe_codon_gain  MED              3                       1,2,3
chr6   32552136  32552137  HLA-DRB1  non_syn_coding      MED              3                       1,2,3
```

**Comment by arq5x** [comment]
This is cool.  My only concern is how it would in the case of a single wildcard `--gt-filter` that enforces an autosomal dominant model across all (possibly many) families, yet the researcher want to just find genes that have multiple families affected, but possibly at different sites. Essentially, behaving like the auto_dom tool with `min-kindreds`, yet one has fine control over the genotype requirements.

    gemini genewise many_recessive_families.db \
    --min-filters 3 \
    --gt-filter "(gt_types).(phenotype==2).(==HET).(all) and (gt_types).(phenotype==1).(==HOM_REF).(all)" \
    --columns "chrom,start,end,gene,impact,impact_severity" \
    --filter "max_aaf_all < 0.005"

**Comment by brentp** [comment]
this in in master

**Comment by jxchong** [comment]
So I *finally* got a little time to think about how I'd want to use this tool beyond being able to do a combined dominant/de novo analysis. 

Is it possible to extend it to be able to simultaneously filter for families with compound het and/or recessive mutations in the same gene? I think this is the logical other way to use it.

**Comment by jxchong** [comment]
Hm, how would one combine a gt_type set of filters with also filtering for depth and GQ.

normally you'd do 
`--gt-filter "(gt_depths).(*).(>=6).(all) AND (gt_quals).(*).(>=20).(all)"`

but you would want that to be applied always and not be subject to the `--min-filters` criteria (otherwise if you said `--min-filters 2` and you were analyzing 2 different trios, you could end up getting variants from the two trios that fail DP/GQ cutoffs when you really want variants from either trio that pass the DP/GQ cutoff?

**Comment by brentp** [comment]
@jxchong this is a good point. We talked about this and figured that maybe we could have `--gt-filter-required` or something that applied to all and wasn't a part of the `--min-filters` groups.

It might be possible to have a place-holder for the current family, e.g:
```
--gt-filter "(gt_depths).(*).(>=6).(family_id==$family) AND (gt_quals).(*).(>=20).(family_id==$family)"
```

and we'd inject the family_id into $family for each family.

**Comment by jxchong** [comment]
Sorry for a very delayed response. I like `--gt-filter-required` (it's clear what it is doing from the name)
