### ISSUE TITLE
Add ExAC num_het, num_hom_alt, etc.

### ISSUE THREAD

**Issue by arq5x** [arq5x/gemini#531]
Useful for triaging variants under various inheritance models.  

Should add this in conjunction with the new "max_exac_aaf", "max_esp_aaf", etc. 

cc
@jxchong @brentp

**Comment by arq5x** [comment]
@brentp - can you add this to the forthcoming release as well? or would you rather wait until the one after?

**Comment by brentp** [comment]
I was hoping to wait til the vcfanno release, otherwise, it's essentially doing it 2x.

**Comment by arq5x** [comment]
Yeah, great point. Let's wait for the vcfanno release.

**Comment by arq5x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bmHhyLG0&#x2F;19-add-exac-num-het-num-hom-alt-etc"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add ExAC num_het, num_hom_alt, etc.</a>

**Comment by brentp** [comment]
this is in master.
