### ISSUE TITLE
gemini load changes

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#536]
"--skip-info-string" and "--no-bcolz" should be the default for gemini load. These will be rarely used (I think bcolz is mostly useful for whole genome) and they incur some cost at loading.

Actually, with the new loader, I think we could remove the info field storage altogether.

**Comment by arq5x** [comment]
Yes, since every field in the INFO string will have the capacity to be stored as a distinct column in the resulting DB, that could replace INFO storage. @dgaston - how do you feel about this?

**Comment by brentp** [comment]
I guess just switching to --keep-info-field could be preferable. then they'd have the info even if it wasn't in the vcfanno config.

**Comment by brentp** [comment]
this is now in master
