### ISSUE TITLE
test-comphet.py assert len error

### ISSUE THREAD

**Issue by MinocheAE** [arq5x/gemini#548]
Hi, 

I have gemini version 0.17.0 installed.
running master-test.sh gives me this error:

Traceback (most recent call last):
  File "test-comphet.py", line 63, in <module>
    assert len(ret.strip().split("\n")) == 2 + 1
AssertionError

Does this need a fix?

This is how I installed gemini:
python gemini_install.py /path/gemini /path/gemini --nosudo
gemini update
gemini update --dataonly --extra cadd_score
gemini update --dataonly --extra gerp_bp

I use Python 2.7.3

Thanks

**Comment by brentp** [comment]
Hi, this was a problem wit the test. It was fixed along with this commit (https://github.com/arq5x/gemini/pull/547/files), but the output of the tool itself will note change.
