### ISSUE TITLE
more resolution in comp_het priority score

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#549]
https://groups.google.com/forum/#!topic/gemini-variation/idC5qyM9ei8

**Comment by arq5x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;4IAvSWrp&#x2F;18-more-resolution-in-comp-het-priority-score"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> more resolution in comp_het priority score</a>

**Comment by brentp** [comment]
We should do this for 0.18

"However, if I have to drop down to priority 2 to see the single proband results, this existing issue acquires greater importance to me as an analyst: #549

Perhaps making single proband results priority 2 and dropping the others down to priority 3?"

**Comment by brentp** [comment]
this is implemented in the inheritance module. I'll add a couple of tests and document.
