### ISSUE TITLE
Unknown PLs should not meet max-pl

### ISSUE THREAD

**Issue by arq5x** [arq5x/gemini#552]

**Comment by arq5x** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;08dRbGSK&#x2F;20-unknown-pls-should-not-meet-max-pl"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Unknown PLs should not meet max-pl</a>

**Comment by brentp** [comment]
this is fixed in cyvcf2: https://github.com/brentp/cyvcf2/commit/5ac3a466348a5a8f213e45807d98ae1a91ca8498

will need to update the dep to cyvcf2==0.1.9
