### ISSUE TITLE
Genotype wildcards

### ISSUE THREAD

**Issue by djm-h** [arq5x/gemini#561]
Is there a way to use wildcards in Gemini to select large cohorts, but not all samples? For instance, if I have a large joint-haplotype-called VCF containing 3 cohorts of 40 samples, is there a way to:

gemini query -q "select chrom, start, ref, alt, gene, (gts).(cohort#1_sample*) from variants"

to get just the genotypes of the samples from cohort#1.  Or perhaps even:

--gt-filter "(gt_types).(cohort#2_sample* == HOM_REF and cohort#3_sample* == HOM_REF)

to look for variants that are unique to cohort#1.

Or is this a problem that should be tackled by manipulating the VCF with GATK prior to loading into Gemini?

Dave

**Comment by brentp** [comment]
you can use any column from your ped file in the selector columns, e.g. 

.(mygroup=="A").(HOM_REF)
