### ISSUE TITLE
No strand_bias

### ISSUE THREAD

**Issue by muraveill** [arq5x/gemini#563]
I ran Gemini 0.17.2 on a VCF containing the following header:

    ##INFO=<ID=FS,Number=1,Type=Float,Description="Phred-scaled p-value using Fisher's exact test to detect strand bias">

and non-null `FS` entries, but all `strand_bias` values are NULL in the db.
The "Gemini database schema" doc page does not inform which VCF field is used (it could, if it is always called 'FS' - I don't know).

**Comment by brentp** [comment]
The vcf spec https://samtools.github.io/hts-specs/VCFv4.2.pdf says it should be "SB" which is what gemini uses.  I'll push an update to the docs for this.

**Comment by muraveill** [comment]
SB seems to be an old thing and people prefer the FS that GATK produces. Could we have the FS field in the db as well ?

https://www.biostars.org/p/58173/
It's you :)
