### ISSUE TITLE
HGVSc, HGVSp imports blank?

### ISSUE THREAD

**Issue by jxchong** [arq5x/gemini#575]
I'm trying to update our Gemini pipeline to 0.17.2 and started trying to pull in HGVS. I'm not sure if I did something wrong because we haven't tried to import these columns before, or if this is a bug.

I annotated my vcf with VEP --hgvs without problems. The resulting vcf has HGVSc and HGVSp included in the header and there are values for each of the variants in the vcf for these fields.

`##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence type as predicted by VEP. Format: Consequence|Codons|Amino_acids|Gene|SYMBOL|Feature|EXON|PolyPhen|SIFT|Protein_position|BIOTYPE|CANONICAL|CCDS|HGVSc|HGVSp">`
    
However, I get only the header returned when I try to use Gemini to pull variants where HGVSc is not null, e.g.

> $ gemini query -q "select * from variants where vep_HGVSc is not NULL" mydatabase.db --header

> chrom	start	end	vcf_id	variant_id	anno_id	ref	alt	qual	filter	type	sub_type	call_rate	in_dbsnp	rs_ids	sv_cipos_start_left	sv_cipos_end_left	sv_cipos_start_right	sv_cipos_end_right	sv_length	sv_is_precise	sv_tool	sv_evidence_type	sv_event_id	sv_mate_id	sv_strand	in_omim	clinvar_sig	clinvar_disease_name	clinvar_dbsource	clinvar_dbsource_id	clinvar_origin	clinvar_dsdb	clinvar_dsdbid	clinvar_disease_acc	clinvar_in_locus_spec_db	clinvar_on_diag_assay	clinvar_causal_allele	pfam_domain	cyto_band	rmsk	in_cpg_island	in_segdup	is_conserved	gerp_bp_score	gerp_element_pval	num_hom_ref	num_het	num_hom_alt	num_unknown	aaf	hwe	inbreeding_coeff	pi	recomb_rate	gene	transcript	is_exonic	is_coding	is_lof	exon	codon_change	aa_change	aa_length	biotype	impact	impact_so	impact_severity	polyphen_pred	polyphen_score	sift_pred	sift_score	anc_allele	rms_bq	cigar	depth	strand_bias	rms_map_qual	in_hom_run	num_mapq_zero	num_alleles	num_reads_w_dels	haplotype_score	qual_depth	allele_count	allele_bal	in_hm2	in_hm3	is_somatic	somatic_score	in_esp	aaf_esp_ea	aaf_esp_aa	aaf_esp_all	exome_chip	in_1kg	aaf_1kg_amr	aaf_1kg_eas	aaf_1kg_sas	aaf_1kg_afr	aaf_1kg_eur	aaf_1kg_all	grc	gms_illumina	gms_solid	gms_iontorrent	in_cse	encode_tfbs	encode_dnaseI_cell_count	encode_dnaseI_cell_list	encode_consensus_gm12878	encode_consensus_h1hesc	encode_consensus_helas3	encode_consensus_hepg2	encode_consensus_huvec	encode_consensus_k562	vista_enhancers	cosmic_ids	info	cadd_raw	cadd_scaled	fitcons	in_exac	aaf_exac_all	aaf_adj_exac_all	aaf_adj_exac_afr	aaf_adj_exac_amr	aaf_adj_exac_eas	aaf_adj_exac_fin	aaf_adj_exac_nfe	aaf_adj_exac_oth	aaf_adj_exac_sas	vep_CANONICAL	vep_CCDS	vep_HGVSc	vep_HGVSp	max_aaf_all	systematic_errors
> $

**Comment by brentp** [comment]
could  you try master? I think this is fixed as of yesterday: https://github.com/arq5x/gemini/pull/574

**Comment by brentp** [comment]
and we'll be releasing 0.18 soon.

**Comment by jxchong** [comment]
This appears to fix things. 

	$ gemini query -q "select * from variants" testanno.VEP.db --header
	chrom	start	end	vcf_id	variant_id	anno_id	ref	alt	qual	filter	type	sub_type	call_rate	in_dbsnp	rs_ids	sv_cipos_start_left	sv_cipos_end_left	sv_cipos_start_right	sv_cipos_end_right	sv_length	sv_is_precise	sv_tool	sv_evidence_type	sv_event_id	sv_mate_id	sv_strand	in_omim	clinvar_sig	clinvar_disease_name	clinvar_dbsource	clinvar_dbsource_id	clinvar_origin	clinvar_dsdb	clinvar_dsdbid	clinvar_disease_acc	clinvar_in_locus_spec_db	clinvar_on_diag_assay	clinvar_causal_allele	pfam_domain	cyto_band	rmsk	in_cpg_island	in_segdup	is_conserved	gerp_bp_score	gerp_element_pval	num_hom_ref	num_het	num_hom_alt	num_unknown	aaf	hwe	inbreeding_coeff	pi	recomb_rate	gene	transcript	is_exonic	is_coding	is_splicing	is_lof	exon	codon_change	aa_change	aa_length	biotype	impact	impact_so	impact_severity	polyphen_pred	polyphen_score	sift_pred	sift_score	anc_allele	rms_bq	cigar	depth	strand_bias	rms_map_qual	in_hom_run	num_mapq_zero	num_alleles	num_reads_w_dels	haplotype_score	qual_depth	allele_count	allele_bal	in_hm2	in_hm3	is_somatic	somatic_score	in_esp	aaf_esp_ea	aaf_esp_aa	aaf_esp_all	exome_chip	in_1kg	aaf_1kg_amr	aaf_1kg_eas	aaf_1kg_sas	aaf_1kg_afr	aaf_1kg_eur	aaf_1kg_all	grc	gms_illumina	gms_solid	gms_iontorrent	in_cse	encode_tfbs	encode_dnaseI_cell_count	encode_dnaseI_cell_list	encode_consensus_gm12878	encode_consensus_h1hesc	encode_consensus_helas3	encode_consensus_hepg2	encode_consensus_huvec	encode_consensus_k562	vista_enhancers	cosmic_ids	info	cadd_raw	cadd_scaled	fitcons	in_exac	aaf_exac_all	aaf_adj_exac_all	aaf_adj_exac_afr	aaf_adj_exac_amr	aaf_adj_exac_eas	aaf_adj_exac_fin	aaf_adj_exac_nfe	aaf_adj_exac_oth	aaf_adj_exac_sas	exac_num_het	exac_num_hom_alt	exac_num_chroms	vep_canonical	vep_ccds	vep_hgvsc	vep_hgvsp	max_aaf_all
	chr8	30969262	30969263	None	1	2	C	T	3141.2800293	None	snp	ts	1.0	0	None	None	None	None	None	None	1	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	None	chr8p12	None	0	0	1	4.26000022888	2.01137e-79	24	0	1	0	0.04	5.73573050278e-07	None	0.0783673469388	0.334487	WRN	ENST00000298139	1	1	0	1	19/35	Cga/Tga	R/*	741/1432	protein_coding	stop_gained	stop_gained	HIGH		None		None	None	None	None	3015	None	60.0	None	0	50	None	None	31.7299995422	2	None	None	None	None	None	0	None	None	None	0	0	None	None	None	None	None	None	None	None	None	None	0	None	None	None	T	R	R	R	T	T	None	None	None	None	None	0.732398	1	1.647e-05	1.64891336609e-05	9.61723408348e-05	0	0	0	1.49974504334e-05	0	0	2	0	121292	YES	CCDS6082.1	ENST00000298139.5:c.2221C>T	ENSP00000298139.5:p.Arg741Ter	9.61723408348e-05

**Comment by brentp** [comment]
cool. fix is thanks to @jsh58

**Comment by jxchong** [comment]
Actually, I just tried loading an entire vcf and got some errors that seem possibly related.

If you need, I can email you with the vcf.

	Done loading 90739 variants in 3 chunks.
	2015-10-27 15:36:55 merging 3 chunks.
	Traceback (most recent call last):
	  File "/usr/local/bin/gemini", line 6, in <module>
	    gemini.gemini_main.main()
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1166, in main
	    args.func(parser, args)
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 323, in mergechunk_fn
	    gemini_merge_chunks.merge_chunks(parser, args)
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_merge_chunks.py", line 225, in merge_chunks
	    merge_db_chunks(args)
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_merge_chunks.py", line 180, in merge_db_chunks
	    gemini_db.create_tables(main_curr, gemini_load_chunk.get_extra_effects_fields(args) if args.vcf else [])
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/database.py", line 101, in create_tables
	    effect_string = "".join(e + " TEXT,\n" for e in effect_fields)
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/database.py", line 101, in <genexpr>
	    effect_string = "".join(e + " TEXT,\n" for e in effect_fields)
	TypeError: can only concatenate tuple (not "str") to tuple
	Traceback (most recent call last):
	  File "/usr/local/bin/gemini", line 6, in <module>
	    gemini.gemini_main.main()
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1166, in main
	    args.func(parser, args)
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 192, in load_fn
	    gemini_load.load(parser, args)
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 49, in load
	    load_multicore(args)
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 75, in load_multicore
	    merge_chunks_multicore(chunks, args)
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 156, in merge_chunks_multicore
	    wait_until_finished(procs)
	  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 341, in wait_until_finished
	    raise ValueError("Processing failed on GEMINI chunk load")
	ValueError: Processing failed on GEMINI chunk load

**Comment by brentp** [comment]
yes, please email the VCF.

**Comment by jxchong** [comment]
Looks like this is fixed.
