### ISSUE TITLE
gemini 0.17.2 --gt-pl-max doesn't work with comp_hets?

### ISSUE THREAD

**Issue by jxchong** [arq5x/gemini#579]
$ gemini comp_hets \
	> --columns "chrom,start,end,ref,alt,gene,impact,filter,transcript,vep_CANONICAL,exon,vep_HGVSp,aa_change,aa_length,vep_HGVSc,codon_change,rs_ids,cadd_scaled,polyphen_score,sift_score,gerp_bp_score,max_aaf_all,aaf_exac_all,aaf_esp_all,aaf_1kg_all,systematic_errors,clinvar_disease_name,clinvar_sig,(gt_depths).(*),(gt_quals).(*)" \
	> --filter "(filter is NULL or filter=='VQSRTrancheSNP99.00to99.90') \
	> and max_aaf_all <= 0.005 \
	> and impact_severity <> 'LOW' and systematic_errors != 1" \
	> -d 4 \
	> --gt-pl-max 10 \
	> myproject.VT.vep.db > myproject.comphet.defaultGATKdefaultfxn.1of17.tsv
	Traceback (most recent call last):
	  File "/cm/shared/apps/bin/gemini", line 6, in <module>
	    gemini.gemini_main.main()
	  File "/cm/shared/apps/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1161, in main
	    args.func(parser, args)
	  File "/cm/shared/apps/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 679, in comp_hets_fn
	    CompoundHet(args).run()
	  File "/cm/shared/apps/gemini/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 31, in __init__
	    self.set_family_info()
	  File "/cm/shared/apps/gemini/anaconda/lib/python2.7/site-packages/gemini/gim.py", line 137, in set_family_info
	    **kwargs)
	  File "/cm/shared/apps/gemini/anaconda/lib/python2.7/site-packages/gemini/family.py", line 928, in comp_het
	    un &= reduce(op.and_, [s.gt_phred_ll_homalt > gt_ll for s in self.unaffecteds])
	TypeError: reduce() of empty sequence with no initial value

Also when I run comp_hets without --gt-pl-max, I only get results from the full trios, not from the single probands.

**Comment by jxchong** [comment]
and same error from autosomal_recessive

If this is expected, that's probably fine, but it's not documented as such.

**Comment by brentp** [comment]
I wrote a quick fix for this that's now in master. I'll add tests before next release but should address what you're seeing.

**Comment by arq5x** [comment]
"Also when I run comp_hets without --gt-pl-max, I only get results from the full trios, not from the single probands."
Is this addressed by relaxing the max priority? The default is the highest priority which would only yield results for families where the relevant alleles are clearly on opposite chromosomes. @brentp - what is the current logic for single probands?

**Comment by brentp** [comment]
unless the single probands are already phased, they will have priority 2.

**Comment by arq5x** [comment]
@jxchong can you let us know if the single pro bands don't pop up with priority 2?

**Comment by jxchong** [comment]
Ok looks like --gt-pl-max works now as well. Thanks!! 

Sorry, it looks like the no results from single probands was my mistake. I forgot that --max-priority defaulting to 1 had been implemented already. (not currently mentioned in ReadtheDocs -- sorry I'm swamped today otherwise I'd update it myself) ;)

However, if I have to drop down to priority 2 to see the single proband results, this existing issue acquires greater importance to me as an analyst: https://github.com/arq5x/gemini/issues/549

Perhaps making single proband results priority 2 and dropping the others down to priority 3?
