### ISSUE TITLE
provide variant.alt_depth / (variant.alt_depth + variant.ref_depth) available for filtering

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#584]
this could mitigate some of the losses that we from hard-filtering, e.g. instead of 
`gt_types[0] == HOM_REF`, could specify `gt_depth_ratio[0] < 0.20`

**Comment by brentp** [comment]
in response to Deanna Churh's talk at gi2015

**Comment by chapmanb** [comment]
Good idea. Stratifying by allele frequency is very useful, especially for cancer calling. Here's an in-progress post about using filters specifically for low frequency variants with VarDict to improve sensitivity: https://github.com/bcbio/bcbio.github.io/blob/master/_posts/2015-10-05-vardict-filtering.md

**Comment by arq5x** [comment]
Decided to create a new column called ``gt_alt_freq`` for next major release.

**Comment by rronen** [comment]
:+1: !!

This is super useful when filtering somatic variants (and couldn't be achieved on the fly with SQL arithmetic as the necessary fields are in blobs)
