### ISSUE TITLE
allow filtering on GQ in addition to GL in inheritance tools

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#586]
via @jxchong and Josh. We can add this a a --gq-min option since gt_quals are available already.

**Comment by brentp** [comment]
this is implemented in https://github.com/brentp/inheritance, we just need to expose it to gemini

**Comment by jxchong** [comment]
Interesting, implementing this manually halves the number of variants I get from a trio called with HaplotypeCaller vs UnifiedGenotyper. Might be pipeline-specific or maybe HC is being much more aggressive about attempting to call a variant even if the GQ is very low.

**Comment by brentp** [comment]
so it filters more variants from HC? Maybe I should get this in for 0.18

**Comment by jxchong** [comment]
Yes almost half of the variants that would otherwise end up in output would be excluded instead. I don't know if this is just an artifact of our pipeline but being able to filter on gq sooner rather than later would be extremely useful.

**Comment by arq5x** [comment]
@jxchong - this effect jogs a memory of a similar finding I heard discussed at a conference. In typical fashion, I can't remember when, where or whom. I recall a plot showing a marked left shift in the GQ assignments for HC versus UG.

**Comment by jxchong** [comment]
Oh good I'm not crazy ;)
