### ISSUE TITLE
comp_hets returns none

### ISSUE THREAD

**Issue by batsal** [arq5x/gemini#589]
Hi,

I annotated with snpEff and phased the vcf with GATK PhaseByTransmission and loaded it to Gemini. Works fine for de_novo but with comp_hets - it returns empty set. I suspect it may be vcf issue, is there a way to send the header to have it looked at?

Thanks.

Batsal.

**Comment by brentp** [comment]
You can email an example vcf and ped to bpederse@gmail.com if that's what you mean. It could be that there really are no comp_het candidates.
