### ISSUE TITLE
Gemini 0.17.2 does not import vep_LoF

### ISSUE THREAD

**Issue by MinocheAE** [arq5x/gemini#601]
Hi, With gemini 0.17.2 the vep_LoF column is always NULL, even though the input vcf contains many HC (high confidence) entries for this field.

It is unlikely caused by the VEP version, since with the same VEP (v79) and an older version of gemini, the import of vep_LoF worked correctly.

This is how I load the database: gemini load -v $vcf -t VEP --cores 16 out.db
This is my query: gemini query -q "select * from variants where (vep_LoF = 'HC' ) " --header out.db

I would be grateful for any assistance in this matter.

**Comment by brentp** [comment]
Hi, we have fixed some vep-related bugs since 0.17.2 that will be released soon in 0.18, could you try out master and let us know if that fixes this for you?
And/or if you have a VCF with a couple of records, it'd be good to add it as a test.

**Comment by MinocheAE** [comment]
Thank you for the fix! I updated to master using "gemini update --devel". Column vep_LoF gets now populated.

**Comment by brentp** [comment]
great. I'm going to close this. please reopen if you see any more problems.
