### ISSUE TITLE
some beginner questions

### ISSUE THREAD

**Issue by johnrabbit** [arq5x/gemini#602]
Hey,

I have some basic questions... Sorry, if I have overseen the relevant docs..

1) I have problems with sequentially loading multiple vcfs - when I do this, only the latest one is in the db
Can I only load multiple samples using a merged vcf ?

2) Having loaded the vcf without the snpeff or vep annotation, can i just update this info from an annotated vcf later, without reimporting the whole variants again ? And can I use both infos in parallel ? E.g. when snpeff is not providing an annotation for a specific region, but vep does, can i streamline to use the annotation in this order ?

3) Is there a "how to" on importing ANNOVAR information also ?

Thanks,

John

**Comment by brentp** [comment]
Hi,
1. you must load a single multi-sample VCF. If you didn't do multisample calling, then you should re-call all samples at once.
2. you can use gemini annotate but this just adds a single column from another VCF
3. currently, annovar is not supported.

**Comment by brentp** [comment]
closing for now. Please use the mailing list if you have further questions.
