### ISSUE TITLE
gemini_install.py permission denied

### ISSUE THREAD

**Issue by rchekaluk** [arq5x/gemini#603]
Permission denied when executing gemini_install.py on Ubuntu:
```
$ /usr/local/anaconda/bin/python gemini_install.py  /usr/local /usr/local/share/gemini
Checking required dependencies...
 wget found
Installing isolated base python installation
Traceback (most recent call last):
  File "gemini_install.py", line 184, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 77, in main
    make_dirs(args)
  File "gemini_install.py", line 147, in make_dirs
    os.makedirs(dname)
  File "/usr/local/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/share/gemini'
```
```
$ ls -l /usr/local | grep share
drwxr-xr-x 14 root   root   4096 Nov 13 13:09 share
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

**Comment by chapmanb** [comment]
The installer respects filesystem permissions on your machine, so will only install in locations where your user has permission. If you have sudo access, you can chown `/usr/local` and `/usr/local/share/gemini` to your local user and then run the installation. Alternatively, set the data and tool directories to locations on your system where you have write permissions.

Also, while looking at this I realized the new installation method accidentally swapped the order of the tool directory and data directory arguments. This doesn't have anything to do with your error but when you re-run you should get the latest version of the script:

wget https://raw.githubusercontent.com/arq5x/gemini/master/gemini/scripts/gemini_install.py

Hope this gets you going and apologies for the issues. We're working through a new easier installation process for the new release coming next week. Thanks much.
