### ISSUE TITLE
VEP v82/GEMINI

### ISSUE THREAD

**Issue by jxchong** [arq5x/gemini#605]
I've been getting this error and I'm slowly trying to figure out whether it's a problem with VEP or GEMINI or version incompatibility between the two (or neither).

I get this error when loading a database in GEMINI 0.17.2 with a file annotated with VEPv82. This error message has been reported previously, not sure if this is related. https://github.com/chapmanb/bcbio-nextgen/issues/766

    CADD scores are being loaded (to skip use:--skip-cadd).
    GERP per bp is being loaded (to skip use:--skip-gerp-bp).
    WARNING: The input VCF has no VEP annotations.                              Variant impact will be set to unknown
    WARNING: The input VCF has no VEP annotations.                              Variant impact will be set to unknown
    WARNING: The input VCF has no VEP annotations.                              Variant impact will be set to unknown
    [..repeats for ~1200 of the variants in the vcf..]

Looks like I don't get the error if I use the most recent GEMINI `GEMINI update --devel` but instead I get:

    $ gemini load -v mydata.final.VT.VEP.vcf.gz -t VEP mydata.final.VT.VEP.db
    CADD scores are being loaded (to skip use:--skip-cadd).
    GERP per bp is being loaded (to skip use:--skip-gerp-bp).
    Traceback (most recent call last):
    File "/usr/local/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
    File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1179, in main
    args.func(parser, args)
    File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 198, in load_fn
    gemini_load.load(parser, args)
    File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 51, in load
    load_singlecore(args)
    File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load.py", line 60, in load_singlecore
    gemini_loader.populate_from_vcf()
    File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 177, in populate_from_vcf
    (variant, variant_impacts, extra_fields) = self._prepare_variation(var, anno_keys)
    File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_load_chunk.py", line 429, in _prepare_variation
    impacts += [geneimpacts.VEP(e, anno_keys["CSQ"]) for e in var.INFO["CSQ"].split(",")]
    File "cyvcf2/cyvcf2.pyx", line 1052, in cyvcf2.cyvcf2.INFO.__getitem__ (cyvcf2/cyvcf2.c:20961)
    KeyError

Here's my header from my vcf:

    ##INFO=<ID=OLD_MULTIALLELIC,Number=1,Type=String,Description="Original chr:pos:ref:alt encoding">
    ##INFO=<ID=OLD_VARIANT,Number=.,Type=String,Description="Original chr:pos:ref:alt encoding">
    ##VEP=v82 cache=variant_effect_predictor/cache//homo_sapiens/82_GRCh37 db=. polyphen=2.2.2 sift=sift5.2.2 COSMIC=71 ESP=20141103 gencode=GENCODE 19 HGMD-PUBLIC=20152 genebuild=2011-04 regbuild=13 assembly=GRCh37.p13 dbSNP=144 ClinVar=201507
    ##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Consequence|Codons|Amino_acids|Gene|SYMBOL|Feature|EXON|PolyPhen|SIFT|Protein_position|BIOTYPE|CANONICAL|CCDS|HGVSc|HGVSp"

**Comment by jxchong** [comment]
GEMIN 0.16.3 + VEPv82 also gives

    CADD scores are being loaded (to skip use:--skip-cadd).
    GERP per bp is being loaded (to skip use:--skip-gerp-bp).
    WARNING: The input VCF has no VEP annotations.                              Variant impact will be set to unknown
    WARNING: The input VCF has no VEP annotations.                              Variant impact will be set to unknown
    WARNING: The input VCF has no VEP annotations.                              Variant impact will be set to unknown
    [..repeats for some subset of variants..]

**Comment by udp3f** [comment]
This is an internal warning, specific to GEMINI. I remember, we did that sometime back to make sure 'VEP' annotations were done as documented. Looks like some clean up is needed :)
-Uma

**Comment by brentp** [comment]
so some VCF records don't have CSQ in the INFO?

**Comment by brentp** [comment]
I was able to recreate by adding a variant without a CSQ field to a vep-annotated VCF. This is now fixed in master. Thanks for reporting.

**Comment by jxchong** [comment]
ahhh apparently VEP is having problems with these lines that I'm guessing are a result of using VT (vt 0.57)

    1	237905571	rs3753630	T	*	6117.46	PASS	AC=0;AF=0.14;AN=24;BaseQRankSum=0.817;ClippingRankSum=0.091;DB;DP=8372;FS=0;InbreedingCoeff=-0.2088;MLEAC=34;MLEAF=0.159;MQ0=0;MQ=57.9;MQRankSum=0.37;NEGATIVE_TRAIN_SITE;POSITIVE_TRAIN_SITE;QD=3.33;ReadPosRankSum=1.03;SOR=0.674;VQSLOD=1.02;culprit=MQ;OLD_MULTIALLELIC=1:237905571:T/C/*	GT:AD:DP:GQ:PL	0/0:20,0:20:0:0,0,456	0/0:17,6:30:15:15,0,512	0/0:18,4:31:16:16,0,585	0/0:39,0:43:41:0,116,1154	0/0:20,6:26:47:47,0,380	0/0:34,4:38:28:0,28,699	0/.:29,0:34:7:7,93,951	0/0:40,0:45:54:0,119,1255	0/0:23,0:25:23:0,68,648	0/0:9,2:18:27:0,43,777	0/0:38,0:38:0:0,0,495	0/0:44,0:51:41:0,132,1321
    1	240370934	rs4997328	G	*	15541.4	PASS	AC=0;AF=0.168;AN=24;BaseQRankSum=0.517;ClippingRankSum=-0.152;DB;DP=3959;FS=4.691;InbreedingCoeff=0.0395;MLEAC=36;MLEAF=0.173;MQ0=0;MQ=58.95;MQRankSum=-0.286;QD=15.81;ReadPosRankSum=-1.516;SOR=0.447;VQSLOD=-0.2163;culprit=MQ;OLD_MULTIALLELIC=1:240370934:G/C/*	GT:AD:DP:GQ:PL	0/0:0,35:35:99:1491,112,0	0/0:29,0:29:62:0,62,1032	0/0:21,0:21:63:0,63,725	0/0:20,0:20:60:0,60,725	0/0:30,0:30:75:0,75,1305	0/0:26,0:26:65:0,65,956	0/0:22,0:22:62:0,62,761	0/0:21,0:21:60:0,60,756	0/0:0,39:39:99:1820,137,0	0/0:48,18:66:99:619,0,1948	0/0:56,0:56:0:0,0,612	0/0:22,0:22:66:0,66,762

**Comment by brentp** [comment]
'*' for ALT, that's a new one.

**Comment by jxchong** [comment]
Ok nope, it's not vt, it's apparently GATK?!?!

original vcf: 

    1	237905571	rs3753630	T	C,*	6117.46	PASS	AC=1,0;AF=0.042,0.140;AN=24;BaseQRankSum=0.817;ClippingRankSum=0.091;DB;DP=8372;FS=0.000;InbreedingCoeff=-0.2088;MLEAC=9,34;MLEAF=0.042,0.159;MQ0=0;MQ=57.90;MQRankSum=0.370;NEGATIVE_TRAIN_SITE;POSITIVE_TRAIN_SITE;QD=3.33;ReadPosRankSum=1.03;SOR=0.674;VQSLOD=1.02;culprit=MQ	GT:AD:DP:GQ:PL	0/0:20,0,0:20:0:0,0,456,0,456,456	0/0:17,0,6:30:15:15,64,406,0,345,512	0/0:18,0,4:31:16:16,47,420,0,378,585	0/0:39,4,0:43:41:0,41,1067,116,1079,1154	0/0:20,0,6:26:47:47,106,503,0,397,380	0/0:34,0,4:38:28:0,101,783,28,710,699	0/1:29,5,0:34:7:7,0,843,93,858,951	0/0:40,5,0:45:54:0,54,1176,119,1190,1255	0/0:23,2,0:25:23:0,23,597,68,603,648	0/0:9,0,2:18:27:0,27,220,43,246,777	0/0:38,0,0:38:0:0,0,495,0,495,495	0/0:44,7,0:51:41:0,41,1211,132,1229,1321

**Comment by jxchong** [comment]
Ughhh ok so I guess I have to report this to VEP's developers too since * is apparently an official alt allele possibility. Since VEP appears to not know what to do with *, it just entirely skips that variant and doesn't leave a CSQ field (which GEMINI then complains about missing).

**Comment by brentp** [comment]
I dont get why for that variant, you don't have any 0/2 or 1/2 genotypes.

**Comment by jxchong** [comment]
.. I don't either. This is the first time I've come across this (since we only recently started using HaplotypeCaller). My current best guess is that it's because the * is leftover from other samples (possibly a GATK bug?) because these variants were derived from gVCFs.

Here are both vt normalized records:

    1	237905571	rs3753630	T	C	6117.46	PASS	AC=1;AF=0.042;AN=24;BaseQRankSum=0.817;ClippingRankSum=0.091;DB;DP=8372;FS=0;InbreedingCoeff=-0.2088;MLEAC=9;MLEAF=0.042;MQ0=0;MQ=57.9;MQRankSum=0.37;NEGATIVE_TRAIN_SITE;POSITIVE_TRAIN_SITE;QD=3.33;ReadPosRankSum=1.03;SOR=0.674;VQSLOD=1.02;culprit=MQ;OLD_MULTIALLELIC=1:237905571:T/C/*	GT:AD:DP:GQ:PL	0/0:20,0:20:0:0,0,456	0/0:17,0:30:15:15,64,406	0/0:18,0:31:16:16,47,420	0/0:39,4:43:41:0,41,1067	0/0:20,0:26:47:47,106,503	0/0:34,0:38:28:0,101,783	0/1:29,5:34:7:7,0,843	0/0:40,5:45:54:0,54,1176	0/0:23,2:25:23:0,23,597	0/0:9,0:18:27:0,27,220	0/0:38,0:38:0:0,0,495	0/0:44,7:51:41:0,41,1211
    1	237905571	rs3753630	T	*	6117.46	PASS	AC=0;AF=0.14;AN=24;BaseQRankSum=0.817;ClippingRankSum=0.091;DB;DP=8372;FS=0;InbreedingCoeff=-0.2088;MLEAC=34;MLEAF=0.159;MQ0=0;MQ=57.9;MQRankSum=0.37;NEGATIVE_TRAIN_SITE;POSITIVE_TRAIN_SITE;QD=3.33;ReadPosRankSum=1.03;SOR=0.674;VQSLOD=1.02;culprit=MQ;OLD_MULTIALLELIC=1:237905571:T/C/*	GT:AD:DP:GQ:PL	0/0:20,0:20:0:0,0,456	0/0:17,6:30:15:15,0,512	0/0:18,4:31:16:16,0,585	0/0:39,0:43:41:0,116,1154	0/0:20,6:26:47:47,0,380	0/0:34,4:38:28:0,28,699	0/.:29,0:34:7:7,93,951	0/0:40,0:45:54:0,119,1255	0/0:23,0:25:23:0,68,648	0/0:9,2:18:27:0,43,777	0/0:38,0:38:0:0,0,495	0/0:44,0:51:41:0,132,1321

**Comment by jxchong** [comment]
Ok, the * leftover without any samples with that allele seem to be an artifact of our pipeline when dealing with VQSR on small sample sets (and using additional controls to increase sample size sufficiently for running VQSR). It seems our pipeline (or whatever software used in our pipeline) was failing to recognize * as an allele and failing to remove it as an allele if the site is monomorphic within a small sample set. 

Fun all around for everyone thanks to *!
