### ISSUE TITLE
pyparsing and Python 3 (in)compatibility

### ISSUE THREAD

**Issue by robinandeer** [arq5x/gemini#608]
Trying to setup travis with a gemini install for Python 3 and getting an exception for the `pyparsing` module (v1.5.7) which doesn't seem to be compatible with Python 3 syntax:

```
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-76omn6aw/pyparsing/setup.py", line 9, in <module>
        from pyparsing import __version__ as pyparsing_version
      File "/tmp/pip-build-76omn6aw/pyparsing/pyparsing.py", line 855
        except ParseBaseException, err:
                                 ^
    SyntaxError: invalid syntax
```

I looked briefly in your `setup.py` and it seems you aim to support Python 2/3 so I thought I'd open this issue :)

Perhaps a later version of `pyparsing` does include Python 3 support?

**Comment by brentp** [comment]
we do not support python3. Only python 2.7 will work at this time.

**Comment by robinandeer** [comment]
Sorry, my bad! Cool project either way :)

**Comment by brentp** [comment]
No problem. Let us know if you find any issues. Support for python3 is on the distant horizon, but not impending.
