### ISSUE TITLE
Comp_hets analysis

### ISSUE THREAD

**Issue by nfarzaneh** [arq5x/gemini#616]
Hello,

I have been using your comp_hets analysis before the recent changes were made (prior to version 16).  Before, I would phase my SNPs before loading them into GEMINI.  Now, I believe that things have changed, if I am not mistaken.

Now, I enter my VCF file with a ped file (phased or unphased) but it seems to only call compound hets for pedigree structures which have parents.  Is there a way GEMINI can call compound hets even for one single sample, if it has been phased beforehand or can GEMINI only call comp_hets when it has information from both parents?

Thanks!
Nima Farzaneh

**Comment by brentp** [comment]
Hi, in version 0.18.0 we give a single sample a priority of 2. So you can run with --max-priority 2 and get singletons as well. I'll leave this open for now in case you continue to encounter issues.

**Comment by nfarzaneh** [comment]
Hello Brent,

So if I understand this correctly, I should phase my data before loading it into GEMINI and then run comp_hets --max-priority 2 to get all compound hets - including singletons?

Nima

**Comment by brentp** [comment]
you don't need to phase beforehand, just run with `--max-priority 2`

**Comment by nfarzaneh** [comment]
Hello Brent,

Could you please clarify how GEMINI calls compound hets of priority 2 and in general?  Some of my samples do not have parents and so is it able to call a compound hets (similar to what Read-Aware Phasing can do)?  

Any more information on this would be greatly appreciated.

Nima

**Comment by jxchong** [comment]
Looks like the documentation is contradictory right now. 

Under genotype requirements:
> If data from one or both parents are unavailable and the child’s data was not phased prior to loading into GEMINI, all comp_het variant pairs will automatically be given `priority == 3`

I think it should be `--max-priority 2` as of 0.18.0 based on our discussions but want to make sure that's the case.

**Comment by brentp** [comment]
yes, it would be priority 2. I'll change that next week unless someone beats me to it.

**Comment by brentp** [comment]
@nfarzaneh were you able to get this working on singletons?
