### ISSUE TITLE
impact severity lookup KeyError

### ISSUE THREAD

**Issue by timle** [arq5x/gemini#619]
Hi,

I have had two separate errors relating to missing entries on the 'IMPACT_SEVERITY' list. These are from files processed with snpEff v3.6. When this happens, no gemini DB is written.

The issue comes up with the seemingly rare occurrence of compound labels - these are the two that have come up so far. 
> "5_prime_UTR_truncation_+_exon_loss_variant"
> "3_prime_UTR_truncation_+_exon_loss_variant"

Example error: 
>   File "/data/anaconda/lib/python2.7/site-packages/geneimpacts/effect.py", line 557, in severity
>         sevs = [IMPACT_SEVERITY[csq] for csq in self.consequences]
>	 KeyError: '5_prime_UTR_truncation_+_exon_loss_variant

The code throwing the error:
>    try:
>        return max(lookup[old_snpeff_lookup[csq]] for csq in self.consequences)
>    except KeyError:
>        #in between
>        sevs = [IMPACT_SEVERITY[csq] for csq in self.consequences]
>        return max(lookup[s] for s in sevs)'''

The easy answer would be to add these entries to the IMPACT_SEVERITY list, though I am unsure what the severity actually would be. However, there may be even more compounds out there, necessitating a more robust approach than keying against the IMPACT_SEVERITY dict.

**Comment by brentp** [comment]
can you send a small sample of the VCF (no genotypes needed) and the snpEff command that you used?

We support snpEff 4+ now, so you don't need to use the older version or -classic mode, but I'd still like to fix this.

**Comment by brentp** [comment]
closing this as it appears to be from an older version of the geneimpacts module. Please re-open with example if you continue to experience the problem.
