### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by mikecroucher** [arq5x/gemini#621]
Hi

I recently installed gemini on The University of Sheffield's HPC system but note that one of the tests failed.

```
    effstring.t02...\c
ok
    effstring.t03...\c
15d14
< gene        impact  impact_severity biotype is_exonic       is_coding       is_lof
64a64
> gene        impact  impact_severity biotype is_exonic       is_coding       is_lof
fail
updated 10 variants
     annotate-tool.t1 ... ok
```

Details of how it was installed and tested are on our website at http://rcg.group.shef.ac.uk/iceberg/software/apps/gemini.html

Do I need to worry about this failure? If so, can you help with where to start debugging it please?

**Comment by brentp** [comment]
I'll look into it but it looks like there is no diff between observed and expected so I think you are good to ignore it

**Comment by mikecroucher** [comment]
Thanks. I suspected it was a test bug rather than a test fail but since I don't know anything about gemini I wanted to check with you guys.

Nice install procedure btw! If only everything was as painless.

**Comment by brentp** [comment]
this is fixed in the commit above.
