### ISSUE TITLE
ExAC frequencies decomposition bug

### ISSUE THREAD

**Issue by muraveill** [arq5x/gemini#630]
Here is a screenshot where the 1000Genomes and ESP freqs are correct but the Exac is badly decomposed.

![screen shot 2015-12-08 at 17 15 08](https://cloud.githubusercontent.com/assets/12040845/11660842/4a72c74a-9dcf-11e5-817a-d37b4d644faa.png)

Or in the sqlite:

    sqlite> select aaf_1kg_all,aaf_esp_all,aaf_exac_all from variants where start=11210911;
    ||0.086
    0.0569089|0.0905735814239582|0.086

Below I copied the 2 VCF entries showing that the first variants has only 0/0 genotypes, while the second has some 0/1, in agreement with the 1KG and ESP frequencies.

19	11210912	rs2228671	C	G	279271	PASS
[...]
0/.:602,0,572:1176:99:13907,15696,32619	0/0:1316,0,5:1322:99:0,3942,41266	0/0:1388,2,1:1391:99:0,4099,43441	0/0:1539,0,1:1540:99:0,4598,48065	0/0:2496,0,3:2499:99:0,7438,75589	0/0:1319,0,4:1324:99:0,3934,38858	0/0:1417,0,3:1421:99:0,4249,44388	0/0:1076,0,3:1079:99:0,3224,33707	0/0:2494,0,2:2496:99:0,7426,79681	0/0:1407,0,7:1415:99:0,4211,41749	0/0:1283,0,0:1283:99:0,3833,38990	0/0:1520,0,2:1522:99:0,4547,47560	0/0:1294,0,3:1297:99:0,3864,40428	0/0:1402,0,2:1404:99:0,4191,42688	0/0:1141,0,0:1141:99:0,3402,33619	0/0:1432,0,3:1435:99:0,4284,43589	0/0:1302,0,5:1307:99:0,3891,40705	0/0:1370,0,4:1375:99:0,4099,42863	0/0:1123,0,0:1123:99:0,3371,35251	0/0:1196,0,1:1197:99:0,3587,37423	0/0:2489,0,6:2496:99:0,7446,77779	0/0:1463,0,5:1468:99:0,4378,45751	0/0:1744,0,2:1746:99:0,5219,53063	0/.:681,0,619:1300:99:15436,17475,36770	0/.:556,0,523:1080:99:12307,13967,29219	0/0:1055,0,3:1058:99:0,3157,32048	0/0:869,0,1:871:99:0,2598,26371	0/0:1493,0,4:1497:99:0,4466,46743	0/.:772,0,720:1493:99:17511,19827,41713	0/0:1235,0,0:1235:99:0,3683,37417	0/0:2483,0,10:2493:99:0,7437,77799	0/0:1276,0,3:1279:99:0,3820,37825	0/0:1294,0,1:1295:99:0,3873,40521	0/0:1214,0,4:1218:99:0,3631,35928	0/0:1459,0,1:1460:99:0,4377,44596	0/0:1297,0,1:1298:99:0,3891,40671	0/0:1342,0,4:1346:99:0,4024,42121	0/0:1406,0,3:1409:99:0,4203,42751	./.:4,1,1179:1184:99:35752,35741,35849	0/0:1300,0,3:1303:99:0,3883,38403	0/0:1260,0,4:1264:99:0,3773,38409	0/0:2489,0,7:2496:99:0,7433,73490	0/0:1447,0,3:1450:99:0,4329,44091	0/0:2488,0,8:2498:99:0,7436,77671	0/0:1080,0,8:1088:99:0,3220,32743	0/0:1309,0,2:1312:99:0,3916,38720	0/0:1269,1,2:1272:99:0,3804,39816	0/0:1239,0,0:1239:99:0,3702,38675	0/0:2491,0,7:2498:99:0,7437,77817	0/.:551,0,564:1116:99:13795,15449,31119	0/0:1332,0,2:1334:99:0,3991,41766	0/.:702,0,709:1412:99:18057,20160,40607	0/0:1508,0,5:1516:99:0,4514,47220	0/.:607,0,632:1240:99:15508,17325,34502	0/0:1008,0,2:1010:99:0,3012,30594	0/0:1236,0,2:1238:99:0,3696,38648	0/.:832,1,873:1706:99:22185,24655,48245	0/0:1264,1,3:1268:99:0,3757,39579	0/.:592,0,514:1107:99:12262,14036,30829	0/0:1255,2,1:1259:99:0,3699,39222	0/0:1177,0,1:1178:99:0,3515,36778	0/0:1339,0,2:1341:99:0,4015,41994	0/0:1433,0,1:1434:99:0,4299,43804	0/0:1168,0,1:1170:99:0,3500,36634	0/0:1394,0,1:1395:99:0,4174,43638	0/0:1171,0,5:1176:99:0,3501,34592	0/.:1230,1,1265:2497:99:32088,35725,71427	0/0:1512,0,5:1517:99:0,4519,46023	0/0:1381,0,3:1384:99:0,4135,43297	0/0:1385,0,1:1386:99:0,4146,42161	0/0:1228,0,2:1231:99:0,3681,38376	0/0:1491,1,4:1496:99:0,4416,46480	0/0:1451,1,2:1455:99:0,4351,45530	0/1:549,526,1:1077:99:13176,0,13961	0/0:1387,1,3:1391:99:0,4112,43279	0/.:442,0,460:902:99:10488,11813,23575	0/0:2494,1,2:2497:99:0,7420,77809	0/0:1309,0,1:1310:99:0,3915,40927	0/0:1360,0,2:1362:99:0,4057,43592	0/0:1324,0,3:1327:99:0,3961,39177	0/0:1084,0,1:1086:99:0,3251,34907	0/.:620,1,600:1221:99:14613,16465,34003	0/0:1288,0,2:1290:99:0,3858,40349	0/0:1033,1,2:1036:99:0,3075,33284	0/0:1262,0,4:1267:99:0,3784,37475	0/0:1109,0,3:1112:99:0,3323,34787	0/0:1106,0,2:1110:99:0,3311,35563	0/0:2491,0,7:2498:99:0,7429,79725	0/.:717,2,641:1360:99:14897,16993,36700	0/0:1351,1,3:1355:99:0,4010,42210	0/0:1323,0,3:1326:99:0,3960,40314	0/0:1299,0,3:1302:99:0,3907,41941	0/0:1264,0,1:1265:99:0,3783,39544	0/.:658,0,706:1364:99:17504,19476,38156

19	11210912	rs2228671	C	T	279271	PASS
[....]
0/1:602,0,572:1176:99:13907,0,15210	0/0:1316,0,5:1322:99:0,3808,41117	0/0:1388,2,1:1391:99:0,4127,43472	0/0:1539,0,1:1540:99:0,4570,48034	0/0:2496,0,3:2499:99:0,7358,75500	0/0:1319,0,4:1324:99:0,3832,38743	0/0:1417,0,3:1421:99:0,4166,44296	0/0:1076,0,3:1079:99:0,3141,33615	0/0:2494,0,2:2496:99:0,7397,79649	0/0:1407,0,7:1415:99:0,4029,41545	0/0:1283,0,0:1283:99:0,3833,38990	0/0:1520,0,2:1522:99:0,4492,47499	0/0:1294,0,3:1297:99:0,3781,40336	0/0:1402,0,2:1404:99:0,4138,42629	0/0:1141,0,0:1141:99:0,3402,33619	0/0:1432,0,3:1435:99:0,4203,43499	0/0:1302,0,5:1307:99:0,3808,40613	0/0:1370,0,4:1375:99:0,4016,42771	0/0:1123,0,0:1123:99:0,3371,35251	0/0:1196,0,1:1197:99:0,3560,37393	0/0:2489,0,6:2496:99:0,7308,77626	0/0:1463,0,5:1468:99:0,4241,45599	0/0:1744,0,2:1746:99:0,5164,53002	0/1:681,0,619:1300:99:15436,0,17439	0/1:556,0,523:1080:99:12307,0,13680	0/0:1055,0,3:1058:99:0,3077,31959	0/0:869,0,1:871:99:0,2571,26342	0/0:1493,0,4:1497:99:0,4355,46621	0/1:772,0,720:1493:99:17511,0,19722	0/0:1235,0,0:1235:99:0,3683,37417	0/0:2483,0,10:2493:99:0,7167,77499	0/0:1276,0,3:1279:99:0,3748,37744	0/0:1294,0,1:1295:99:0,3873,40521	0/0:1214,0,4:1218:99:0,3528,35813	0/0:1459,0,1:1460:99:0,4351,44566	0/0:1297,0,1:1298:99:0,3864,40641	0/0:1342,0,4:1346:99:0,3913,41999	0/0:1406,0,3:1409:99:0,4120,42659	1/1:4,1,1179:1184:99:35752,3421,0	0/0:1300,0,3:1303:99:0,3832,38346	0/0:1260,0,4:1264:99:0,3666,38289	0/0:2489,0,7:2496:99:0,7279,73318	0/0:1447,0,3:1450:99:0,4247,43999	0/0:2488,0,8:2498:99:0,7216,77427	0/0:1080,0,8:1088:99:0,3113,32624	0/0:1309,0,2:1312:99:0,3863,38661	0/0:1269,1,2:1272:99:0,3748,39754	0/0:1239,0,0:1239:99:0,3702,38675	0/0:2491,0,7:2498:99:0,7244,77603	0/1:551,0,564:1116:99:13795,0,13986	0/0:1332,0,2:1334:99:0,3935,41705	0/1:702,0,709:1412:99:18057,0,18315	0/0:1508,0,5:1516:99:0,4405,47099	0/1:607,0,632:1240:99:15508,0,15284	0/0:1008,0,2:1010:99:0,2986,30564	0/0:1236,0,2:1238:99:0,3668,38618	0/1:832,1,873:1706:99:22185,0,20974	0/0:1264,1,3:1268:99:0,3703,39519	0/1:592,0,514:1107:99:12262,0,15259	0/0:1255,2,1:1259:99:0,3728,39255	0/0:1177,0,1:1178:99:0,3495,36754	0/0:1339,0,2:1341:99:0,3959,41933	0/0:1433,0,1:1434:99:0,4272,43774	0/0:1168,0,1:1170:99:0,3500,36634	0/0:1394,0,1:1395:99:0,4146,43608	0/0:1171,0,5:1176:99:0,3398,34476	0/1:1230,1,1265:2497:99:32088,0,31922	0/0:1512,0,5:1517:99:0,4386,45874	0/0:1381,0,3:1384:99:0,4052,43205	0/0:1385,0,1:1386:99:0,4118,42131	0/0:1228,0,2:1231:99:0,3625,38315	0/0:1491,1,4:1496:99:0,4362,46420	0/0:1451,1,2:1455:99:0,4296,45468	0/.:549,526,1:1077:99:13176,14790,30318	0/0:1387,1,3:1391:99:0,4060,43221	0/1:442,0,460:902:99:10488,0,10383	0/0:2494,1,2:2497:99:0,7393,77779	0/0:1309,0,1:1310:99:0,3890,40898	0/0:1360,0,2:1362:99:0,4002,43531	0/0:1324,0,3:1327:99:0,3883,39090	0/0:1084,0,1:1086:99:0,3224,34876	0/1:620,1,600:1221:99:14613,0,15743	0/0:1288,0,2:1290:99:0,3831,40318	0/0:1033,1,2:1036:99:0,3047,33252	0/0:1262,0,4:1267:99:0,3682,37360	0/0:1109,0,3:1112:99:0,3237,34692	0/0:1106,0,2:1110:99:0,3256,35502	0/0:2491,0,7:2498:99:0,7231,79506	0/1:717,2,641:1360:99:14897,0,17792	0/0:1351,1,3:1355:99:0,3956,42149	0/0:1323,0,3:1326:99:0,3880,40225	0/0:1299,0,3:1302:99:0,3824,41849	0/0:1264,0,1:1265:99:0,3755,39514	0/1:658,0,706:1364:99:17504,0,16560

**Comment by brentp** [comment]
What version of gemini are you using? On your gemini installed Exac.tidy.vcf.gz could you run:

```
$ tabix  ExAC.r0.3.sites.vep.tidy.vcf.gz 19:11210912-11210912 | grep -oP "A[C|N]_Adj=(.+?);"
```
and let me know what you see?
Mine is:
```
AC_Adj=10484;
AN_Adj=121058;
AC_Adj=2;
AN_Adj=121058;
```

**Comment by muraveill** [comment]
I am using 0.18.0, and the above command returns me 
AC_Adj=10484,2;
AN_Adj=121058;
AC_Adj=10484,2;
AN_Adj=121058;

**Comment by brentp** [comment]
did you update with `--nodata` ?
You can fix by removing your ExAC.r0.3.sites.vep.tidy.vcf.gz*
and doing 
```
wget https://s3.amazonaws.com/gemini-annotations/ExAC.r0.3.sites.vep.tidy.vcf.gz
wget https://s3.amazonaws.com/gemini-annotations/ExAC.r0.3.sites.vep.tidy.vcf.gz.tbi
```

we should have some md5sum checking to avoid this type of problem.

**Comment by muraveill** [comment]
All right, my gemini-config.yaml indicated another location with old databases from 0.11, and I also needed the --annotationdir option to "gemini update" to point to the new ones. Issue closed, thanks.

One problem though is that when I run "gemini update" with the wrong configuration **and the destination folder is read-only**, it does not give me any error - and no update is done.

**Comment by brentp** [comment]
can you open a new issue with that gemini update error?

**Comment by muraveill** [comment]
#634

**Comment by brentp** [comment]
cheers.
