### ISSUE TITLE
error in annotation_dir option installing data

### ISSUE THREAD

**Issue by lpantano** [arq5x/gemini#633]
Hi!

I am having problems when using this command:

` /home/lpantano/soft/bcbio/anaconda/bin/gemini --annotation-dir /home/lpantano/soft/bcbio/gemini_data update --dataonly`

i think is because there is a typo here:

https://github.com/arq5x/gemini/blob/master/gemini/config.py#L61

all `annotationdir` should be `annotation_dir`

I made the change and is working nicely now.

do you think this is the error?

**Comment by brentp** [comment]
Assigning @chapmanb in hopes that he'll address this. :-)

**Comment by chapmanb** [comment]
Lorena and Brent;
Apologies about the problem and thanks for the heads up. This was confusing as we had two arguments for annotation-dir, one global and one local to the update function, with different argument names (annotation-dir vs annotation). I removed the update specific one to get rid of the mess so this should work in the latest development.

Brent -- sorry shaking out a bunch of bugs I missed in the 0.18.0 update. My apologies. We should probably roll a point release soon after fixing #634 if that works with you.

**Comment by brentp** [comment]
Brad, no problem, thanks for looking into it! I have a 0.18.1 tag with most stuff (including this one) closed and then, yeah, we're ready for the next release.

**Comment by brentp** [comment]
when I do: python gemini_install.py ~/gemini_install/tools ~/gemini_install/data

I see:
```
/home/u6000771/gemini_install/data/anaconda/bin/gemini --annotation-dir /home/u6000771/gemini_install/data/gemini_data update --dataonly --tooldir /home/u6000771/gemini_install/tools
Upgrading associated tools...
Traceback (most recent call last):
  File "/home/u6000771/gemini_install/data/anaconda/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/home/u6000771/gemini_install/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1179, in main
    args.func(parser, args)
  File "/home/u6000771/gemini_install/data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1021, in update_fn
    gemini_update.release(parser, args)
  File "/home/u6000771/gemini_install/data/anaconda/lib/python2.7/site-packages/gemini/gemini_update.py", line 37, in release
    subprocess.check_call([sys.executable, _get_install_script(), config["annotation_dir"]] + extra_args)
KeyError: 'annotation_dir'
Traceback (most recent call last):
  File "gemini_install.py", line 184, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 81, in main
    install_rest(gemini, args)
  File "gemini_install.py", line 142, in install_rest
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/u6000771/gemini_install/data/anaconda/bin/gemini', '--annotation-dir', '/home/u6000771/gemini_install/data/gemini_data', 'update', '--dataonly', '--tooldir', '/home/u6000771/gemini_install/tools']' returned non-zero exit status 1
```

**Comment by chapmanb** [comment]
Brent;
It doesn't look like the latest gemini conda package has the fix yet. I didn't roll out a new one thinking 0.18.1 was on the horizon, but could do an update with the latest development version to get it going again. Sorry about all the problems caused by this one.

**Comment by brentp** [comment]
I updated it so that
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gemini/meta.yaml points to 3efc092
and
https://github.com/arq5x/gemini/blob/3efc0921da629d736eef85f914f3c654602149b3/gemini/config.py
includes your fixes.
Is it pulling from pypi somehow?

**Comment by brentp** [comment]
I also get an error from conda when I do:
```
conda install -c bioconda --file http://raw.githubusercontent.com/arq5x/gemini/master/versioning/0.18.0/requirements_conda.txt
```

**Comment by chapmanb** [comment]
Ah, I see. Your bioconda update didn't increase the build number so it didn't build a new package. If you bump that and push an update it should re-build and be okay.

Sorry about the versioning install issues. I'll have to look at that, I'm not super familiar with this aspect of conda so will have to learn.

**Comment by brentp** [comment]
cheers. that's my bad. I have a PR bumping the version running through CI stuff on bioconda/recipes now.
