### ISSUE TITLE
gemini update: trying to overwrite read-only files should raise an error

### ISSUE THREAD

**Issue by muraveill** [arq5x/gemini#634]
For a long time I "gemini updated" while having the wrong databases destination set (--annotationdir or the gemini-update.yaml). The destination folder was read-only and I got no warning (only a super-quick update process skipping everything as if already up-to-date).

An error should be raised if a database can be updated but the location cannot be written.

**Comment by brentp** [comment]
Assigning @chapmanb in hopes that he'll address this. :-)

**Comment by chapmanb** [comment]
Sorry about the issues. Silent failures are bad. I'm trying to replicate this but can't seem to do so. If I create a root-owned directory (`/usr/gemini-test`) I get permission errors trying to create the directories. If I create everything manually, I get a permission error when trying to write:
```
$ gemini --annotation-dir /usr/gemini-test update --dataonly
Traceback (most recent call last):
  File "/usr/local/share/bcbio_nextgen/anaconda/lib/python2.7/site-packages/gemini-0.18.0-py2.7.egg/gemini/install-data.py", line 165, in <module>
    install_annotation_files(args.anno_dir, args.dl_files, args.extra)
  File "/usr/local/share/bcbio_nextgen/anaconda/lib/python2.7/site-packages/gemini-0.18.0-py2.7.egg/gemini/install-data.py", line 94, in install_annotation_files
    os.makedirs(anno_dir)
  File "/usr/local/bin/../share/bcbio_nextgen/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/gemini-test/gemini/data'
```
So gemini seems to complain loudly for me. I'm probably misunderstanding your setup to replicate this correctly -- what does the destination folder look like, permissions wise, that gemini silently skips it? Thanks for the report and help debugging.

**Comment by muraveill** [comment]
It is most confusing indeed. I seem to still have path issues even after editing the yaml and --annotationdir. I think I will just remove everything and reinstall. Thanks for your time.
