### ISSUE TITLE
'' instead of None for inexistent VEP values

### ISSUE THREAD

**Issue by muraveill** [arq5x/gemini#639]
Empty values when reading from custom fields added through VEP (such as HGVSc and HGVSp) are represented by the empty string in the database. I think it could be safely replaced by NULL.

    sqlite> select vep_hgvsc,vep_hgvsp from variants where vep_hgvsp='' limit 10;
    |
    |
    |
    ...
    sqlite> select vep_hgvsc,vep_hgvsp from variants where vep_hgvsp is NULL;
    sqlite>

**Comment by jxchong** [comment]
Agreed, although currently GEMINI doesn't officially support the most recent versions of VEP that do HGVSc and HGVSp. GEMINI officially only supports up to VEP v75.

@brentp Whenever you get around to officially supporting VEP v83, this is an issue for all custom VEP fields that I've tested in VEP v82 and v83.

**Comment by brentp** [comment]
ok. this is news to me. any time you find something like this, an example VCF with no genotypes will be a great help. It will likely take me longer to update vep and annotate an example than it will to fix the bug-- so, yeah examples greatly appreciated.

**Comment by jxchong** [comment]
## VEP vcf made with VEP v82
	
	$ gemini load -v test.VEP.nogeno.vcf.gz -t VEP --cores 4 test.VEP.db
[test.VEP.nogeno.vcf.gz](https://github.com/arq5x/gemini/files/64759/test.VEP.nogeno.vcf.gz)

	$ gemini query -q "SELECT distinct(vep_gene_pheno) from variants" test.VEP.db
	$ gemini query -q "SELECT vep_hgvsc,vep_hgvsp from variants where vep_hgvsp='' limit 10" test.VEP.db

	$ gemini query -q "SELECT distinct(vep_gene_pheno) from variants" test.VEP.db
	
	None
	1	
	$ gemini query -q "SELECT vep_hgvsc,vep_hgvsp from variants where vep_hgvsp='' limit 10" test.VEP.db
	
	
	
	
	ENST00000327044.6:c.26+22C>T
	ENST00000379409.2:c.865-10A>C
	ENST00000379409.2:c.865-6A>C
	ENST00000491024.1:c.397+24A>G
	ENST00000379389.4:c.-33T>C
	ENST00000379370.2:c.5651+5C>T
	ENST00000354700.5:c.1407+4C>T
	$ gemini query -q "SELECT distinct(exon) from variants limit 10" test.VEP.db
	1/1
	
	None
	10/14
	13/14
	16/19
	10/19
	9/19
	4/12
	12/12

**Comment by brentp** [comment]
@jxchong and @muraveill so, I made some changes and now have:
```
$ gemini query -q "SELECT distinct(vep_gene_pheno) from variants" test.VEP.db
None
1
$ gemini query -q "SELECT vep_hgvsc,vep_hgvsp from variants where vep_hgvsp='' limit 10" test.VEP.db
$ gemini query -q "SELECT vep_hgvsc,vep_hgvsp from variants where vep_hgvsp is NULL limit 10" test.VEP.db
None	None
None	None
None	None
None	None
ENST00000327044.6:c.26+22C>T	None
ENST00000379409.2:c.865-10A>C	None
ENST00000379409.2:c.865-6A>C	None
ENST00000491024.1:c.397+24A>G	None
ENST00000379389.4:c.-33T>C	None
ENST00000379370.2:c.5651+5C>T	None
```

Does that look sensible? I'm

**Comment by jxchong** [comment]
Works for me

**Comment by brentp** [comment]
Thanks guys, this will be in 0.18.1
