### ISSUE TITLE
Splice regions with amino acid changes?

### ISSUE THREAD

**Issue by nfarzaneh** [arq5x/gemini#640]
Hello, 

I noticed that some of my impacts are labelled as splice_regions, even though they have an amino acid change associated with it.  Shouldn't they be labelled as either splice_donor/acceptor instead of splice_region?

I attached a list which shows examples of this.  It is quite common within the data set actually, which makes me believe that it could be a potential bug.

Here is my query:  gemini query --header -q "SELECT * FROM variant_impacts WHERE impact = 'splice_region' AND (NOT aa_change = 'None')"

Thank you for looking into this!
Nima Farzaneh

[splice_regions.txt](https://github.com/arq5x/gemini/files/63032/splice_regions.txt)

**Comment by brentp** [comment]
could you paste the original VCF record for a couple of those? no genotypes needed

**Comment by nfarzaneh** [comment]
It's very odd.  I can not reproduce my error.  I know that there has been some changes in versions over time; so there was probably some sort of inconsistency in my dataset.  I apologize for any inconvenience.  It seems to be working now.

**Comment by brentp** [comment]
no problem. that's good to hear. we are glad to get bug reports (especially when accompanied by example VCFs).
