### ISSUE TITLE
Update ClinVar VCF

### ISSUE THREAD

**Issue by dgaston** [arq5x/gemini#641]
Looks like we should update the version of the ClinVar VCF being used for annotations. I noticed this because I am doing work on clinical specimens previously tested with other methods getting our clinical NGS pipeline operational and have come across variants annotated with a clinical significance of "other" in the 20150305 release that have been updated to pathogenic in newer versions. In this case the variant has always been pathogenic (since 2007 I believe) but ClinVar has had some issues with their VCFs and sorting things into the right categories.

**Comment by arq5x** [comment]
Awesome, Brent. Just a reminder to set the correct S3 permissions for the .gz and .gz.tbi file as I always forget to do so.

**Comment by brentp** [comment]
yep. doing a full install to check everything.
