### ISSUE TITLE
only-affected vs. allow-unaffected

### ISSUE THREAD

**Issue by TorHou** [arq5x/gemini#650]
It would be nice to make mendel_errros consistent with the other tools and change the
'--only-affected' flag to the otherwise used
'--allow-unaffected'

**Comment by arq5x** [comment]
Well, they are named differently because they have different behavior. --allow in an inclusion whereas --only is an exclusion of unaffected individuals in this tool.

**Comment by TorHou** [comment]
I understand. 
I'm just thinking, that because you have a default setting of False for both flags, then for most tools you would not get the unaffected candidates and for mendel_errors you would get them. Of course it's not a major problem but it might confuse a few users.
