### ISSUE TITLE
Use the built in analysis tools from python API

### ISSUE THREAD

**Issue by moonso** [arq5x/gemini#659]
Hello,

is there any way to use the built in [tools](http://gemini.readthedocs.org/en/latest/content/tools.html) from the python API?
I can not find anything in the [documentation](http://gemini.readthedocs.org/en/latest/content/api.html) .
If not what would be the best way, can you help out to point to the source code where these are implemented?

Thanks

**Comment by brentp** [comment]
the source for these is here: https://github.com/brentp/inheritance
you can use via python via that module, but not through gemini, you just have to use our encoding for HOM_REF=0, HET=1, UNKNOWN=2, HOM_ALT=3

**Comment by moonso** [comment]
Ok nice!
Any suggestion on how i would get for example all compound hets in my gemini database for a particular family from within python by using this?

**Comment by brentp** [comment]
For everything but comp_hets, you can just run python -m inheritance (https://github.com/brentp/inheritance/blob/master/inheritance/__main__.py). I haven't go around to comp_hets yet. For comp_hets, it's best just to use the tool that's built in to gemini.

**Comment by moonso** [comment]
Ok, from what I can see this tool finds the models in vcf files but I need to search for variants that follow the models in gemini databases...

**Comment by brentp** [comment]
the inheritance module is what gemini uses. 
If you want to use these within gemini, then see: https://github.com/arq5x/gemini/blob/master/gemini/gim.py#L289-L437

You'll have to call the constructor with an args object that has attributes for db, families, etc. You can infer these from the arguments requested for the appropriate tool arg parsing in gemini_main.py 
All of them have these: https://github.com/arq5x/gemini/blob/master/gemini/gemini_main.py#L8-L67

**Comment by moonso** [comment]
Thanks alot!

**Comment by brentp** [comment]
I'm going to close this for now. Let us know if you have any further questions or any issues using gemini in this manner.
