### ISSUE TITLE
Sample-level information for SVs

### ISSUE THREAD

**Issue by vasiliosz** [arq5x/gemini#661]
I have loaded some gemini databases with multiple samples analyzed with lumpy or other tools. When querying this, I realised there is no real way of getting back which sample(s) the SV event was detected in. Or am I missing something? 

Adding `--show-samples` does not produce anything. I suspect this is because lumpy and other tools do not produce a GT field (leaves it `./.`). 

In the multi-sample VCF, there are however additional FORMAT fields specific to SVs (`SU`,`PE`,`SR`) that will inform which sample has read support for the SV. But these are not loaded at the sample-level in gemini, as I understand.

Ex, here the SV is present in the second sample: 

```
GT:SU:PE:SR     ./.:0:0:0       ./.:4:2:2       ./.:0:0:0       ./.:0:0:0       ./.:0:0:0       ./.:0:0:0       ./.:0:0:0       ./.:0:0:0 
```

More in general, what approach do you suggest for SV analysis in gemini?
Ideally, I would want to merge SNVs and SVs in the same database.

**Comment by brentp** [comment]
you will have to genotype your structural variants using svtyper (https://github.com/hall-lab/svtyper) in order to use them in gemini.

**Comment by vasiliosz** [comment]
Ah, thanks!
