### ISSUE TITLE
HPC gemini problem: writing to config files

### ISSUE THREAD

**Issue by bgruening** [arq5x/gemini#662]
We found a problem on our cluster where gemini tries to write into `gemini-config.yaml` during `update`.

```gemini --annotation-dir /data/3/galaxy_db/job_working_directory/000/247/247810/dataset_365217_files update --dataonly --extra gerp_bp --extra cadd_score```

I guess it's trying to write the annoation_dir into the yaml file. If this happens on a read-only cluster node this is causing the following error:

```
IOError: [Errno 13] Permission denied: '/usr/local/tools/gemini/0.18.1/iuc/package_gemini_0_18_1/b90d6db50590/gemini-config.yaml'
```

Can we add a check before we write and issue a warning if we can not update the `yaml` file?

**Comment by brentp** [comment]
CC @chapmanb @roryk

**Comment by chapmanb** [comment]
Björn -- thanks for the report. Apologies, we hadn't considered this case. I pushed a fix which checks for write permissions and skips writing if it's read only. Hope this works for your system setup. Thanks again.

**Comment by bgruening** [comment]
@chapmanb thanks a lot!
