### ISSUE TITLE
gemini windower

### ISSUE THREAD

**Issue by TorHou** [arq5x/gemini#673]
gemini windower doesn't work. I used "gemini update" to get the latest version but on my test data I get the error:

> Command was:
> 
> bedtools map -o mean -c 4 -b .temp.12012 -a /tmp/tmp7NzDcG/tmp/pybedtools.X3t3_E.tmp
> 
> Error message was:
> 
> *****
> ***** ERROR: Requested column 4, but database file /tmp/tmp7NzDcG
/tmp/pybedtools.X3t3_E.tmp only has fields 1 - 3.

**Comment by brentp** [comment]
can you give the command that you ran?

**Comment by arq5x** [comment]
I think this arises from a specific version(s) of bedtools

**Comment by TorHou** [comment]
I can run 'test-windower.sh' in the test folder to get this message on every test.

I thought everything was contained in the conda install. I'm using bedtools version v2.21.0, so I guess that is the problem then.

**Comment by TorHou** [comment]
it works with v2.25.0
