### ISSUE TITLE
gemini annotate float error

### ISSUE THREAD

**Issue by davetang** [arq5x/gemini#676]
```
gemini annotate -f exome.vt.vep.vcf.gz -o list -e AF -t float exome.vt.vep.db
updated 100000 variants
Non float value found in annotation file: 0.021,0.058

gemini query -q 'select variant_id,AF from variants where AF is null limit 2' --header *.db
variant_id      AF
100001  None
100002  None
```

When I manually checked the variant at line 100001 in the VCF file, the AF has a single value: ;AF=0.208; and so does variant 100002: ;AF=0.34;. The AF of variant 100000 is stored correctly in the database, ;AF=0.118;. I'm not sure where the 0.021,0.058 came from. It was just a bit suspicious that the error occurred on line 100,001.

I'm getting the same error with VQSLOD.

```
gemini annotate -f exome.vt.vep.vcf.gz -o list -e VQSLOD -t float exome.vt.vep.db
updated 100000 variants
Non float value found in annotation file: -0.0946,-1.352
```

**Comment by brentp** [comment]
did you run vt decompose on `exome.vt.vep.vcf.gz`

**Comment by davetang** [comment]
Yep.

`vt decompose -s $VCF | vt normalize -r $GENOME - | gzip > $BASE.vt.vcf.gz`

**Comment by davetang** [comment]
I get the same error with the UK10K VCF file.

```
wget -c ftp://ngs.sanger.ac.uk/production/uk10k/UK10K_COHORT/REL-2012-06-02/UK10K_COHORT.20140722.sites.vcf.gz

VCF=UK10K_COHORT.20140722.sites.vcf.gz
GENOME=human_g1k_v37.fasta.gz
BASE=`basename $VCF .vcf.gz`

vt decompose -s $VCF | vt normalize -r $GENOME - | gzip > $BASE.vt.vcf.gz

perl ~/src/ensembl-tools-release-82/scripts/variant_effect_predictor/variant_effect_predictor.pl -i $BASE.vt.vcf.gz -o $BASE.vt.vep.vcf --vcf \
--offline --cache --sift b --polyphen b --symbol --numbers --biotype --total_length \
--fields Consequence,Codons,Amino_acids,Gene,SYMBOL,Feature,EXON,PolyPhen,SIFT,Protein_position,BIOTYPE

gemini load -v $BASE.vt.vep.vcf -t VEP --cores 8 $BASE.vt.vep.db

tabix -p vcf UK10K_COHORT.20140722.sites.vt.vep.vcf.gz

gemini annotate -f UK10K_COHORT.20140722.sites.vt.vep.vcf.gz -o list -e VQSLOD -t float UK10K_COHORT.20140722.sites.vt.vep.db

Non float value found in annotation file: 4.5487,4.5487

gemini -v
gemini 0.18.1
```

**Comment by brentp** [comment]
Thanks for the full example! I'll have a look at how to handle this better. Note that for this case. VQSLOD is type=Float,Number=1, and so it violates the VCF spec by having `4.5487,4.5487` in that field.

**Comment by davetang** [comment]
No problems. But what I was initially reporting is that `4.5487,4.5487` doesn't exist in the file.

```
zcat UK10K_COHORT.20140722.sites.vt.vep.vcf.gz | grep "4.5487,4.5487"
# returns nothing
```

In my first example, `0.021,0.058` and `-0.0946,-1.352` aren't found in the VCF file either. I also checked all the fields in that VCF file and they all have single values.

**Comment by brentp** [comment]
understood. I'll have a look this week. I tagged this for 0.18.3 so we'll have a fix soon.

**Comment by brentp** [comment]
for my own record, I'm testing on:

```
wget -O -$url \
    | zcat - | head -100000 \
    | vt decompose -s - \
    | vt normalize -r /data/human/hs37d5.fa - \
    | grep -v "ID=CSQ" | perl -pe 's/CSQ[^;]+//' \
    | bgzip -c > uk100k.vcf.gz
```

then vep annotate then : 

```
tabix uk100k.vep.vcf.gz
gemini load --cores 4 -v uk100k.vep.vcf.gz -t VEP --no-genotypes uk100k.db
```

annotate:

```
gemini annotate -f uk100k.vep.vcf.gz -o list -e VQSLOD -t float uk100k.db
```

**Comment by brentp** [comment]
There are some interesting things in that VCF. For example:
```
1	2942599	.	A	ATGG
```
occurs twice but with different values in the info field.

**Comment by brentp** [comment]
@davetang I just pushed a fix for this that will be out in the next release. You can get it meanwhile with:

```
gemini_pip install git+https://github.com/arq5x/gemini.git
```
