### ISSUE TITLE
VCF loaded with --no-genotype: ImportError: No module named gemini_inheritance_model_utils

### ISSUE THREAD

**Issue by brainstorm** [arq5x/gemini#678]
After loading some VCF's from ICGC, the data gets loaded into the Gemini DB but the Gemini browser does not work show up (am I missing the installation of some plugin/additional library?):

```
$ gemini browser test.db
Traceback (most recent call last):
  File "/Users/romanvg/.anaconda/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/Users/romanvg/.anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1177, in main
    args.func(parser, args)
  File "/Users/romanvg/.anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 906, in browser_fn
    import gemini_browser
  File "/Users/romanvg/.anaconda/lib/python2.7/site-packages/gemini/gemini_browser.py", line 6, in <module>
    from gemini_inheritance_model_utils import GeminiInheritanceModelFactory
ImportError: No module named gemini_inheritance_model_utils

$ gemini --version
gemini 0.18.1
```

**Comment by brentp** [comment]
The browser has been deprecated (or at least suffered too much bitrot).
I'll have a look at restoring the functionality for the next release.

**Comment by dgaston** [comment]
If anyone is interested, at one point I was working on a larger web-based program that kept some project-level data and project management features but it also included a specialized interface to a GEMINI database with a form-based query interface. It may or may not be functional at the moment, and I haven't developed installation documentation but you can find the project here: https://github.com/dgaston/kvasir

I would be happy to revisit this project and develop it further if there is interest. It allowed for integration of gene lists for filtering but I would need to update with some of the newer GEMINI features, like the Phenotype integrations.

**Comment by brainstorm** [comment]
I was actually exploring the builtin browse functionality on GEMINI and looking for integrations with Puzzle:

https://github.com/robinandeer/puzzle

Thanks @brentp for reporting the current state of GEMINI's browser!

@robinandeer @moonso @guillermo-carrasco @ohofmann

**Comment by brentp** [comment]
It looks like the changes to fix the browser are minimal. I'll have a look this week.

@dgaston that seems very interesting. Do you have some screenshots?

**Comment by yanickpouliot** [comment]
I'd be most interested in having this problem fixed! Kind of a mark on such a fine system :-)

**Comment by brainstorm** [comment]
Solved in PR #683, feel free to give it a try now that [puzzle](https://github.com/robinandeer/puzzle) is the default GEMINI browser! ;)

**Comment by yanickpouliot** [comment]
Very cool! Thx for fixing!

One problem: the gemini example ("puzzle --mode gemini view -i path/to/gemini_database.db") in https://github.com/robinandeer/puzzle fails. 

According to puzzle --help, there is no "mode" command. Some sort of version problem? I'm running 0.0.1...

**Comment by moonso** [comment]
Hello @yanickpouliot , there has been rapid development of puzzle lately and the docuentation was lagging. It is now updated, you can try `puzzle view --mode gemini path/to/gemini.db`.

**Comment by yanickpouliot** [comment]
Thx much! I think I'm there... Thx again.
