### ISSUE TITLE
limit auto_* tools to autosomal chromosomes

### ISSUE THREAD

**Issue by brentp** [arq5x/gemini#690]
we'll have to figure out how to do this generally since we'll be supporting other species soon.

**Comment by brentp** [comment]
I'm going to close this since it's simple to add `... AND not chrom in ('X', 'Y')` to the query.

**Comment by arq5x** [comment]
should we just add that to the internal query?

**Comment by brentp** [comment]
poses problems with organisms that don't have X and/or Y for sex chromosomes.

**Comment by arq5x** [comment]
True, but couldn't we just have a CL argument through which they specify what the sex chroms are if they really care to filter them out?
