### ISSUE TITLE
some test issues with 2f4b777bf18ea

### ISSUE THREAD

**Issue by roryk** [arq5x/gemini#694]
Running master-test.sh:

```
  File "/n/home05/kirchner/miniconda/envs/bcbio/lib/python2.7/site-packages/gemini-0.18.3-py2.7.egg/gemini/annotations.py", line 808, in get_exac_info
    num_hets = int(info_map.get("AC_Het", -1))
ValueError: invalid literal for int() with base 10: '13904,285,15,24,22,2,71,5,153,6,2,0,0,0,0,0,0,0,0,0,0'
```

**Comment by arq5x** [comment]
@brentp - are you able to replicate these?

**Comment by brentp** [comment]
I didn't see this til now. but no, I'm not able to replicate. What test or load is failing?

**Comment by brentp** [comment]
I think you might have a stale ExAC vcf. can you check that you get md5sum for your 93a4393680c0fb8f9c4e5ffbef755bae  ExAC.r0.3.sites.vep.tidy.vcf.gz ?

**Comment by brentp** [comment]
closing this for now. please reopen if you still see the issue.
