### ISSUE TITLE
best may to get x-linked variants

### ISSUE THREAD

**Issue by timmo2003** [arq5x/gemini#695]
I'm new to using gemini, and used it to identify de novo, and autosomal recessive variants in our ~200 families. In your documents you mention to you can get X chromosome variants using the gt-filter tool, but is there a may to identify variants that are hemizygous in the child and heterozygous in the mother.

Thanks for your time, and great tool (which has saved we lots of time!).

Andrew

**Comment by brentp** [comment]
We have X-linked recessive and dominant coming in the next release. The logic and tests are implemented in the inheritance module, we just need to incorporate into gemini. I think this will be in the next couple of weeks.

**Comment by timmo2003** [comment]
great, thanks for letting me know.

Andrew

**Comment by brentp** [comment]
x-linked dominant, recessive, and de novo are now in master. They'll be in the next release.
