### ISSUE TITLE
Feature Request: pull VCF header into database

### ISSUE THREAD

**Issue by davemcg** [arq5x/gemini#697]
It'd useful if the header lines (grep "^##" your.vcf) of the VCF could be stored in gemini. There's useful information there with the GATK workflow about the exact settings used for the various tools. Since I'm using a python wrapper to query Gemini and export a xlsx file, I'd like to be able to pull the VCF header and stick (some of it) it in a worksheet for diagnostics. Of course I could just pull from the VCF itself, but having in the Gemini DB would make it less prone to mistakes and easier to script. 

- D

**Comment by arq5x** [comment]
Thanks! We already have a table called vcf_header:
https://github.com/arq5x/gemini/blob/master/gemini/database.py#L336
that is loaded here:
https://github.com/arq5x/gemini/blob/2f4b777bf18ea31497424b78853d492112f08112/gemini/gemini_load.py#L64
Have you looked into using that?

**Comment by davemcg** [comment]
I suspected you already had something...just couldn't find it. I bet that'll be perfect.

**Comment by davemcg** [comment]
Yep, SELECT * FROM vcf_header is exactly what I wanted!

**Comment by arq5x** [comment]
Great, sorry it is not well documented.
