### ISSUE TITLE
Error doing a fresh install of GEMINI

### ISSUE THREAD

**Issue by nfarzaneh** [arq5x/gemini#698]
Hello Aaron/Brent,

I get an error when I try to do a fresh install of GEMINI:

Error: MD5 sums mismatch for download: https://conda.binstar.org/bcbio/linux-64/python-graph-core-1.8.2-py27_1.tar.bz2 (ce43afe12ff58ce52346347f6db92a27 != 1a43067a8d71aa88a09b27830923e933)

Thanks,
Nima Farzaneh

**Comment by brentp** [comment]
Hi Nima, things haven't changed with that for some time, so maybe it's a network issue? Can you remove any traces of the install and try again?

**Comment by nfarzaneh** [comment]
Hello Brent,

When I download directly from the source, it gives me an MD5SUM of ce43afe12ff58ce52346347f6db92a27, which I think is not what it is expecting?

Thanks,
Nima

**Comment by brentp** [comment]
@chapmanb any ideas?

**Comment by chapmanb** [comment]
Nima;
Sorry about the install problems. How are you trying to run it? I'm concerned that you're pulling from the older `bcbio` anaconda.org repository, which we don't want since everything has moved to the bioconda project. You'd want to remove bcbio from your `~/.condarc` file if it's there and ideally use the automated installer:

http://gemini.readthedocs.org/en/latest/#new-installation

Happy to help debug more with more details about the installation approach and environment. Thanks again for reporting.

**Comment by nfarzaneh** [comment]
Hello Brad,

Thanks a lot for looking into this.  I was not able to find ~/.condarc on my system.  Here is the complete command/error:

python gemini_install.py /home/nfarzaneh/software/gemini/tools/ /home/nfarzaneh/software/gemini/data/
[...]
Error: MD5 sums mismatch for download: https://conda.binstar.org/bcbio/linux-64/python-graph-core-1.8.2-py27_1.tar.bz2 (ce43afe12ff58ce52346347f6db92a27 != 1a43067a8d71aa88a09b27830923e933)
Traceback (most recent call last):
  File "gemini_install.py", line 410, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 91, in main
    install_conda_pkgs(anaconda, remotes, args)
  File "gemini_install.py", line 174, in install_conda_pkgs
    subprocess.check_call([anaconda["conda"], "install", "--yes"] + channels + pkgs)
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/nfarzaneh/software/gemini/data/anaconda/bin/conda', 'install', '--yes', '-c', 'https://conda.binstar.org/bcbio', 'conda', 'cython', 'ipython', 'jinja2', 'nose', 'numpy', 'openssl', 'pip', 'pycrypto', 'pyparsing', 'python-graph-core', 'python-graph-dot', 'pyyaml', 'pyzmq', 'pandas', 'scipy', 'bx-python', 'pysam', 'ipython-cluster-helper']' returned non-zero exit status 1

Let me know if you need any other information.

Kind regards,
Nima

**Comment by chapmanb** [comment]
Nima;
It seems like you have an old version of the `gemini_install.py` script. Could you try getting the latest:

https://raw.githubusercontent.com/arq5x/gemini/master/gemini/scripts/gemini_install.py

and re-running. Sorry about the confusion and hopefully the up to date version will work cleanly for you

**Comment by nfarzaneh** [comment]
Excellent!  That fixed it!

Thanks a lot for your quick response and help.

Nima

**Comment by nfarzaneh** [comment]
Sorry to open this again, but now I am getting a different error now when I try to update gemini after doing a successful data install.  Also master-test.sh never showed up anywhere on my system so I was not able to test the install:

Checking required dependencies...
 wget found
Installing isolated base python installation
Installing base gemini package...
/home/nfarzaneh/software/gemini/data/anaconda/bin/conda install --yes -c bioconda gemini
Fetching package metadata: ......
Solving package specifications: .........

# All requested packages already installed.
# packages in environment at /home/nfarzaneh/software/gemini/data/anaconda:
#
gemini                    0.18.3                   py27_1    https://conda.binstar.org/bioconda/linux-64/gemini-0.18.3-py27_1.tar.bz2
/home/nfarzaneh/software/gemini/data/anaconda/bin/gemini --annotation-dir /home/nfarzaneh/software/gemini/data/gemini_data update --dataonly --tooldir /home/nfarzaneh/software/gemini/tools
Traceback (most recent call last):
  File "/home/nfarzaneh/software/gemini/data/anaconda/bin/gemini", line 3, in <module>
    import gemini.scripts
  File "/home/nfarzaneh/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/__init__.py", line 4, in <module>
    from GeminiQuery import GeminiQuery
  File "/home/nfarzaneh/software/gemini/data/anaconda/lib/python2.7/site-packages/gemini/GeminiQuery.py", line 15, in <module>
    import sqlalchemy as sql
ImportError: No module named sqlalchemy
Traceback (most recent call last):
  File "gemini_install.py", line 190, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 81, in main
    install_rest(gemini, args)
  File "gemini_install.py", line 148, in install_rest
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/nfarzaneh/software/gemini/data/anaconda/bin/gemini', '--annotation-dir', '/home/nfarzaneh/software/gemini/data/gemini_data', 'update', '--dataonly', '--tooldir', '/home/nfarzaneh/software/gemini/tools']' returned non-zero exit status 1

Any help would be much appreciated again!  Thanks for such a great tool.

Thanks,
Nima

**Comment by brentp** [comment]
Just pip install sqlalchemy. We'll fix this dependency soon.
