### ISSUE TITLE
CADD scores wrong?

### ISSUE THREAD

**Issue by davemcg** [arq5x/gemini#699]
Very confused here. 

Running Gemini 0.18

The CADD scores are....not right. Some end users pointed out to me at a meeting that they were getting different CADD scores when they used the CADD website (http://cadd.gs.washington.edu/score). I hand checked four variants and they differ between Gemini and the CADD site.

Gemini Query:
```
gemini query -q "select chrom, end, rs_ids, ref, alt, cadd_scaled, cadd_raw from variants where hwe < 0.01" --header mygemini.db | less -S
...
# four variants I grabbed near the top
chrom   end     rs_ids  ref     alt     cadd_scaled     cadd_raw
chr1    1266738 rs76755863      G       A       14.61   2.59
chr1    1266740 rs141430443     T       A       8.16    0.79
chr1    1273278 rs307370        A       G       9.73    1.16
chr1    1277649 rs146525333     G       T       2.77    -0.26
```

I send those four variants from the query to the CADD site and got these values:
```
#Chrom	Pos	Ref	Alt	RawScore	PHRED
1	1266738	G	A	1.335746	12.45
1	1266740	T	A	0.247220	5.169
1	1273278	A	G	0.219953	4.888
1	1277649	G	T	-0.108795	1.665
```

Checking against the CADD scores directly (http://krishna.gs.washington.edu/download/CADD/v1.3/ExAC_r0.3.tsv.gz) gave the same results as the CADD site.

**Comment by brentp** [comment]
We use CADD v1 in gemini: try: http://krishna.gs.washington.edu/download/CADD/v1.0/ExAC_r0.3.tsv.gz

when I select cadd V1.0 instead of the default of v1.3 from the website, I see:

```
#CHROM	POS	REF	ALT	RawScore	PHRED
1	1266738	G	A	2.587031	14.61
1	1266740	T	A	0.789246	8.16
1	1273278	A	G	1.161846	9.729
1	1277649	G	T	-0.256824	2.766
```

**Comment by davemcg** [comment]
Ah, I see. Thanks.
