### ISSUE TITLE
Use a more portable blob format for genotypes

### ISSUE THREAD

**Issue by jdelafon** [arq5x/gemini#700]
Currently, genotype arrays are compressed Python pickle objects. This is unfortunate as it prevents reading the content from anything but Python. Also, consider that the pickle protocol can be a security hole (one can execute arbitrary code from a malformed VCF).

Since the pickled objects are simple arrays, why not use a portable format like JSON instead ? Or even, for an array, "to string" is a `join`, and "from string" is a `split`. That would probably be (much) faster and can be zipped just as well.

**Comment by brentp** [comment]
in the [new loader to gemini](https://github.com/quinlan-lab/vcf2db) we have the option to expand out the genotype columns into separate tables. We have also considered using blosc: https://github.com/quinlan-lab/vcf2db/blob/169b6c57078bc7aab8e5eb664449b263d20d9951/vcf2db.py#L83-L87
but that would be a burden to maintain for backward compat so it's still under consideration, even though it's quite a bit faster. I'll leave this open to benchmark using comma-delimited.

**Comment by muraveill** [comment]
I did the benchmark for you. It is definitely faster to avoid pickling for such simple objects. 
N.B. I am using Python3 (i.e. cPickle became pickle, and one needs to cast to/from bytes before/after compression) :

    In [58]: %paste
    import random
    from timeit import timeit
    try:
        import cPickle as pickle
    except:
        import pickle


    def zdumps(obj):
        return zlib.compress(pickle.dumps(obj, pickle.HIGHEST_PROTOCOL), 9)

    def zloads(obj):
        return pickle.loads(zlib.decompress(obj))

    def xdumps(obj):
        return zlib.compress(bytes(','.join(map(str,obj)), 'UTF-8'))

    def xloads(obj):
        return zlib.decompress(obj).decode('UTF-8').split(',')

    a = [random.randint(0,10) for _ in range(1000)]


    %time b = zdumps(a)
    %time c = xdumps(a)
    %time d = zloads(b)
    %time e = xloads(c)

    ## -- End pasted text --
    CPU times: user 233 µs, sys: 36 µs, total: 269 µs
    Wall time: 274 µs
    CPU times: user 428 µs, sys: 23 µs, total: 451 µs
    Wall time: 478 µs
    CPU times: user 100 µs, sys: 22 µs, total: 122 µs
    Wall time: 148 µs
    CPU times: user 89 µs, sys: 21 µs, total: 110 µs
    Wall time: 116 µs

**Comment by brentp** [comment]
thanks, here is what I get:
```
In [13]: %timeit xdumps(a)
The slowest run took 5.38 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 158 us per loop

In [14]: %timeit zdumps(a)
10000 loops, best of 3: 95.1 us per loop

In [15]: %timeit xloads(bx)
The slowest run took 5.32 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 25.8 us per loop

In [16]: %timeit zloads(bz)
The slowest run took 4.07 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 30 us per loop

In [17]: len(bz)
Out[17]: 707

In [18]: len(bx)
Out[18]: 700
```

the ',' delimited string should compress better for real genotype and depth data.

**Comment by muraveill** [comment]
Yes. Only loading performance matters, I suppose, and a 14-22% improvement when iterating over millions of variants is good to take (and solves the portability/security issue).

As for the dumping time, I don't understand why it increases, but one could use `str(x).strip('[]')` instead (is it that ugly?). The string representation of lists is not going to change soon.

**Comment by brentp** [comment]
zlib.compress(a.tobytes()) is portable and extremely fast for both encoding and decoding. We'll need extra metadata indicating the type of the serialized array (float/int64/etc), but this is likely what I'll go with barring any unforeseen problems.

It is 6X faster for encoding 50 ints in (0, 3) compared to zlib.compress(pickle.dumps())
The resulting string is almost 3x shorter.

On that same set, it is 6X faster to de-serialize. That could have a real impact on the speed in gemini.

**Comment by brentp** [comment]
```python
import numpy as np
import zlib
import cPickle

L=zlib.Z_BEST_SPEED
L = 5

a = np.random.randint(3, size=50)

print "SERIALIZE"
print "binary:"
%timeit zlib.compress(a.tobytes(), L)
ab = zlib.compress(a.tobytes(), L)
print "len:", len(ab)

print "pickle:"
%timeit zlib.compress(cPickle.dumps(a, cPickle.HIGHEST_PROTOCOL), L)
ap = zlib.compress(cPickle.dumps(a, cPickle.HIGHEST_PROTOCOL), L)
print "len:", len(ap)


print "DESERIALIZE:"
print "binary:"
%timeit np.fromstring(zlib.decompress(ab), dtype=int)

print "pickle:"
%timeit cPickle.loads(zlib.decompress(ap))
```

**Comment by muraveill** [comment]
Indeed, this is what I use for saving arrays to a Redis cache. Note that it loses portability again - but for my own application I would be absolutely happy with that solution.

**Comment by brentp** [comment]
I added blosc as well for uint8 (gt_types) it is about 2x as fast for decompressing as the binary.
For uint32 (depths) it is 4-5x as fast. so much much faster than the current cPickle.

I'm leaning toward binary format for simplicity, but 2-5X is hard to ignore.

**Comment by muraveill** [comment]
The thing that made me write this issue is that I tried something in Scala... Unfortunately blosc has no Java/Scala wrapper. Still, for that kind of improvement I would go for blosc all the way. It is also rather easy I think to propose both alternatives for portability, detecting the format when reading the first element, and always using blosc internally.

**Comment by brentp** [comment]
closing as this has gone both into vcf2db and gemini master. the new format (snappy compression of the binary) is much faster *and* much smaller than the current format. It's "portable" to anything language that has snappy bindings.
