### ISSUE TITLE
master-test.sh fail on 0.18.3

### ISSUE THREAD

**Issue by Vaidhy-M** [arq5x/gemini#701]
I installed a fresh copy of Gemini 0.18.3 on Linux Mint 17 using the automated installation option. When I ran master-test.sh it failed throwing out this message earlier, 

> Requested GEMINI database (test.query.core.db) not found. Please confirm the provided filename.

While running the test it also says bgzip not found.

Please suggest a fix.

**Comment by brentp** [comment]
can you show the full output of running master-test.sh

**Comment by Vaidhy-M** [comment]
please tell me if this is sufficient. thank you!

[gemini.txt](https://github.com/arq5x/gemini/files/224875/gemini.txt)

**Comment by brentp** [comment]
why isn't the output of data-setup.sh present in the file?

**Comment by Vaidhy-M** [comment]
Hey, turns out tabix wasn't installed and once I did that it ran the whole test. I am attaching the output of the same. It does say that 

> skiping windower tests since we can't find bedtools

Could you please tell me if this is alright? Thanks!
[out.txt](https://github.com/arq5x/gemini/files/226189/out.txt)

**Comment by brentp** [comment]
looks fine to me.

**Comment by Vaidhy-M** [comment]
great. thanks!
