### ISSUE TITLE
Variant impacts - ranking

### ISSUE THREAD

**Issue by nfarzaneh** [arq5x/gemini#703]
Hello All,

When I run this query for one of my databases:

gemini query --header -q "SELECT variant_id,gene,transcript,impact,impact_severity FROM variants WHERE variant_id = 7602576" *.db

I get this:

variant_id	gene	transcript	impact	impact_severity
**7602576	LZTR1	ENST00000389355	synonymous_variant	LOW**
But when I check to see all the alternates:

gemini query --header -q "SELECT variant_id,gene,transcript,impact,impact_severity FROM variant_impacts WHERE variant_id = 7602576" *.db

I get this:

variant_id	gene	transcript	impact	impact_severity
7602576	AIFM3	ENST00000335375	downstream_gene_variant	LOW
7602576	AIFM3	ENST00000486003	downstream_gene_variant	LOW
**7602576	LZTR1	ENST00000443265	missense_variant	MED**
7602576	XXbac-B135H6.18	ENST00000610278	upstream_gene_variant	LOW
7602576	LZTR1	ENST00000389355	synonymous_variant	LOW
7602576	LZTR1	ENST00000215739	synonymous_variant	LOW
7602576	AIFM3	ENST00000483107	downstream_gene_variant	LOW
7602576	AIFM3	ENST00000465606	downstream_gene_variant	LOW
7602576	AIFM3	ENST00000333607	downstream_gene_variant	LOW
7602576	LZTR1	ENST00000414985	synonymous_variant	LOW
7602576	AIFM3	ENST00000440238	downstream_gene_variant	LOW
7602576	LZTR1	ENST00000480895	upstream_gene_variant	LOW
7602576	AIFM3	ENST00000399163	downstream_gene_variant	LOW
7602576	LZTR1	ENST00000493460	non_coding_exon_variant	LOW
7602576	AIFM3	ENST00000405089	downstream_gene_variant	LOW
7602576	AIFM3	ENST00000399167	downstream_gene_variant	LOW
7602576	LZTR1	ENST00000479606	non_coding_exon_variant	LOW

Why didn't the MED impact make it to the variant table?  I thought that GEMINI reports only the highest impact SNPs.

Let me know if you need any other information.

Thanks,
Nima

**Comment by brentp** [comment]
can you paste the CSQ from the VCF for that variant?

**Comment by nfarzaneh** [comment]
Hello Brent,

Here is the VCF file for that variant:

22	21337325	.	G	A	5602.73	.	AC=13;AF=0.203;AN=64;BaseQRankSum=-3.255;DP=1195;Dels=0;FS=6.835;HaplotypeScore=4.4141;InbreedingCoeff=-0.2549;MLEAC=13;MLEAF=0.203;MQ=59.97;MQ0=0;MQRankSum=1.167;QD=11.92;ReadPosRankSum=-0.209;CSQ=downstream_gene_variant|||ENSG00000183773|AIFM3|ENST00000335375||||-/586|protein_coding,downstream_gene_variant|||ENSG00000183773|AIFM3|ENST00000486003|||||retained_intron,missense_variant&NMD_transcript_variant|aGc/aAc|S/N|ENSG00000099949|LZTR1|ENST00000443265|2/7|unknown(0)||72/101|nonsense_mediated_decay,upstream_gene_variant|||ENSG00000272829|XXbac-B135H6.18|ENST00000610278|||||lincRNA,synonymous_variant|aaG/aaA|K|ENSG00000099949|LZTR1|ENST00000389355|2/20|||70/821|protein_coding,synonymous_variant|aaG/aaA|K|ENSG00000099949|LZTR1|ENST00000215739|2/21|||70/840|protein_coding,downstream_gene_variant|||ENSG00000183773|AIFM3|ENST00000483107|||||processed_transcript,downstream_gene_variant|||ENSG00000183773|AIFM3|ENST00000465606|||||processed_transcript,downstream_gene_variant|||ENSG00000183773|AIFM3|ENST00000333607||||-/598|protein_coding,synonymous_variant&NMD_transcript_variant|aaG/aaA|K|ENSG00000099949|LZTR1|ENST00000414985|2/8|||70/117|nonsense_mediated_decay,downstream_gene_variant|||ENSG00000183773|AIFM3|ENST00000440238||||-/605|protein_coding,upstream_gene_variant|||ENSG00000099949|LZTR1|ENST00000480895|||||processed_transcript,downstream_gene_variant|||ENSG00000183773|AIFM3|ENST00000399163||||-/598|protein_coding,non_coding_exon_variant&nc_transcript_variant|||ENSG00000099949|LZTR1|ENST00000493460|2/3||||retained_intron,downstream_gene_variant|||ENSG00000183773|AIFM3|ENST00000405089||||-/604|protein_coding,downstream_gene_variant|||ENSG00000183773|AIFM3|ENST00000399167||||-/605|protein_coding,non_coding_exon_variant&nc_transcript_variant|||ENSG00000099949|LZTR1|ENST00000479606|3/22||||processed_transcript

**Comment by brentp** [comment]
and can you send the CSQ def from the VCF header?

**Comment by nfarzaneh** [comment]
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence type as predicted by VEP. Format: Consequence|Codons|Amino_acids|Gene|SYMBOL|Feature|EXON|PolyPhen|SIFT|Protein_position|BIOTYPE">

**Comment by nfarzaneh** [comment]
Also, what does GEMINI do in case of a Tie between identical impact severities?

Nima

**Comment by brentp** [comment]
the biotype of the variant with MED impact is `nonsense_mediated_decay` we prioritize `protein_coding` as "coding" variants even though the impact is higher.

In the case of a tie. One is chosen arbitrarily.

**Comment by nfarzaneh** [comment]
Excellent.  Thanks for clarifying this!

If I understand correctly, there isn't a ranking between any biotypes other than protein_coding?  And in case there is a tie between two protein_coding, the highest impact is first chosen, then if there is still a tie, we randomly choose an impact which have the same biotype and same impact_severity?  Is this correct? 

Thanks!
Nima

**Comment by brentp** [comment]
The rules are listed here:
https://github.com/brentp/geneimpacts/#rules-for-severity

**Comment by brentp** [comment]
closing this for posterity. please re-open if you find other issues.
