### ISSUE TITLE
Is it possible to add hemizygous counts (AC_Hemi) as one of the columns?

### ISSUE THREAD

**Issue by nfarzaneh** [arq5x/gemini#710]
`##INFO=<ID=AC_Hemi,Number=A,Type=Integer,Description="Adjusted Hemizygous Counts">`

Would be great!

Thanks,
Nima

**Comment by arq5x** [comment]
I assume you are referring to ExAC?

**Comment by nfarzaneh** [comment]
Yes.

**Comment by arq5x** [comment]
Okay, thanks. We will keep this in mind for the new release which will leverage a new loading system that would allow new annotations (such as this) to be added relatively easily by the user via a simple configuration script for vcfanno (which will drive the columns that end up in the final GEMINI database).
https://github.com/brentp/vcfanno

**Comment by nfarzaneh** [comment]
Excellent thanks a bunch!
