### ISSUE TITLE
github_gemini directory not installed

### ISSUE THREAD

**Issue by mutundis** [arq5x/gemini#711]
Following the installation instructions at https://gemini.readthedocs.org/en/latest/content/installation.html#automated-installation I do this:

```
wget https://github.com/arq5x/gemini/raw/master/gemini/scripts/gemini_install.py
tools=/usr/local/gemini data=/Users/xxx/data/gemini # username obscured here
python gemini_install.py $tools $data
```
The script runs without error and at the end I get:

```
 Run tests with:
  cd /Users/xxx/data/gemini/github_gemini && bash master-test.sh

```
gemini runs OK:
```
~: export PATH=/usr/local/gemini/bin:$PATH
~: which gemini
/usr/local/gemini/bin/gemini
~: gemini -v
gemini 0.18.3
```
but the directory containing the testing script has not been created:
```
~: ls /Users/xxx/data/gemini/github_gemini
/opt/pkg/bin/gls: cannot access /Users/xxx/data/gemini/github_gemini: No such file or directory
```
I am using:

OS X El Capitan version 10.11.4

and:

Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin

**Comment by brentp** [comment]
This is a change to how gemini is installed. you'll have to clone the github
repo if you want to run the tests. I'll leave this open as a reminder to update the docs.
