### ISSUE TITLE
Harmonize sample_ids in sample_genotype_counts and in the sample table

### ISSUE THREAD

**Issue by lbeltrame** [arq5x/gemini#736]
I understand this is a "not really supported" scenario, but I found out that the `sample_genotype_counts` table and the `samples` table have different sample IDs (one is 0-based, the other is 1-based). 

This breaks when trying to make queries accessing the database directly (as on the why: my entire set of tools is Python 3 based, and I need to use things in a way that the GEMINI API is not suited for) because it's impossible to make a proper join on the sample table. 

Rationally it would be best to have a relationship between `sample_genotype_counts` and `samples` since it's 1:1 and let the database handle the rest when querying.

**Comment by brentp** [comment]
The sample_id in the sample_genotype_counts table was fixed in: ad743289 in march.

It appears that I re-corrected in gemini-stats using sample_id - 1. I'll have a look.

**Comment by brentp** [comment]
actually, seems like this is fixed completely in master. please reopen if you see otherwise.

**Comment by lbeltrame** [comment]
It may be an older version of GEMINI. I observed this with the (at the time) latest stable version of bcbio-nextgen. I'll update and check back.

**Comment by brentp** [comment]
yes, what you report was the case until  ad74328

**Comment by lbeltrame** [comment]
Just in case: is this already in a tagged version?

What I saw was with 

```
gemini --version
gemini 0.18.3
```

**Comment by brentp** [comment]
no. it's not released yet. we hope to release as version 0.19 next week.

**Comment by lbeltrame** [comment]
Hence this is the reason: I rely on what bcbio-nextgen provides, so I'm still affected. I'll add a FIXME in my code and upgrade once 0.19 is released.

**Comment by brentp** [comment]
understood. thanks for reporting.
