### ISSUE TITLE
Correct PED file format?

### ISSUE THREAD

**Issue by sndrtj** [arq5x/gemini#742]
Hi there,

In essentially all PED files there's at least one individual with unknown parents. Unfortunately, the [original](http://pngu.mgh.harvard.edu/~purcell/plink/data.shtml#ped) PED format documentation doesn't mention any guidelines for what to fill in the `maternal_id` and `paternal_id` fields in this case. The [documentation](https://www.cog-genomics.org/plink2/formats#fam) for plink2 is more clear, stating that those fields should contain a *0*. 

However, the gemini [documentation](http://gemini.readthedocs.io/en/latest/content/preprocessing.html) seems to suggest that the field should be *-9*, but [this issue](https://groups.google.com/forum/#!topic/gemini-variation/gkDc3R3Y6yg) uses 0. Yet another format is used by [varapp](https://varapp-demo.vital-it.ch/docs/src/method.html) - which uses gemini in its backend. This one uses simple empty tabs to indicate unknown parents. 

Three formats to indicate the very same concept is getting quite confusing. Does gemini prefer any of the three methods, and if so, which?

**Comment by roryk** [comment]
Hi @sndrtj,

It's super confusing for sure. GEMINI has a little bit to translate everything to `0` so `0` and `-9` and `None` will work. Here's all the fields that count as 'missing':

https://github.com/arq5x/gemini/blob/master/gemini/ped.py#L9

They get set to `0` here:

https://github.com/arq5x/gemini/blob/master/gemini/ped.py#L39

Hope that helps!

**Comment by roryk** [comment]
I updated the documentation with this information, thanks!

**Comment by sndrtj** [comment]
Hi @roryk 

Thanks for the super quick reply! 

I do think the `None` case is really dangerous when the file is not tab-delimited. For example:

```
>>> tabs = "fam01\tindividual_1\t\t\t2\t2"
>>> spaces = "fam01 individual_1   2 2"
>>> tabs.split("\t")
['fam01', 'individual_1', '', '', '2', '2']
>>> spaces.split()
['fam01', 'individual_1', '2', '2']
```

This would essentially mean the parser is going to think the sex and phenotype fields are parent IDs.

**Comment by brentp** [comment]
@sndrtj In the case you show, it will generate an error. We could add more defensive checks, but this method seems to work well in practice.
