### ISSUE TITLE
comp_hets - Surpress Warnings

### ISSUE THREAD

**Issue by AndrewSkelton** [arq5x/gemini#743]
Hi, 

When running the comp_hets tool, I seem to get quite a few warnings similar to the below:

`not phasing variant due to apparent de_novo in kid`

Is there a way to suppress these warnings? I tried setting `--max-priority` to 1, but the warnings still persist.

Thanks,

**Comment by brentp** [comment]
for now, these warnings can't be silenced. I'll leave this open as a reminder.

**Comment by brentp** [comment]
You can silence these by updating the inheritance module to v0.1.2:
```
$ pip install -U inheritance
```

and then setting GEMINI_WARN_OFF=true in your environment variables.
