### ISSUE TITLE
Record version of GEMINI that created DB

### ISSUE THREAD

**Issue by jxchong** [arq5x/gemini#746]
Since we've been using GEMINI for so long, it's been getting complicated to figure out:
1) what version of GEMINI was used to generate a particular DB
2) what version of GEMINI a particular analysis file was generated with

Is it simple to add a field in each database that stores the version of GEMINI that created the DB such that one could run `gemini db_version mydata.db" or similar command?

Ideally (2) can be tracked more easily by generating a log file (similar to how PLINK always creates a .log file with same prefix as the results file -- but I'm not sure how to implement this since GEMINI currently doesn't know how the results file is named because the output is saved by command-line redirect)

**Comment by brentp** [comment]
you can do:
```
gemini query -q "select * from version" $db
```
to get the gemini version the database was loaded with. I'm inclined to say that tracking that is up to the user, but I guess it could be an option to print that version first.

**Comment by jxchong** [comment]
It's not critical but it does seem somehow a bit messy right now -- we either have to create log files manually or append to the header of the each results file to include information on the command/GEMINI version used. Maybe an option to include in the output file as an extra row?
