### ISSUE TITLE
gemini-intro gist, "KeyError: 'variants'

### ISSUE THREAD

**Issue by paul-shannon** [arq5x/gemini#766]
After a fresh install of gemini, and following the tutorial at 

   https://gist.github.com/arq5x/9e1928638397ba45da2e#file-gemini-intro-sh

the first command fails:

    gemini query -q "SELECT name FROM samples" learnSQL.db
    ...
    KeyError: 'variants'

Looking at the sqlite database,  I see only one table in leanSQL.db, with only these columns:

- sample_id 
- name
- family_id
- paternal_id
- maternal_id
- sex 
- phenotype 
- ethnicity

Perhaps the 'variants' column will be found in another table?

I am running macos 10.11.2, and version 0.19.0 of gemini. 

Thanks,

  - Paul

**Comment by brentp** [comment]
Hi, gemini was expecting there to be a variants table since it can't do much without one. 
I've fixed this here: https://github.com/arq5x/gemini/pull/768
and it will be out in gemini version 0.19.1 soon.

**Comment by brentp** [comment]
this is now in 0.19.1
