### ISSUE TITLE
Corresponding inheritance models to R's VariantFiltering

### ISSUE THREAD

**Issue by komalsrathi** [arq5x/gemini#778]
Hello,

I am moving my code from the R package [VariantFiltering](https://www.bioconductor.org/packages/devel/bioc/manuals/VariantFiltering/man/VariantFiltering.pdf) to Gemini. The following table has the inheritance models from VariantFiltering and the corresponding models in Gemini:

```
VariantFiltering	Gemini
autosomalRecessiveHomozygous	autosomal_recessive
autosomalRecessiveHeterozygous	comp_het
deNovo	de_novo
xLinked	(x_linked_dominant/x_linked_recessive)?
```

Is the conversion correct? I am not sure if VariantFiltering's `xLinked` is Gemini's `x_linked_dominant` or `x_linked_recessive`. Can you clarify?

**Comment by brentp** [comment]
based on the descripton for their xLinked:
```
This function identifies variants that appear only in the X chromosome of the unaffected females
as heterozygous, don’t appear in the unaffected males analyzed and finally are present (as homozygous)
in the affected male(s).
```
that appears to be x-linked-recessive

otherwise, yes, your conversion seems reasoable on quick glance.

**Comment by komalsrathi** [comment]
Alright thanks!
