### ISSUE TITLE
support for python 3.5.x? hg38?

### ISSUE THREAD

**Issue by paul-shannon** [arq5x/gemini#781]
http://gemini.readthedocs.io/en/latest/content/installation.html specifies that gemini requires python 2.7.x.   

Are there any plans to update to 3.5.x?
Any plans to support hg38?

Thanks!
- Paul

**Comment by brentp** [comment]
Hi, we have plans to support both python3 and other species/builds including hg38. The modules supporting gemini: cyvcf2, inheritance, geneimpacts, and the new loader all support python2 and 3, but we'll have some minor work in the main code-base to do that.

**Comment by matthdsm** [comment]
Hi Brent,

Any idea when we could expect those changes? We're very interested in hg38, and would like te try and implement Gemini into our diagnostics pipeline.

Cheers
M

**Comment by brentp** [comment]
you can already use gemini with [vcf2db](https://github.com/quinlan-lab/vcf2db) which will let you use any organism. You'll have to aggregate the annotations, but you can follow this:
https://github.com/brentp/vcfanno/blob/master/example/rare-disease.conf

annotation example with whatever annotations you use for hg38. The idea is to use vcfanno to annotate, then use vcf2db to load.

**Comment by lbeltrame** [comment]
As someone who actually *wrote a new wrapper* to use GEMINI internally with Python 3, I'm looking forward to this.

**Comment by brentp** [comment]
I have pushed most of the changes necessary for python 3 support to my py3 branch. I need to do more testing, but this will go in the next release.

**Comment by brentp** [comment]
python 3 is now supported and hg38 is possible with vcf2db.
