### ISSUE TITLE
Feature: annotation with cancer mutation hotspots

### ISSUE THREAD

**Issue by schelhorn** [arq5x/gemini#784]
For oncology, data about the functional significance of variants that are_not_ in Clinvar or Cosmic is very relevant and cannot always be inferred from sequence-based variant impact analysis. Ideally, we would like to have an annotation for the frequency of a variant in TCGA or other cancer sequencing projects. One such annotation resource is MutationAligner http://www.mutationaligner.org/FAQ as well as the supplement of a recent paper https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-016-2727-x Would it be possible to add this or a similar resource to the GEMINI output and/or database schema?

**Comment by brentp** [comment]
The answer is probably not very satisfying, but once we get the new loader in place, it will be trivial to add new annotations such as this. For now, you can use gemini annotate.

**Comment by schelhorn** [comment]
Thanks, that's what I assumed as well.
