### ISSUE TITLE
How to extract protein position for amino acid change from GEMINI database?

### ISSUE THREAD

**Issue by naumenko-sa** [arq5x/gemini#785]
Hi GEMINI developers!

Thanks for the excellent framework.

Is there a way to extract protein position for amino acid change from GEMINI database
(VEP annotation) I don't see this field in the variants or variant_impacts tables.

All I want is to have the variant effect for protein-coding genes reported in common F234L format.

Thanks.
Sergey

**Comment by brentp** [comment]
Hi, for historical reasons, this is stored in `aa_length` in the database.

**Comment by naumenko-sa** [comment]
Thanks Brent. 
Could you please describe this in the documentation? 
http://gemini.readthedocs.io/en/latest/content/database_schema.html#the-variants-table
Also this field seems to work with VEP. 
SN

**Comment by brentp** [comment]
Yes, meanwhile, a pull-request would be appreciated.
