### ISSUE TITLE
'gemini update' not working to update to v0.19.1

### ISSUE THREAD

**Issue by VelNZ** [arq5x/gemini#789]
Hey guys,

I'm getting this error when running 'gemini update':

Collecting gemini==0.19.1 (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 24))
  Could not find a version that satisfies the requirement gemini==0.19.1 (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 24)) (from versions: 0.6.2, 0.6.2.1, 0.6.2.2, 0.6.3, 0.6.3.1, 0.6.3.2, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.1, 0.12.2, 0.13.0, 0.13.1, 0.14.0, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 0.17.1, 0.17.2, 0.18.0, 0.18.1, 0.18.2, 0.18.3)
No matching distribution found for gemini==0.19.1 (from -r https://raw.github.com/arq5x/gemini/master/requirements.txt (line 24))
Traceback (most recent call last):
  File "/usr/local/bin/gemini", line 6, in <module>
    gemini.gemini_main.main()
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1117, in main
    args.func(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 992, in update_fn
    gemini_update.release(parser, args)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_update.py", line 54, in release
    subprocess.check_call([pip_bin, "install"] + pip_compat + ["-r", url])
  File "/usr/local/share/gemini/anaconda/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/gemini/anaconda/bin/pip', 'install', '--allow-external', 'python-graph-core', '--allow-unverified', 'python-graph-core', '--allow-external', 'python-graph-dot', '--allow-unverified', 'python-graph-dot', '-r', 'https://raw.github.com/arq5x/gemini/master/requirements.txt']' returned non-zero exit status 1

Looks like v0.19.1 isn't listed as an official release that's available for updating?

Cheers,
Vel

**Comment by chapmanb** [comment]
Vel;
Sorry about the issues. What version of gemini are you upgrading from? We substantially improved the install process as of 0.18 but this requires an initial step to fix the install to be compatible with the new versions:

http://gemini.readthedocs.io/en/latest/#new-installation

Hope this helps get GEMINI updated for you.

**Comment by VelNZ** [comment]
Hey @chapmanb, thanks for that. I was updating from 0.15 and installing fresh using the script fixed the problem.
