### ISSUE TITLE
Updating ped file with additional fields

### ISSUE THREAD

**Issue by Vaidhy-M** [arq5x/gemini#791]
Hi, when I try to update samples table with ped file having additional fields using amend, the ped file gets loaded without error. However when I query db_info to look at updated samples table, it shows the following error.

> Traceback (most recent call last):
>   File "/usr/local/bin/gemini", line 6, in <module>
>     gemini.gemini_main.main()
>   File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1227, in main
>     args.func(parser, args)
>   File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 666, in dbinfo_fn
>     gemini_dbinfo.db_info(parser, args)
>   File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_dbinfo.py", line 25, in db_info
>     get_table_info(metadata, table, out_template)
>   File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/gemini/gemini_dbinfo.py", line 13, in get_table_info
>     rec = (table_name, row.name, str(row.type))
>   File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 481, in **str**
>     return unicode(self.compile()).\
>   File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 468, in compile
>     return dialect.type_compiler.process(self)
>   File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 261, in process
>     return type_._compiler_dispatch(self, *_kw)
>   File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
>     return meth(self, *_kw)
>   File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/sqlalchemy/sql/compiler.py", line 2606, in visit_null
>     "type on this Column?" % type_)
> sqlalchemy.exc.CompileError: Can't generate DDL for NullType(); did you forget to specify a type on this Column?

The ped file has a header line as follows,

> # family_id    sample_id   paternal_id maternal_id sex phenotype   asd li  ri  srs

Could you please clarify?

**Comment by brentp** [comment]
hi, what version of gemini is this?

**Comment by Vaidhy-M** [comment]
v0.19.1

**Comment by brentp** [comment]
can you share the ped file that you used? you can email it to me directly or post it here.

**Comment by Vaidhy-M** [comment]
I have emailed you the ped file.

**Comment by brentp** [comment]
gemini amend was just adding columns without specifying the type. I have modfied amend to include the TEXT type. Your database will still have this problem, but the issue will be fixed for future users.

You can also see the schema by doing:
`echo ".schema" | sqlite3 $db`

**Comment by Vaidhy-M** [comment]
Okay, so when I create new db with the next version of GEMINI it will be fixed?

**Comment by brentp** [comment]
that's correct. You can also install gemini from master and get it working today.
