### ISSUE TITLE
wild card with joined tables

### ISSUE THREAD

**Issue by ishengtsai** [arq5x/gemini#792]
Hi, 

I tried to output all gts when combining different tables but with no success. What would be the best way to do it? Any suggestion would be appreciated.

Both 

gemini query \
     -q "SELECT v.chrom, v.start, v.end, v.ref, v.alt, v.gene, g.entrez_id,  v.impact,  v.cyto_band, v.clinvar_sig, v.impact_severity, (v.gts).(*) \
        FROM variants v, gene_detailed g \
     WHERE v.chrom = g.chrom and v.gene = g.gene " db

and

gemini query \
     -q "SELECT v.chrom, v.start, v.end, v.ref, v.alt, v.gene, g.entrez_id,  v.impact,  v.cyto_band, v.clinvar_sig, v.impact_severity, v.(gts).(*) \
        FROM variants v, gene_detailed g \
     WHERE v.chrom = g.chrom and v.gene = g.gene " db

yield no success.

**Comment by brentp** [comment]
just use (gts).(*) without the table designation.

**Comment by ishengtsai** [comment]
Thanks. It works like a charm.

**Comment by brentp** [comment]
great. thanks for following up.
