### ISSUE TITLE
Calculating allele balance for each sample for denovo models

### ISSUE THREAD

**Issue by komalsrathi** [arq5x/gemini#795]
Hi,

I wanted to know if you guys have implemented the issue https://github.com/arq5x/gemini/issues/584 where in you can get allele balance for each sample in the family? Or something similar to `gt_alt_depths/gt_depths`?

I am trying this query:

```
gemini de_novo --columns "(gt_alt_depths).(*),(gt_depths).(*)" EG0039_EG0039P.trio.com.filtered.ad.de.nm.snpeff.anno.db | head

variant_id	gene	gt_alt_depths.EG0039F	gt_alt_depths.EG0039M	gt_alt_depths.EG0039P	gt_depths.EG0039F	gt_depths.EG0039M	gt_depths.EG0039P	family_id	family_members	family_genotypes	samples	family_count
35	WASH7P	0	0	3	18	18	14	EG0039	EG0039F(EG0039F;unaffected;male),EG0039M(EG0039M;unaffected;female),EG0039P(EG0039P;affected;male)	ACC/ACC,ACC/ACC,ACC/A	EG0039P	1
267	AGRN	0	0	4	7	6	7	EG0039	EG0039F(EG0039F;unaffected;male),EG0039M(EG0039M;unaffected;female),EG0039P(EG0039P;affected;male)	C/C,C/C,C/CGT	EG0039P	1
```

I am only interested in the sample EG0039P from this family. Apparently, when I try `(gt_alt_depths).EG0039P` or `(gt_alt_depths).$PROBAND` instead of `(gt_alt_depths).(*)`, it doesn't work. Is it possible to calculate the frequency for a particular sample in the family, or each sample of the family separately, and adding a new column in the database? Something like this: 

```
PROBAND=EG0039P
gemini de_novo --columns "$PROBAND.AB=(gt_alt_depths).$PROBAND/(gt_depths).$PROBAND" EG0039_EG0039P.trio.com.filtered.ad.de.nm.snpeff.anno.db
```

**Comment by brentp** [comment]
That's not implemented yet and unfortunately, you can't do queries like you suggest.

You should be able to do `gt_alt_depths.EG0039P` for just 1 sample.

**Comment by komalsrathi** [comment]
Ya I just figured I was doing (gt_alt_depths).$PROBAND instead of gt_alt_depths.$PROBAND.
