### ISSUE TITLE
 Annovar vs VEP 

### ISSUE THREAD

**Issue by naumenko-sa** [arq5x/gemini#796]
Hi Gemini developers and users!

Thank you for the excellent tool!

Gemini supports VEP/Snpeff annotations.
Do you have any plans to support Annovar or arguments why VEP is better?

Personally I'm ok with VEP, but some people are used to ANNOVAR. Is there any research on VEP vs Annovar?

Thanks,
Sergey

**Comment by brentp** [comment]
If Annovar supports outputing sequence ontology terms into VCF format, then it can easily be added. To my knowledge, it does not yet do that.
