### ISSUE TITLE
Gemini annotate only 100000 records?

### ISSUE THREAD

**Issue by csardas** [arq5x/gemini#803]
Hi, 

I tried to use gemini annotate to extract some information from my VCF to Gemini db.

Only information from top 100000 lines of VCF is stored in db, and returned me 
“update 100000 variants.”

Data after the 100001 line of VCF file was not be processed. 
Is it a limit of gemini annotate? 
How can I annotate all variants in db?

**Comment by brentp** [comment]
Likely all of the variants were annotated, but it didn't give a final number. I'll leave this issue open to remember to print the final value.

**Comment by csardas** [comment]
I tried to print out variant_id, after first chunk processing  and _update_variants()  https://github.com/arq5x/gemini/blob/master/gemini/gemini_annotate.py#L123 
the variant_id will be reset to 1, and break the loop during second chunk,
that make gemini annotate update top 100000 annotations Only

seems _update_variants() change the position of cursor and confuse fetchmany() ?

**Comment by khalidm** [comment]
Hi - I am seeing the same issue on the latest version. Any updates? 
Thanks.

**Comment by brentp** [comment]
can you install the version from git master and retry? I believe that I fixed this in #809 . It's not in a released version yet, but you should just be able to checkout the repo and run python setup.py install.

**Comment by brentp** [comment]
does the latest change resolve this for you?

**Comment by csardas** [comment]
no,
seems the fix doesn't work
the process still end up at 100000 variants
(there are 6,000,000 records in db)

```
('finished updating', 100000, 'variants')
```

**Comment by brentp** [comment]
Hi, sorry for the delay. I pushed a fix for this that simplifies the logic. Please let me know any additional problems.

**Comment by csardas** [comment]
thanks for the fix, it worked.
