### ISSUE TITLE
codon_change blank

### ISSUE THREAD

**Issue by davetang** [arq5x/gemini#807]
I have the same issue as https://github.com/quinlan-lab/vcf2db/issues/21. VEP adds the codon change information to the VCF but it is not stored in GEMINI. I'm using version 0.19.1, which was built around 3 weeks ago.

I had a look at effect.py inside the gemini folder and running `gemini update` did not update the script to "'codon_change': 'Codons',"; it's still with the lowercase "c". (I'm not sure if it's supposed to but thought I'll give it a go.)

**Comment by brentp** [comment]
you'll have to run "pip install -U geneimpacts" and then re-load the database.

**Comment by davetang** [comment]
Is this what I should do? By the way, I'm running this inside Docker and can create the image again.

```
pwd
/usr/local/share/gemini/anaconda/bin

./pip install -U geneimpacts
Requirement already up-to-date: geneimpacts in /usr/local/share/gemini/anaconda/lib/python2.7/site-packages
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

# still not updated
cat ../lib/python2.7/site-packages/geneimpacts/effect.py | grep codon_change
    'codon_change': ['HGVS.c', 'Codon_Change'],
    'codon_change': 'codons',
```

**Comment by davetang** [comment]
I rebuilt the Docker image (re-installed GEMINI) and the problem went away.

**Comment by brentp** [comment]
great! thanks for figuring out. (I forgot to follow up on this.)
