### ISSUE TITLE
protein_altering_variant not being seen as coding

### ISSUE THREAD

**Issue by mmoisse** [arq5x/gemini#812]
I have the impression that VEP annotates bigger indels as _protein_altering_variant_ instead of _protein_altering_variant_ or _inframe_variant_, but as a consequence when I load a VEP annotated vcf into gemini some of my variants are not annotated as _is_coding_ although they should I believe (cfr http://www.sequenceontology.org/miso/current_svn/term/SO:0001818).

Please find attached some sample data

[chrTest12.flt.norm.VEP.vcf.gz](https://github.com/arq5x/gemini/files/739062/chrTest12.flt.norm.VEP.vcf.gz)
[chrTest12.flt.norm.VEP.db.gz](https://github.com/arq5x/gemini/files/739063/chrTest12.flt.norm.VEP.db.gz)

**Comment by brentp** [comment]
thanks for the test-case. I have fixed this in the gene-impacts, module, you can update with: pip install -U geneimpacts.

**Comment by mmoisse** [comment]
Can I update an existing gemini db or should I start gain from vcf?

**Comment by brentp** [comment]
you'll have to start from vcf unless you date to do something like (untested):
```
update variants set is_coding = 1 where impact = 'protein_altering_variant';
```

**Comment by brentp** [comment]
and same for variant_impacts.
