### ISSUE TITLE
Install issue 

### ISSUE THREAD

**Issue by Phillip-a-richmond** [arq5x/gemini#813]
Hello,
I'm attempting to install gemini using the latest method.  I keep getting an error, which looks like some form of error in the path to a specific file.

$ python gemini_install.py /usr/local/ /usr/local/share/gemini/
Checking required dependencies...
 wget found
Installing isolated base python installation
--2017-02-15 15:19:58--  http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
Resolving repo.continuum.io... 104.16.18.10, 104.16.19.10, 2400:cb00:2048:1::6810:130a, ...
Connecting to repo.continuum.io|104.16.18.10|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh [following]
--2017-02-15 15:19:58--  https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
Connecting to repo.continuum.io|104.16.18.10|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-02-15 15:19:58 ERROR 404: Not Found.

Traceback (most recent call last):
  File "gemini_install.py", line 192, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 82, in main
    anaconda = install_anaconda_python(args, remotes)
  File "gemini_install.py", line 131, in install_anaconda_python
    subprocess.check_call(["wget", "--continue", url])
  File "/Users/philliprichmond/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--continue', 'http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh']' returned non-zero exit status 8

Any help?
I have anaconda 2.7 installed, and in my path.  Used home-brew to install wget as well.

Cheers,
Phil

**Comment by chapmanb** [comment]
Phil;
Apologies about the issue, it looks like the Miniconda download link changed slightly. I updated the `gemini_install.py` script so if you get the latest:
```
wget https://github.com/arq5x/gemini/raw/master/gemini/scripts/gemini_install.py
```
it should hopefully work cleanly for you now. Thanks much for reporting the problem.
