### ISSUE TITLE
missing annotations using load -t all

### ISSUE THREAD

**Issue by hoppmann** [arq5x/gemini#816]
Hi,

I've stumbled over an issue when I'm loading vep AND snpeff annotated variants. My typical approach is:

1. decompose and normalize using vt
2. annotate using vep
3. annotate using snpEff
4. load in gemini using -t all option

Resently I've been looking for cDNA positions and figured out that a list of vep annotations are not load in the gemini database when using the "-t all" option. But when using "-t vep" I can find these annotation, even so using the same vcf file. These columns are:

vep_allele
vep_cdna_position
vep_cds_position
vep_distance
vep_existing_variation
vep_feature_type
vep_hgnc_id
vep_intron
vep_strand
vep_symbol_source

Is this a bug, or is this on intended?

Thanks, 
Anselm

**Comment by brentp** [comment]
It was a bug. Thanks much for reporting. I've just pushed a fix for it now. Please try out from master and let me know any problems.
