### ISSUE TITLE
Annotate with vcf FORMAT field

### ISSUE THREAD

**Issue by 444thLiao** [arq5x/gemini#825]
I have try to figure out when I using 'annotate -a extract ' for adding my field from vcf is always failed with responsing nan/none value. When I read its doc third time, I guess it maybe just extract data from INFO field from vcf file?? So it also WARNING me about missing value about AF/AD.

So I want to know, if I want to add own field to db from vcf FORMAT field, how should I do? I also see #311  
But I see the cyvcf, it seem like it just contain a few of tag in vcf FORMAT field. e.g AD,AF and so on.  

So my question is, if I want to extract data from vcf FORMAT field to insert it in gemini db. Isn't it any arg can help me do that? 

Thank you.

**Comment by brentp** [comment]
this is not supported. you can only annotate with the INFO field.  I'm closing this as it's outside of the scope of gemini.

cyvcf2 gives you full access to all format fields so  you can use that to take stuff from the sample fields and put it into the INFO and the anntate with that.

If you are having trouble with using gemini annotate to pull from the INFO, please post the command you are using and the error message.
