### ISSUE TITLE
Update CADD to v1.3

### ISSUE THREAD

**Issue by jxchong** [arq5x/gemini#827]
In the past few weeks, I've been going back and updating information for some of our candidate variants and I noticed that the CADD scores have changed a LOT between v1.0 and v1.3 (e.g. going from nothing noteworthy ~10 to ~25). It's probably worth updating GEMINI's CADD version

http://cadd.gs.washington.edu/download

**Comment by jxchong** [comment]
@brentp I literally posted this simultaneously with your email asking for any final requests.

**Comment by oleraj** [comment]
I would second this.  It would be great if you could add the single nucleotide deletions as well (current GEMINI only has single nucleotide substitutions).

Related: #499
