### ISSUE TITLE
Problems with custom annotations (gemini annotate) 

### ISSUE THREAD

**Issue by andkam** [arq5x/gemini#836]
Hi!

I have problem adding custom annotations in GEMINI - I want to add the SweGen dataset to my database.
command line: gemini annotate -f database.vcf.gz -a extract -c new_col -t float -e AF -o mean my.db
(Version 0.19.0)

At first it seems to work, however, only variants on chromosome 1 gets annotated (but correctly). The problem is the same for all my gemini databases created from whole genome data, but not for the gemini databases that is built from whole exome data. Otherwise my gemini databases seems to work fine, and I have also tried all different kinds of settings for the -t and -o options. My databases with whole genome data are about 25GB. Can they be to big? 

Does anyone have any suggestions?

Best, 
Anders

**Comment by brentp** [comment]
yes, there was a bug in 0.19. If you update gemini to the version here on github the annotation will complete.

**Comment by andkam** [comment]
Thank you very much!


________________________________
