### ISSUE TITLE
Way to use gt-filter to only apply to samples with variant?

### ISSUE THREAD

**Issue by jxchong** [arq5x/gemini#839]
Is there a logical way to make it so that gt-filter only apply to samples with a variant in question? 

Our main use case is filtering for all variants in a given gene where the variant call is of good quality (gt_qual>=20 and gt_depth >=6). If you do `(gt_quals).(*).(>=20)` then you'll only get variants where all samples in the database have GQ>=20, when what you really want is all variants where any sample who has a non-ref genotype has GQ>=20.

**Comment by brentp** [comment]
I just pushed a what to do this. It would be great if you could give it a try and let me know if you have any issues.

**Comment by jxchong** [comment]
From reading your commit notes, it seems like if you had samples A, B, and C; A and B are het for a particular variant, but A's GQ==42 but B's GQ==12, then you wouldn't not retrieve this variant?

**Comment by brentp** [comment]
if you use .(all), then yes, your interpretation is correct.

**Comment by jxchong** [comment]
So I'm trying to retrieve all variants where at least one affected individual is not homref and any individual who is not homref has a good quality call. Here's what I think should do that?

```
    gemini query --header --show-samples -q "SELECT chrom,start,end,ref,alt,gene,impact" \
    --gt-filter "(gt_types).(phenotype==2).(!=HOM_REF).(any) and (gt_quals).(!=HOM_REF).(>=20).(all) and (gt_depths).(!=HOM_REF).(>=6).(all)" myDB.db
```

I get an error though `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "!=": syntax error [SQL: u'SELECT samples.sample_id, samples.name \nFROM samples \nWHERE !=HOM_REF']`

**Comment by brentp** [comment]
It currently has to be of the form:

`(=HET)` not` !=HOM_REF`

I can probably expand to make the latter possible.

**Comment by jxchong** [comment]
Ah the latter would be useful. But I still get the same error when I use `(=HET)`

**Comment by brentp** [comment]
The condition has to be in the 2nd block. So
`(gt_types).(phenotype==2).(=HET).(any)` is not allowed.
but:
`(gt_quals).(=HET)(>20).(all)` is allowed

**Comment by jxchong** [comment]
Ok to make testing simpler I just simplified it down to `--gt-filter "(gt_quals).(=HET).(>=20).(all)"`

but I'm still getting `sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "=": syntax error [SQL: u'SELECT samples.sample_id, samples.name \nFROM samples \nWHERE =HET']`

**Comment by jxchong** [comment]
Ok, just did some testing and I realized this doesn't go all the way to what we would need although it is useful.

The goal is to be able to replicate the built-in tools analyses, where so long as all the individuals in a given family have good quality calls, the variant will show up in the results, even if other samples not in that family have missing calls. So I think the analogous situation I'm aiming for with `gt-filter`, since it isn't family-aware, is to output all good quality calls that meet the genotype criteria in at least one sample.

In this example, when I am looking for GQ>=20 and DP>=6, I would want to keep this variant in the output because sample4 and sample6 are both het and meet my GQ and DP cutoffs. Right now it gets excluded because sample1 is het and fails the cutoff.

| | sample1 | sample2 | sample3 | sample4 | sample5 | sample6 | sample7
| --- | --- | --- | --- | --- | --- | --- | --- |
| | A/. | A/A | A/A | A/AAAAAT | A/A | A/AAAAAT | A/A
| DP | 13 | 23 | 32 | 12 | 8 | 13 | 22
| GQ | 3 | 60 | 63 | 84 | 21 | 99 | 60
