### ISSUE TITLE
building .db with PED file, structure is wrong?

### ISSUE THREAD

**Issue by rachelgfox** [arq5x/gemini#840]
Hi everyone,

When I load in a ped file with my vcf:
`gemini load -v hayflick2_7_vep.vcf -p 5_2_PEDIGREE.txt -t VEP --cores 3 5_2_hayflick.db`

I can successfully build the database, but when I go to look at the pedigree:
`gemini query -q "SELECT * FROM samples" --header 5_2_hayflick.db `

What comes back is a huge thing of "none" and seemingly overlapping information. Like it loaded on top of itself?
![screen shot 2017-05-02 at 11 18 29 am](https://cloud.githubusercontent.com/assets/11955654/25632774/ca0ebc60-2f29-11e7-92e6-341187580e0e.png)

Any ideas? What is going on here? I checked to make sure my ped file is only spaced with tabs. But I could just make it again to be sure?
![screen shot 2017-05-02 at 11 25 10 am](https://cloud.githubusercontent.com/assets/11955654/25632842/08744f56-2f2a-11e7-87c7-c535cc5eda98.png)

Thanks all in advance!

**Comment by brentp** [comment]
can you share your .ped file?

**Comment by rachelgfox** [comment]
Here is the text file. Thanks Brent!
[5_2_PEDIGREE.txt](https://github.com/arq5x/gemini/files/971827/5_2_PEDIGREE.txt)

**Comment by brentp** [comment]
Hi, you have mac line endings in the file. I fixed them in the attached so it should load. On linux, you may have a mac2unix tool to convert them for you or you can google how to do that. It's a PITA, but happens from time to time.

[5_2_PEDIGREE.txt](https://github.com/arq5x/gemini/files/971848/5_2_PEDIGREE.txt)

**Comment by rachelgfox** [comment]
Thank you so much, I would have spent hours trying to figure that out! 👿
