### ISSUE TITLE
X-linked de novo and autosomal de novo behavior inconsistent when 1 parent missing

### ISSUE THREAD

**Issue by jxchong** [arq5x/gemini#843]
If you have only a parent-child duo available, de_novo will not run or produce results because one parent is missing. However X-linked de novo will produce results. I'm thinking that since X-linked de novo is a pretty new command, it might make sense to modify it to behave like de novo and not output any results?

**Comment by jxchong** [comment]
@brentp can this be part of the 0.20 release?

**Comment by oleraj** [comment]
I just noticed this issue as well.  I agree with @jxchong that it makes sense to modify the x-linked de novo command.  It might be nice to have an error message as well (for both tools) so the user knows the reason there are no results.
