### ISSUE TITLE
de_novo analysis does not return variants for which the parent genotypes weren't called

### ISSUE THREAD

**Issue by ehitchcock** [arq5x/gemini#844]
I recently started using gemini and decided to re-analyze a trio in my study. The de_novo analysis tool did not return a variant that I already have confirmed to be de novo in the child. 

These are the column headings for the attached screenshot of variant in my merged vcf.
#CHROM POS ID REF ALT QUAL FILTER INFO FORMAT FATHER MOTHER PROBAND

When I looked at the bam files on IGV the parents are clearly homozygous for the reference allele.
I think the de_novo tool might not be working because the genotypes for the parents weren't called. Is there an option for that would allow me to call these types of variants?

Thanks!
![fam7](https://cloud.githubusercontent.com/assets/19938933/26179338/0692dee2-3b18-11e7-917a-c1de47d4b596.png)

**Comment by brentp** [comment]
If the parents are homozygous for the reference allele, they should be coded as 0/0. Did you call variants in the samples separately and then merge the VCFs? If so, gemini will not be of use to you.

**Comment by ehitchcock** [comment]
Okay thanks!
