### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by ehitchcock** [arq5x/gemini#845]
I am trying to install gemini and continue to get the error below.
I have installed Anaconda and Miniconda and put the path in my .bash_profile.

I have successfully installed gemini on a different mac following the same steps.
Any help would be much appreciated!

ehitchcock$ python gemini_install.py /Users/ehitchcock/GEMINI/gemini_tools /Users/ehitchcock/GEMINI/gemini_data
Checking required dependencies...
 wget found
Installing isolated base python installation
--2017-05-18 11:52:54--  http://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.16.18.10, 104.16.19.10, 2400:cb00:2048:1::6810:130a, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.16.18.10|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh [following]
--2017-05-18 11:52:54--  https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh
Connecting to repo.continuum.io (repo.continuum.io)|104.16.18.10|:443... connected.
ERROR: cannot verify repo.continuum.io's certificate, issued by ‘CN=thawte SSL CA - G2,O=thawte\\, Inc.,C=US’:
  Unable to locally verify the issuer's authority.
To connect to repo.continuum.io insecurely, use `--no-check-certificate'.

Traceback (most recent call last):
  File "gemini_install.py", line 191, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 81, in main
    anaconda = install_anaconda_python(args, remotes)
  File "gemini_install.py", line 130, in install_anaconda_python
    subprocess.check_call(["wget", "--continue", url])
  File "/Users/ehitchcock/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', '--continue', 'http://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh']' returned non-zero exit status 5

**Comment by chapmanb** [comment]
Thank you for the report and apologies about the issue. I pushed a fix to the latest version of gemini_install.py that should resolve this. If you replace your previous version and re-run the automated install (http://gemini.readthedocs.io/en/latest/#new-installation) hopefully this will work cleanly for you now. Thanks again.

**Comment by ehitchcock** [comment]
Thanks very much!!

I am getting a second install error now:

gemini-0.20.0- 100% |#######################################################################################################| Time: 0:00:08   1.50 MB/s
/Users/ehitchcock/GEMINI/gemini_data/anaconda/bin/gemini --annotation-dir /Users/ehitchcock/GEMINI/gemini_data/gemini_data update --dataonly --tooldir /Users/ehitchcock/GEMINI/gemini_tools
Upgrading associated tools...
* downloading https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz to /Users/ehitchcock/GEMINI/gemini_data/gemini_data

--2017-05-23 10:28:00--  https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.80.235
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.80.235|:443... connected.
ERROR: cannot verify s3.amazonaws.com's certificate, issued by ‘CN=DigiCert Baltimore CA-2 G2,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to s3.amazonaws.com insecurely, use `--no-check-certificate'.
wget failed with non-zero exit code 5. Retrying
--2017-05-23 10:28:10--  https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.72.10
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.72.10|:443... connected.
ERROR: cannot verify s3.amazonaws.com's certificate, issued by ‘CN=DigiCert Baltimore CA-2 G2,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to s3.amazonaws.com insecurely, use `--no-check-certificate'.
wget failed with non-zero exit code 5. Retrying
--2017-05-23 10:28:20--  https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.64.35
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.64.35|:443... connected.
ERROR: cannot verify s3.amazonaws.com's certificate, issued by ‘CN=DigiCert Baltimore CA-2 G2,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to s3.amazonaws.com insecurely, use `--no-check-certificate'.
wget failed with non-zero exit code 5. Retrying
Traceback (most recent call last):
  File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 170, in <module>
    install_annotation_files(args.anno_dir, args.dl_files, args.extra)
  File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 105, in install_annotation_files
    to_dl, anno_dir, cur_config)
  File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 123, in _download_anno_files
    cur_config.get("versions", {}).get(orig, 1))
  File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 151, in _download_to_dir
    raise ValueError("Failed to download with wget")
ValueError: Failed to download with wget
Traceback (most recent call last):
  File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
    args.func(parser, args)
  File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1080, in update_fn
    gemini_update.release(parser, args)
  File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_update.py", line 38, in release
    subprocess.check_call([sys.executable, _get_install_script(), config["annotation_dir"]] + extra_args)
  File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ehitchcock/GEMINI/gemini_data/anaconda/bin/python', '/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py', '/Users/ehitchcock/GEMINI/gemini_data/gemini_data']' returned non-zero exit status 1
Traceback (most recent call last):
  File "gemini_install.py", line 191, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 84, in main
    install_rest(gemini, args)
  File "gemini_install.py", line 149, in install_rest
    subprocess.check_call(cmd)
  File "/Users/ehitchcock/miniconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ehitchcock/GEMINI/gemini_data/anaconda/bin/gemini', '--annotation-dir', '/Users/ehitchcock/GEMINI/gemini_data/gemini_data', 'update', '--dataonly', '--tooldir', '/Users/ehitchcock/GEMINI/gemini_tools']' returned non-zero exit status 1
