### ISSUE TITLE
Second Install Issue

### ISSUE THREAD

**Issue by ehitchcock** [arq5x/gemini#848]
Hey, I am trying to install Gemini on one of my computers. I have been getting errors during install. @chapmanb kindly fixed the first error I was getting (Issue #845), but now I'm getting another error. It looks to be the same sort of problem, I think. 

Thank you very much for all your help!

Emma

This is the second install error:

gemini-0.20.0- 100% |#######################################################################################################| Time: 0:00:08 1.50 MB/s
/Users/ehitchcock/GEMINI/gemini_data/anaconda/bin/gemini --annotation-dir /Users/ehitchcock/GEMINI/gemini_data/gemini_data update --dataonly --tooldir /Users/ehitchcock/GEMINI/gemini_tools
Upgrading associated tools...

downloading https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz to /Users/ehitchcock/GEMINI/gemini_data/gemini_data
--2017-05-23 10:28:00-- https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.80.235
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.80.235|:443... connected.
ERROR: cannot verify s3.amazonaws.com's certificate, issued by ‘CN=DigiCert Baltimore CA-2 G2,OU=www.digicert.com,O=DigiCert Inc,C=US’:
Unable to locally verify the issuer's authority.
To connect to s3.amazonaws.com insecurely, use --no-check-certificate'. wget failed with non-zero exit code 5. Retrying --2017-05-23 10:28:10-- https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.72.10 Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.72.10|:443... connected. ERROR: cannot verify s3.amazonaws.com's certificate, issued by ‘CN=DigiCert Baltimore CA-2 G2,OU=www.digicert.com,O=DigiCert Inc,C=US’: Unable to locally verify the issuer's authority. To connect to s3.amazonaws.com insecurely, use--no-check-certificate'.
wget failed with non-zero exit code 5. Retrying
--2017-05-23 10:28:20-- https://s3.amazonaws.com/gemini-annotations/hg19_fitcons_fc-i6-0_V1-01.bed.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.64.35
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.64.35|:443... connected.
ERROR: cannot verify s3.amazonaws.com's certificate, issued by ‘CN=DigiCert Baltimore CA-2 G2,OU=www.digicert.com,O=DigiCert Inc,C=US’:
Unable to locally verify the issuer's authority.
To connect to s3.amazonaws.com insecurely, use `--no-check-certificate'.
wget failed with non-zero exit code 5. Retrying
Traceback (most recent call last):
File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 170, in 
install_annotation_files(args.anno_dir, args.dl_files, args.extra)
File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 105, in install_annotation_files
to_dl, anno_dir, cur_config)
File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 123, in _download_anno_files
cur_config.get("versions", {}).get(orig, 1))
File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py", line 151, in _download_to_dir
raise ValueError("Failed to download with wget")
ValueError: Failed to download with wget
Traceback (most recent call last):
File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/bin/gemini", line 7, in 
gemini_main.main()
File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1244, in main
args.func(parser, args)
File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_main.py", line 1080, in update_fn
gemini_update.release(parser, args)
File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/gemini_update.py", line 38, in release
subprocess.check_call([sys.executable, _get_install_script(), config["annotation_dir"]] + extra_args)
File "/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/subprocess.py", line 186, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ehitchcock/GEMINI/gemini_data/anaconda/bin/python', '/Users/ehitchcock/GEMINI/gemini_data/anaconda/lib/python2.7/site-packages/gemini/install-data.py', '/Users/ehitchcock/GEMINI/gemini_data/gemini_data']' returned non-zero exit status 1
Traceback (most recent call last):
File "gemini_install.py", line 191, in 
main(parser.parse_args())
File "gemini_install.py", line 84, in main
install_rest(gemini, args)
File "gemini_install.py", line 149, in install_rest
subprocess.check_call(cmd)
File "/Users/ehitchcock/miniconda2/lib/python2.7/subprocess.py", line 186, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/ehitchcock/GEMINI/gemini_data/anaconda/bin/gemini', '--annotation-dir', '/Users/ehitchcock/GEMINI/gemini_data/gemini_data', 'update', '--dataonly', '--tooldir', '/Users/ehitchcock/GEMINI/gemini_tools']' returned non-zero exit status 1

**Comment by chapmanb** [comment]
Emma;
Thanks for the follow up and apologies about missing your earlier message on #845. I pushed a fix that should resolve this by using `--no-check-certificate`. You'll have to update to the latest development version to use, so should do:
```
/Users/ehitchcock/GEMINI/gemini_data/anaconda/bin/gemini --annotation-dir /Users/ehitchcock/GEMINI/gemini_data/gemini_data update --devel --tooldir /Users/ehitchcock/GEMINI/gemini_tools'
```
Hope that fixes it for you and gets a clean gemini install. Thanks again for the reports.

**Comment by ehitchcock** [comment]
Thank you Brad, it installed successfully!
