### ISSUE TITLE
Dependency missing: Bottle 

### ISSUE THREAD

**Issue by RS91** [arq5x/gemini#849]
Hi,

Am trying to installing gemini on a new machine with no sudo access and keep hitting this error:

_Checking required dependencies..._
 _wget found_
_Installing isolated base python installation_
_Installing base gemini package..._
_~/GEMINI_NEW/anaconda/bin/conda install --yes -c bioconda gemini_
_Fetching package metadata ..........._
_Solving package specifications:_ 

_PackageNotFoundError: Dependency missing in current linux-64 channels:_
_- gemini -> bottle_

_Close matches found; did you mean one of these?_
    _bottle: bottleneck, bottlechest_

Is this dependency missing from anaconda or is this instance specific error for my install?

Best wishes,
Roshan

**Comment by chapmanb** [comment]
Roshan;
Thanks for the report and sorry about the issue. This package recently moved out of bioconda into the more general conda-forge channel and we hadn't yet updated the install script to reflect this. I pushed a fixed version that includes that, so if you re-download `gemini_install.py` and re-run it should hopefully work cleanly for you now. Thanks again.
