### ISSUE TITLE
Gemini API

### ISSUE THREAD

**Issue by matthdsm** [arq5x/gemini#853]
Hi, 

We're looking to build a somewhat elaborate GUI for variant interpretation. Are there any plans to expand the API functionality and/or add more documentation? Ideally, we'd like to use the API for all query types, to avoid having to do system calls (if we decide to go with Python of course).

Thanks
M

**Comment by brentp** [comment]
You might want to look at the other GUI's available, e.g. https://github.com/robinandeer/puzzle
But you can use the `GeminiQuery` object to do queries and then the inheritance models each have their own classes. You can see the examples of this in gemini's browser:
https://github.com/arq5x/gemini/blob/master/gemini/gemini_browser.py
