### ISSUE TITLE
Incorrect regex in make-gnomad.sh script

### ISSUE THREAD

**Issue by mbootwalla** [arq5x/gemini#855]
Hello Gemini Developers,

The make-gnomad.sh script that is used to process and prepare the gnomad exomes vcf for use with gemini has a bug in the perl regex that is used to remove \*_HIST\* columns from the INFO field. The regex causes removal of all INFO fields after the initial AC field up to the AC_AFR field for multi-allelic variants only. Adding a semi-colon to the regex should fix the issue. Here's the updated regex to use: `'s/(;[^_\s;]+_HIST(_AL[LT])?=[^;]+)//g'`. For more details see my post in the gemini google group here: [https://groups.google.com/forum/#!topic/gemini-variation/6u6HUO2PHr0](url)

Let me know if you need any more information.

Thanks,

Moiz

**Comment by brentp** [comment]
thanks for finding this. would you mind opening a pull request to fix make-gnomad.sh?

**Comment by mbootwalla** [comment]
@brentp Sent in a pull request for this fix.
