### ISSUE TITLE
most severely affected transcript

### ISSUE THREAD

**Issue by AlisonCT** [arq5x/gemini#865]
Where a variant affects two transcripts with equal severity protein coding mutations, which does gemini return as the most severely affected? 

Apologies if this is covered elsewhere - I haven't been able to find an answer! 

Thank you for your help

**Comment by arq5x** [comment]
@brentp - if there is a tie (e.g., two transcripts that have splice_donor (HIGH)), is the transcript chosen randomly?

**Comment by brentp** [comment]
it is not random, but it will choose a single transcript as the highest impact and that choice will be the same each time. It is determined according to these rules:
https://github.com/brentp/geneimpacts/blob/master/geneimpacts/effect.py#L339-L388

**Comment by AlisonCT** [comment]
Thank you for your reply and the link.

Reading through the code it looks to me as if there would still be cases where two transcripts are tied for the most severely affected - in those cases is the top choice just which ever sort puts first?

Thanks again.

**Comment by brentp** [comment]
> Reading through the code it looks to me as if there would still be cases where two transcripts are tied for the most severely affected - in those cases is the top choice just which ever sort puts first?

if you need all of the transcripts, you can use the variant_impacts table, this is a limitation with storing only a single effect per variant in the main variants table.
