### ISSUE TITLE
unrecognized arguments: test.snpeff.vcf.db

### ISSUE THREAD

**Issue by idamaumea** [arq5x/gemini#874]
Hello

I am new to programming and new to Gemini, but I am trying to learn, and I understand my question is very very basic. I've had help to get everything in order, and I know that everything works, it's me who doesn't understand why this error occurs. I've tried to start learning by using Gemini's test examples. But I get an error on my .db file. I have tried to google around but I have no clue what I am doing wrong. The .db file has tables, that I have checked (if it matters).

[idama@mps test]$ gemini query -q select 'chrom from variants' --header test.snpeff.vcf.db
usage: gemini [-h] [-v] [--annotation-dir ANNOTATION_DIR]
              {actionable_mutations,amend,annotate,autosomal_dominant,autosomal_recessive,bcolz_index,browser,burden,comp_hets,db_info,de_novo,dump,examples,fusions,gene_wise,interactions,load,load_chunk,lof_interactions,lof_sieve,mendel_errors,merge_chunks,pathways,qc,query,region,roh,set_somatic,stats,update,windower,x_linked_de_novo,x_linked_dominant,x_linked_recessive}
              ...
gemini: error: unrecognized arguments: test.snpeff.vcf.db
[idama@mps test]$ 

Thank you.

**Comment by idamaumea** [comment]
I resolved it myself. It should be "select chrom from variants"

**Comment by roryk** [comment]
haha-- I think I ask questions and then solve them immediately afterward about 50% of the time. :) Thanks for following up!
