### ISSUE TITLE
Update to latest version of inheritance in requirements.txt

### ISSUE THREAD

**Issue by oleraj** [arq5x/gemini#879]
I have been working on validating our installation of gemini 0.20 and everything was working fine except x_linked_recessive.  It appears the requirements file still says `inheritance>=0.1.2` but it should say 0.1.3 since there is a bug in 0.1.2 that was fixed in 0.1.3 when you have unaffected female siblings that might be homozygous recessive.  We will update it manually, but for future releases it would be good to have it install automatically.
Thanks!

**Comment by brentp** [comment]
added. thanks.
