### ISSUE TITLE
--nosudo not working

### ISSUE THREAD

**Issue by Vaidhy-M** [arq5x/gemini#881]
I am trying to install GEMINI without admin access and it fails saying

`gemini_install.py: error: unrecognized arguments: --nosudo`

This is the command I used,

`python gemini_install.py ~/gemini ~/gemini --nosudo`

**Comment by brentp** [comment]
Hi, gemini doesn't use sudo any more, so just run without `--nosudo`.
I just removed the last remnants of that from the docs. thanks for reporting.

**Comment by Vaidhy-M** [comment]
Thank you so much for the quick response!
