### ISSUE TITLE
cool  filtering variant gui using gemini  

### ISSUE THREAD

**Issue by aurelBZH** [arq5x/gemini#883]
Hi, 
thanks for gemini, it's a great framework.
Do you know there is a great application to filter genetic variants, with a graphical user interface based on gemini ? It's called Varapp, you can find it here :  https://varapp-demo.vital-it.ch/docs/src/about.html
and test it here : https://varapp-demo.vital-it.ch/ . I think it's really good.

 I'm not one of the developer of the project, i find it while looking for GUI to filter and annotate variant.

Aurélien

**Comment by brentp** [comment]
Hi, I forgot to reply to this. Yes, we were aware of it. We should have a list somewhere of things like these. 

I think varapp has its own code for inheritance models and only uses gemini to store the data. But, yes, a very nice UI for querying.
