### ISSUE TITLE
Transmission of Dominant De Novos

### ISSUE THREAD

**Issue by parkesK** [arq5x/gemini#885]
Hi there,

I am using Gemini version 0.20.1, and I am trying to analyze a multigenerational pedigree. However, I am not having much luck.

The pedigree (from the perspective of the youngest family member) is: two maternal grandparents, both unaffected; two parents, mom is affected, dad is unaffected; one daughter, who is affected.

I am expecting an autosomal dominant inheritance where the mom acquired a de novo mutation that was then passed down to the daughter. However, when I try:

gemini autosomal_dominant *.db –lenient
Nothing comes out.

I also ran two trios: 1) grandma, grandpa, mom, and 2) mom, dad, daughter, and found a couple de novo variants in the mom that also came through an autosomal_dominant filter for the daughter in the 2nd trio.
Based off of this result, I was expecting some candidates to come through, but my logic could be wrong here.

I also tried gemini query -q "select * from variants" --gt-filter "gt_types.grandma == HOM_REF and gt_types.grandpa == HOM_REF and gt_types.dad == HOM_REF and gts.mom == gts.daughter and gt_types.mom == HET and gt_types.daughter == HET" *.db

This produced a lot of candidates, and is similar enough (?) to the multigenerational autosomal dominant logic, so I thought this might also give a good indication of if any candidates should come through.

Would it be possible to get gemini to accommodate this case?

Thanks!

**Comment by brentp** [comment]
Thanks for reporting, could you try:
```
pip install git+https://github.com/brentp/inheritance@auto-dom-de-novo
```
and then re-run?
This will update the inheritance module to the branch where I've made a fix.

**Comment by parkesK** [comment]
Great! I have put a ticket in to get this installed. 

Do I still need to use the --lenient flag for this case?

**Comment by brentp** [comment]
For now, yes, lenient will still be required. I'll revisit this and see what other changes I can make.

**Comment by parkesK** [comment]
Hi Brent,

I have installed this change, but I am still not getting any results from using autosomal_dominant.
I am treating all other family members besides the mother and daughter as unaffected (no unknown phenotypes). Where is the code for this? I am interested in understanding why this change does not work for this pedigree.

Thanks,
Parkes

**Comment by brentp** [comment]
https://github.com/brentp/inheritance in the auto-dom-de-novo branch. PR's accepted. Otherwise, I'll have a careful look at this later this month.

**Comment by parkesK** [comment]
Great, thank you. I will let you know if I come up with anything. Otherwise, I will wait to hear from you about any changes!

Thanks,
Parkes

**Comment by oleraj** [comment]
@parkesK 

> The pedigree (from the perspective of the youngest family member) is: two maternal grandparents, both unaffected; two parents, mom is affected, dad is unaffected; one daughter, who is affected.

>I am expecting an autosomal dominant inheritance where the mom acquired a de novo mutation that was then passed down to the daughter.

I remember there was some discussion about this back when the support for multi-generational pedigrees was added.  See this gist (Aaron's comment near the end):
https://gist.github.com/brentp/4b3cbeebfaa7360b5ce6
This scenario might be included in the de_novo model.  Did you try running de_novo for the full family?

**Comment by parkesK** [comment]
Hi @oleraj ,

Good idea. I just tried de_novo, however, and am still not getting any results. I also tried de_novo for the database where one of the mom's parent's phenotypes is changed to unknown, and did not get any results.

-Parkes

**Comment by parkesK** [comment]
@brentp Has there been any progress on this ticket?

Thanks,
Parkes

**Comment by jxchong** [comment]
@oleraj @brentp @parkesK Not sure if this was ever resolved, but as far as I know, de_novo does not support multi-generational inheritance because it requires there to be at least 1 affected kid in the database with unaffected parents (and in the case of a single family, the parents are homref) while autosomal_dominant requires an affected parent to pass the variant on to an affected child (and in the case of generation 1 in @parkesK pedigree, both grandparents are unaffected.

When we analyze these, we do one of few things: either manually write up a `--gt-filter` query, use the `gene_wise` query and split the grandchild into its own pedigree such that you're then looking for a de novo in the mother + grandparents and a het variant in the same gene in the grand child, or do the same split and use de_novo and autosomal_dominant separately.

**Comment by brentp** [comment]
I think I see a way to support this in a straightforward and intuitive way. It has the consequence that an affected child with an affected parent will never have any de novos called. I think this jives with the other assumptions in gemini's inheritance models, but I'd be happy to hear feedback.

**Comment by jxchong** [comment]
@brentp I think it's ok to not be able to call de novos (using de_novo) in an affected child with an affected parent because you wouldn't be looking for de novos as the causal in that case (excluding mosaicism which is an edge case you don't handle anyway)

**Comment by brentp** [comment]
great. thanks for feedback. I have this implemented. will be out for next release.
