### ISSUE TITLE
Tutorial file issues

### ISSUE THREAD

**Issue by sormond** [arq5x/gemini#896]
Hey, there is an issue with the turotial files at https://s3.amazonaws.com/gemini-­‐tutorials/dominant.ped and https://s3.amazonaws.com/gemini-%C2%AD%E2%80%90tutorials/trio.trim.vep.vcf.gz

Thanks

**Comment by roryk** [comment]
Hi @sormond,

Sorry for the problem-- those URLs look like they got mangled during cut and pasting to me, not sure if is that way in the tutorial or just on the issue. At any rate:

https://s3.amazonaws.com/gemini-tutorials/dominant.ped
https://s3.amazonaws.com/gemini-tutorials/trio.trim.vep.vcf.gz

seem to work fine. 

Thanks!

**Comment by sormond** [comment]
Hi roryk,

Sorry, it seems that they were on copy and pasting, just added an extra '-' which I didn't notice. Sorry about that!

Thanks
