### ISSUE TITLE
X-linked recessive model needs to handle het calls in males

### ISSUE THREAD

**Issue by jxchong** [arq5x/gemini#903]
We had a huge project with hundreds of samples and noticed spurious variants showing up under the X-linked recessive model that should be in X-linked de novo. In all cases so far, the proband was male and HET and parents unaffected and HOMREF. (this is distinct from issue #843).

I'm guessing the X-linked recessive model code doesn't have specific handling for scenarios where males show up as het (either from variants in the pseudoautosomal region, calling artifacts, contamination, or mosaicism). I think you probably need to add handling such that if a male affected/proband is het for an X chr call and both parents are homref, the variant should be X de novo. If a male proband is het and so is the affected mother, then it should be X-linked recessive (with the caveat that there's got to be something unusual about the call in the male proband).

FYI @oleraj

**Comment by brentp** [comment]
For x-linked recessive, for affected males, we just require not HOM_REF or UNKNOWN. And unaffected males must be HET, unaffected females must be HET or HOM_REF. 

I think the solution to your concern here is to simply remove putative (x recessive) calls from samples that unaffected parents. Is that correct?

**Comment by jxchong** [comment]
Yeah. Or actually the more accurate option might be to have a lenient option that allows for unaffected mothers to pass on the variant and otherwise it would default to strict such that unaffected people cannot have the variant?

**Comment by brentp** [comment]
I'd like to avoid --lenient if possible. It creates too many questions and not using that flag is almost always the right answer. I could be convinced otherwise, but do you think the solution I propose will meet expectations nearly all of the time?

**Comment by jxchong** [comment]
Ok sorry for delay, needed time to think things through.  

First, can you modify XLR and XLdenovo to be limited to the X chromosome? That helps reduce the mess anyway.

Second, I think the solution is for XLR to require affected males to be HOM_ALT (hemizygous), unaffected males should be HOM_REF, affected females should be HET or HOM_ALT, unaffected females should be HET or HOM_REF.

XLde novo: affected males should be HOM_ALT (hemizygous) or HET, unaffected males should be HOM_REF, affected females should be HET, unaffected females should be HOM_REF.

I'm not sure how to handle the unknown genotype situation, so I'll leave that to you :)

**Comment by jxchong** [comment]
@brentp circling back to this. We're currently having to manually review all outputs from these models and remove the ones where a male is showing up as het.

**Comment by brentp** [comment]
I think the solution is to facilitate outputting the HET,HOM_REF,HOM_ALT status for each sample so it's a simple filter on the results. Would that be sufficient for you?
Otherwise, we'd have to implement a --lenient to satisfy those who want HET calls to appear as de-novo.

I suppose we could default to filtering to the X chrom, but since gemini now supports non-human, that would rule out cases where the female chromosome is named "X" or "chrX".

**Comment by jxchong** [comment]
What about supporting cases where the female chromosome is X or chrX? I think these built-in X-linked models aren't necessarily great for non-human species anyway since sex determination can be vastly different (females can be the ones that are hemizygous; or sex is not determined by the chromosomes).

I don't think outputting those is a great solution because it doesn't scale -- if you have 90 trios, you'd have to manually figure out which of the samples are male, then write scripts to filter for only variants where those males have the correct genotype. 

I don't think you need to implement `--lenient` though? For changes to the genotype filtration, I'm only talking about modifying the X-linked recessive model -- don't show variants where the male is het and parents are homref in the X-linked recessive model because those variants *already* show up in the X-linked de novo model.

**Comment by brentp** [comment]
Now that I'm looking at the code, it looks like I added it to filter to X or chrX in f15706b6 . So, I assume that's not working for you? Regardless, I'll just make them use X, chrX on your recommendation.

Likewise, for x-recessive, I will exclude sites where the male is het and parents are hom ref.

**Comment by jxchong** [comment]
Hmm let me revisit. Maybe I was looking at old results (re: X/chrX). Thanks for the X-recessive change!!

**Comment by jxchong** [comment]
How do I get the change to X-recessive? Do I need to download a dev build?

**Comment by oleraj** [comment]
@brentp 
Would it be possible to make a new stable release that includes this change (and other new changes)?  We tried to install from master and there were quite a few errors in the test script so we would prefer to work with a named release in production here if possible.  Thanks!

**Comment by brentp** [comment]
@jxchong you can just install from source (with python setup.py install, where python is the gemini_python). I'll open another issue to track what needs to be done for a new release.

**Comment by brentp** [comment]
@jxchong, I have fixed this for het males. You can get this by simply updating the inheritance module: `pip install -U inheritance`
and making sure you have version: inheritance-0.1.4

**Comment by brentp** [comment]
this is now fixed. will be out in next release.
