### ISSUE TITLE
Connecting to PostgreSQL or other databases?

### ISSUE THREAD

**Issue by JHibbard** [arq5x/gemini#916]
Hello, I've been experimenting with vcf2db to create non-sqlite databases for gemini, but I'm not sure how to connect to the newly created database with gemini.  I'm having trouble finding documentation for this, is there an example or piece of documentation?  Thanks!  This is an amazing tool :)

**Comment by brentp** [comment]
instead of using a sqlite.db path as the final argument, just use, e.g. `"postgres://brentp:password@localhost/gemini"`

**Comment by JHibbard** [comment]
Thank you!  I didn't realize that was a sqlalchemy connection string and not a file path.
