### ISSUE TITLE
GATK4 compatibility?

### ISSUE THREAD

**Issue by SarahBeecroft** [arq5x/gemini#922]
HI, 

We've been trying to move to GATK4 from GATK3, but now we are not getting the same variants output when we query the database (even though we're using the same samples). We are pretty stumped, as the process works to completion without errors. I even tried with the joint VCF made from BcBio in case I'd stuffed the 'homemade' pipeline somewhere. It seems that we mainly/only get rubbish/artifact variants now? I also tried without the VQSR step, but the outcome is the same. We use VEP annotation. Any help would be greatly appreciated! Thanks!

**Comment by brentp** [comment]
Can you share a small ~20 line VCF that, when you load, gives unexpected results?
It's hard to know from your description if this is something in gemini or something peculiar about VCF.

**Comment by SarahBeecroft** [comment]
[failed_VCF.txt](https://github.com/arq5x/gemini/files/2929573/failed_VCF.txt)
Ok sure. This is 50 lines but please let me know if you need more. I can also give and example of one that worked. they're both VCF4.2 from what I can see. thanks!!

**Comment by brentp** [comment]
I mean the first 50 lines after the header (and the header).

**Comment by SarahBeecroft** [comment]
[failed_VCF.txt](https://github.com/arq5x/gemini/files/2934034/failed_VCF.txt)
ah sorry

**Comment by brentp** [comment]
well, that's easy, that appears to be a gvcf (and every single genotype in there is ./.)

**Comment by SarahBeecroft** [comment]
That would do it!! thanks very much!
